2nd Edition of The Enterprise Path to Service Mesh Architectures
layer5io/layer5 pull request #1013
Opened 2020-10-24 07:26 UTC by akashgp09

**Description**
Added The 2nd Edition of The Enterprise Path to Service Mesh Architectures

This PR fixes #883 

**Screenshots**
<img src="https://i.imgur.com/YaC5o2G.png">
<img src="https://i.imgur.com/of2MzzC.png">

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2020-10-24 08:04 UTC, leecalcote requested changes
Thanks, @akashgp09

2020-10-24 08:04 UTC, leecalcote commented on collections/_books/2020-10-24-the-enterprise-path-to-service-mesh-architectures-2nd-Edition.md
> +date:   2018-06-11 21:15:05 +0000
Let’s bring this date forward to now.

2020-10-24 08:04 UTC, leecalcote commented on collections/_books/2020-10-24-the-enterprise-path-to-service-mesh-architectures-2nd-Edition.md
> +redirect_from:
We can safely remove this redirect. This duplicate will cause conflict Withrow eh existing redirect.

2020-10-25 12:24 UTC, akashgp09 commented
Hey @leecalcote are the changes ok ?

2020-10-25 12:46 UTC, kishore007k commented
![Capture29](https://user-images.githubusercontent.com/34863222/97107492-e92c8000-16ed-11eb-94a2-3ef4da659be8.PNG)
The Book Image is not correctly aligned in the mobile view and it would be nice to have the buttons perfectly aligned to the center @akashgp09 Please fix that.

2020-10-25 12:59 UTC, akashgp09 commented
**We have the alignment issue with all the books images**

![image](https://user-images.githubusercontent.com/55311336/97107864-c4390c80-16ef-11eb-8d72-327c41999541.png)

**Can I open a different issue for it ?**

2020-10-25 13:08 UTC, kishore007k commented
> **We have the alignment issue with all the books images**
> 
> ![image](https://user-images.githubusercontent.com/55311336/97107864-c4390c80-16ef-11eb-8d72-327c41999541.png)
> 
> **Can I open a different issue for it ?**

@Nikhil-Ladha

2020-10-25 13:25 UTC, Nikhil-Ladha commented
I think it will require a common change since all the files use the same code structure. So, I think it can be resolved in this PR itself.

2020-10-26 06:56 UTC, akashgp09 commented
@Nikhil-Ladha @leecalcote 

![image](https://user-images.githubusercontent.com/55311336/97142243-4d028780-1786-11eb-8d89-dc3158384e1c.png)

2020-10-26 07:08 UTC, kishore007k submitted a review, later dismissed

2020-10-26 12:10 UTC, leecalcote commented
Good improvement, @akashgp09

2020-10-26 14:10 UTC, leecalcote commented on collections/_books/2020-10-24-the-enterprise-path-to-service-mesh-architectures-2nd-Edition.md
> +<i>Author: Lee Calcote, Publisher: O'Reilly, Publish Date: October 2020</i>
```suggestion
<i>Author: Lee Calcote, Publisher: O'Reilly, Publish Date: November 2020</i>
```

2020-10-26 20:56 UTC, leecalcote approved these changes
Thank you, @akashgp09. 👍 

Would you like to try adding this to the layer5ng site?

2020-10-26 20:56 UTC, merged

2020-10-27 08:12 UTC, akashgp09 commented
> Would you like to try adding this to the layer5ng site?

Yes definitely.