Profile Page member
layer5io/layer5 pull request #1170
Opened 2020-11-19 18:07 UTC by vinayaksh42

Signed-off-by: Vinayak Sharma <vinayaksh42@gmail.com>

**Description**
Profile page improvements

This PR fixes #1085 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2020-11-19 20:38 UTC, Tanuj22 reviewed
Looks good. Some minor changes. There is unnecessary margin both at the top and bottom in mobile view. Remove that

2020-11-19 20:38 UTC, Tanuj22 commented on src/sections/Member-single/index.js
>                                      <h4>skills: {skills}</h4>
```suggestion
                                    <h4>Skills: {skills}</h4>
```

2020-11-19 20:38 UTC, Tanuj22 commented on src/sections/Member-single/index.js
>                                      <h4>skills: {skills}</h4>
Also make `Skills` bold

2020-11-19 20:38 UTC, Tanuj22 commented on src/sections/Member-single/index.js
> +                                    <h4>{bio}</h4>
Can you avoid changing the font-weight of the header tags (also do other headers tags)? You can create a class and use that in a `div` or a `span`

2020-11-19 20:38 UTC, Tanuj22 commented on src/sections/Member-single/index.js
>                                      <h4>Location: {location}</h4>
Make `Location` bold

2020-11-20 12:59 UTC, Nikhil-Ladha commented
The design is definitely an improvement here :+1: 
One thing to change here is:
- On the full page, please remove the green color on the GitHub and other icons and keep them in grayscale and fill them on hover.

2020-11-20 13:02 UTC, Nikhil-Ladha commented
These look better:
![Screenshot from 2020-11-20 18-30-49](https://user-images.githubusercontent.com/29438875/99803000-b182ed80-2b5e-11eb-99c7-e573f64c8792.png)
![Screenshot from 2020-11-20 18-30-51](https://user-images.githubusercontent.com/29438875/99803016-b6e03800-2b5e-11eb-9fbd-6634e979cb3a.png)

2020-11-20 16:45 UTC, Tanuj22 commented on src/sections/Member-single/index.js
> +                                    <h4>{bio}</h4>
This is left

2020-11-21 15:12 UTC, akashgp09 reviewed
Looks better Now. Nice work @vinayaksh42

2020-11-21 17:19 UTC, Nikhil-Ladha requested changes
The green bg color on the hover is still there. Can you please remove that?

2020-11-22 05:10 UTC, Nikhil-Ladha approved these changes

2020-11-22 05:10 UTC, merged