add anirudh-jain profile to community w/ Yash Vardhan <yashvardhan513…
layer5io/layer5 pull request #1396
Opened 2021-01-22 08:31 UTC by Grumpyyash

…@gmail.com>

Signed-off-by: Yash vardhan <yashvardhan513@gmail.com>

Adding Anirudh-Jain profile to community section 

This PR fixes #1383 of adding the profile of Anirudh-Jain to the community
![issue-1383](https://user-images.githubusercontent.com/62200066/105466394-2dfa8f80-5cba-11eb-8e26-a1363ac6f89c.png)

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2021-01-22 09:50 UTC, Nikhil-Ladha commented on src/collections/members/anirudh-jain/index.mdx
> +badges:
Please follow the ordering of times as mentioned in the template (https://github.com/layer5io/layer5/blob/3f738b30b76e0d618910f279572157d5d82738d7/src/collections/members/_member-profile-template/index.mdx).

2021-01-22 09:51 UTC, Nikhil-Ladha commented
Also, @anirudhjain75 if you could share a small `bio` and `location` with @Grumpyyash on slack, he might update that as well in this PR.

2021-01-24 10:13 UTC, Nikhil-Ladha commented on src/collections/members/anirudh-jain/index.mdx
> +badges:
You don't need to add empty fields.

2021-01-24 10:14 UTC, Nikhil-Ladha commented on src/collections/members/anirudh-jain/index.mdx
> +maintainer: no
If it's a `no` it's not required.

2021-01-24 10:15 UTC, Nikhil-Ladha requested changes
Rebase your branch with the upstream/layer5-ng branch to fix the netlify build issue.

2021-01-24 10:54 UTC, Grumpyyash commented
I have done the required changes

2021-01-24 10:57 UTC, Nikhil-Ladha commented on src/collections/members/anirudh-jain/index.mdx
> +  - meshary
Ahh... last one I guess 😂....typo: meshary-> meshery

2021-01-24 11:08 UTC, Nikhil-Ladha approved these changes

2021-01-24 11:08 UTC, merged