Emperor yp7/color legend
layer5io/layer5 pull request #1435
Opened 2021-01-29 10:34 UTC by EmperorYP7

**Description**

This PR fixes #1071

**Notes for Reviewers**

- Used chroma-js for showing color legends
- Work in progress! 🚧 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

<img width="574" alt="Screenshot 2021-01-29 at 4 03 06 PM" src="https://user-images.githubusercontent.com/62606998/106264345-8b0ebc00-624b-11eb-87c0-912d88cb7f3a.png">

2021-01-29 11:31 UTC, Nikhil-Ladha commented
I wonder, isn't it possible to do it without using any library and only using CSS?

2021-01-29 11:37 UTC, EmperorYP7 commented
@Nikhil-Ladha I was thinking the same! But, I thought to give it a shot when I was react-select's docs.. 😓 Anyways, I'll do it with CSS now.

2021-02-02 13:32 UTC, leecalcote commented
Quick check... This is still in draft, right, @EmperorYP7?

2021-02-02 14:42 UTC, EmperorYP7 commented
@leecalcote Yep. Working on it.. 🔨

2021-02-03 13:34 UTC, Jashpatel1 requested changes
@EmperorYP7  The dropdown goes behind the member card and makes it inaccessible.

2021-02-04 14:34 UTC, EmperorYP7 commented on src/sections/Community/Members-grid/index.js
> +                  styles={colourStyles}
@Jashpatel1 Even if I pass `colourStyles = {}` to `styles` prop in the react-select component, its behaving that way. Not sure why.

2021-02-04 15:30 UTC, EmperorYP7 commented on src/sections/Community/Members-grid/index.js
> +                  styles={colourStyles}
Never mind. 😓 fixed it!

2021-02-04 15:32 UTC, EmperorYP7 commented
@Jashpatel1 I think now it is fixed.

2021-02-05 20:46 UTC, leecalcote commented
@EmperorYP7 good work so far. 👍 With a custom component comes a custom user experience. Reflecting on that for a moment, you might consider that a user would internalize the gray "Inactive Members" as a disabled option in the otherwise list of green-colored selections. You almost might find that users are confused when seeing a green circle next to Active Members AND next to All Members. A split-colored indicator using both green and gray might more accurately depict the fact that All Members is not filtered at all. In fact, not using a color indicator for this selection is best. Will you consider the following changes?

1. All selections in black text.
2. No status indicator for All Members.
3. Use of the "5" icon for the status indicator for Maintainers.
4. Use of the MeshMate icon for the status indicator for MeshMates.
5. Display of the status indicators in the dropdown list in addition to the status indicator shown after selection.

<img width="287" alt="Screen Shot 2021-02-05 at 2 40 26 PM" src="https://user-images.githubusercontent.com/7570704/107086822-21992b00-67c0-11eb-8909-3a3929e55e8a.png">

2021-02-05 20:46 UTC, leecalcote requested changes

2021-02-05 20:46 UTC, leecalcote commented on src/pages/community/members.js
> +  { label: "All Members", value: "all", color: "#0bb39f", isFixed: true},
It'd be great if we could use the properties from src/theme/app/themeStyles.js here.

2021-02-05 20:47 UTC, leecalcote commented
Marking with Post-go-live milestone.

2021-02-06 14:00 UTC, EmperorYP7 commented
@leecalcote On it! 🔨

2021-02-06 23:03 UTC, leecalcote commented
Pretty cool to see this coming along, @EmperorYP7. 👍

2021-02-07 11:50 UTC, EmperorYP7 commented
> Will you consider the following changes?
> 
> 1. All selections in black text.
> 2. No status indicator for All Members.
> 3. Use of the "5" icon for the status indicator for Maintainers.
> 4. Use of the MeshMate icon for the status indicator for MeshMates.
> 5. Display of the status indicators in the dropdown list in addition to the status indicator shown after selection.
> 6. Use green indicator for active members.
> 7. Use gray indicator for inactive members.

@leecalcote Done! 🙆🏻‍♂️

2021-02-07 11:57 UTC, EmperorYP7 reviewed
I think the quality of my patch can be a lot better. All suggestions are welcomed! :smile:

2021-02-07 11:57 UTC, EmperorYP7 commented on src/sections/Community/Members-grid/membersGrid.style.js
> +    alignItems: "center",
This is where I was sceptical about going against DRY. Any clever work-around for this?

2021-02-07 12:14 UTC, Jashpatel1 approved these changes
Looks good. For now, we can go ahead with this approach. Great work here. Thanks @EmperorYP7

2021-02-07 12:52 UTC, leecalcote approved these changes
Ditto. Good work. 😀

2021-02-07 12:53 UTC, merged