Added Soham Sonawane in members
layer5io/layer5 pull request #1690
Opened 2021-03-11 16:47 UTC by 96RadhikaJadhav

**Description**

This PR fixes #1687 .

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-03-11 17:44 UTC, Tanuj22 requested changes

2021-03-11 17:44 UTC, Tanuj22 commented on src/collections/members/soham-sonawane/index.mdx
> +github: @killbotXD
```suggestion
github: killbotXD
```

2021-03-11 17:44 UTC, Tanuj22 commented on src/collections/members/soham-sonawane/index.mdx
> +twitter: @killbot_XD
```suggestion
twitter: killbot_XD
```

2021-03-11 17:44 UTC, Tanuj22 commented on src/collections/members/soham-sonawane/index.mdx
> +
Remove these empty lines

2021-03-11 19:21 UTC, 96RadhikaJadhav commented on src/collections/members/soham-sonawane/index.mdx
> +
@Tanuj22  Done.

2021-03-11 19:30 UTC, l5io commented
🚀 Preview for commit ee98f3ea59736d32cfa64403bd196245bf0116cd at: https://604a6f5c2a42ad23c817d322--layer5ng.netlify.app

2021-03-11 20:01 UTC, l5io commented
🚀 Preview for commit 36a6e5b490f3c317f265ebe338ff8072f209db3d at: https://604a76b153d5d7275c35b8ae--layer5ng.netlify.app

2021-03-12 04:42 UTC, killbotXD commented on src/collections/members/soham-sonawane/index.mdx
> +     debug 99.9% of the bugs out there.
this newline wont cause an Issue right?

2021-03-12 04:43 UTC, Tanuj22 commented on src/collections/members/soham-sonawane/index.mdx
> +     debug 99.9% of the bugs out there.
Nope

2021-03-12 04:44 UTC, killbotXD commented on src/collections/members/soham-sonawane/index.mdx
> +     debug 99.9% of the bugs out there.
cool lgtm

2021-03-12 04:45 UTC, killbotXD approved these changes

2021-03-12 04:45 UTC, Tanuj22 approved these changes
Thank you @96RadhikaJadhav :)

2021-03-12 04:45 UTC, merged

2021-03-12 05:23 UTC, leecalcote commented
Yes, thank you, @96RadhikaJadhav! 😎

@killbotXD 🥳

2021-03-12 09:36 UTC, killbotXD commented
thank you @96RadhikaJadhav  :) thanks @leecalcote  @dhruv0000 @Tanuj22 @everyone