Member Profile for  Stephen Miller
layer5io/layer5 pull request #1783
Opened 2021-04-14 06:22 UTC by Anita-ihuman

Signed-off-by: Anita-ihuman <charlesanita403@gmail.com>

**Description**
Added Member Profile for  Stephen Miller

This PR fixes #1776

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

2021-04-14 11:47 UTC, Tanuj22 requested changes

2021-04-14 11:47 UTC, Tanuj22 commented on src/collections/members/stephen-miller /index.mdx
> +---
There is a leading white space in the folder name. Remove that

2021-04-14 11:47 UTC, Tanuj22 commented on src/collections/members/stephen-miller /index.mdx
> +github: Stephen Miller
```suggestion
github: smille02a
```

2021-04-14 11:47 UTC, Tanuj22 commented on src/collections/members/stephen-miller /index.mdx
> +titHub: @smille02a
Remove

2021-04-14 11:47 UTC, Tanuj22 commented on src/collections/members/stephen-miller /index.mdx
> +twitter: @smille02
```suggestion
twitter: smille02
```

2021-04-14 11:47 UTC, Tanuj22 commented on src/collections/members/stephen-miller /index.mdx
> +location: Sure, Manhattan, NYC, NY, US
```suggestion
location: NYC, NY, USA
```

2021-04-14 19:19 UTC, Tanuj22 commented on src/collections/members/stephen-miller/index.mdx
> +linkedIn: Stephen Miller
```suggestion
linkedIn: swmps
```

2021-04-14 19:19 UTC, Tanuj22 commented
@Anita-ihuman the DCO is failing

2021-04-14 19:27 UTC, leecalcote commented
@Anita-ihuman that's an issue with GitHub. I've flagged this DCO to pass for the current commits.

2021-04-15 17:34 UTC, l5io commented
🚀 Preview for commit b6b69f4fb936c13b9e0c77bdcbb73e03ab3d7e6b at: https://607878c6a8875e793dc57e15--layer5ng.netlify.app

2021-04-15 17:35 UTC, Tanuj22 commented
@Anita-ihuman I ended up fixing the build error

2021-04-18 10:38 UTC, Tanuj22 approved these changes

2021-04-18 10:38 UTC, merged