Added `Back to Programs`  button
layer5io/layer5 pull request #1868
Opened 2021-05-18 20:08 UTC by amino19

_Signed Off : Anshumaan_ anshumaankrprasad76@gmail.com

**Description**
Added ` <-- Back button` to Program page. 

This PR fixes #1859 

**Notes for Reviewers**
Not sure about work completed, pl give me more time to view on this issue.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2021-05-19 21:42 UTC, Tanuj22 requested changes
Thank you for this @amino19. Were you able to build to run the site locally? I ask because the build seems to fail (should be fixed after the changes are done)

2021-05-19 21:42 UTC, Tanuj22 commented on src/collections/programs/Programs.style.js
> +    margin: 4.5rem 0 3.125rem 0;
This css should be in `ProgramsSingle.style.js` file

2021-05-19 21:42 UTC, Tanuj22 commented on src/sections/Careers/Careers-Programs-single/index.js
> +          <Row>
To use `Row` and `Link` you need to import them first.

2021-05-19 21:42 UTC, Tanuj22 commented on src/sections/Careers/Careers-Programs-single/index.js
> +                <Link to="careers/programs">
the link should be `/careers/programs/`

2021-05-20 12:47 UTC, Tanuj22 requested changes

2021-05-20 12:47 UTC, Tanuj22 commented on src/sections/Careers/Careers-Programs-single/index.js
>  import { Container } from "../../../reusecore/Layout";
Why are you importing this again? Remove this

2021-05-20 12:47 UTC, Tanuj22 commented on src/collections/programs/ProgramsSingle.style.js
>  import styled from "styled-components";
Do not rename this file. No changes are needed in this file. The CSS needs to be added in this file https://github.com/layer5io/layer5/blob/master/src/sections/Careers/Careers-Programs-single/ProgramsSingle.style.js

2021-05-20 23:21 UTC, Tanuj22 requested changes
@amino19 Try to run the site locally first ([instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)), and then make the changes. Then check out the changes locally in your web browser. Otherwise there may be issues each time

2021-05-20 23:21 UTC, Tanuj22 commented on src/sections/Careers/Careers-Programs-single/index.js
>  import { Container } from "../../../reusecore/Layout";
Add `Row` directly here

2021-05-20 23:21 UTC, Tanuj22 commented on src/collections/programs/Programs.style.js
> +    margin: 4.5rem 0 3.125rem 0;
This css is no longer needed

2021-05-20 23:21 UTC, Tanuj22 commented on src/sections/Careers/Careers-Programs-single/ProgramsSingle.style.js
> +margin: 4.5rem 0 3.125rem 0;
The margin is probably going be messed up due to this. You need to also account for the previous `margin-bottom: 30px;`

2021-05-22 08:23 UTC, l5io commented
🚀 Preview for commit 2841b930b119ccedaba1a0dfba93ec0ba1a48b17 at: https://60a8bf508eed10c0e4d552b2--layer5ng.netlify.app

2021-05-22 09:13 UTC, Tanuj22 requested changes
Almost done

2021-05-22 09:13 UTC, Tanuj22 commented on src/sections/Careers/Careers-Programs-single/ProgramsSingle.style.js
> +margin: 4.5rem 0 3.125rem 0;
Change to `margin-bottom : 3,125rem`

2021-05-22 09:13 UTC, Tanuj22 commented on src/sections/Careers/Careers-Programs-single/ProgramsSingle.style.js
> +    margin-bottom: 1rem;
Remove `margin-bottom: 1rem;` and add 
```
position: absolute;
top: 9.30rem;
z-index: 2
```

2021-05-22 09:13 UTC, Tanuj22 commented on src/sections/Careers/Careers-Programs-single/index.js
> +import { Row } from "../../../reusecore/Layout";
Just make this - 
```
import { Row, Container } from "../../../reusecore/Layout";
```

and then remove -
```
import { Container } from "../../../reusecore/Layout";
```

2021-05-22 09:55 UTC, l5io commented
🚀 Preview for commit 41860935c947ca633a35b785d3becad653280cca at: https://60a8d4abf0e37cf37d10c8ce--layer5ng.netlify.app

2021-05-22 10:07 UTC, Tanuj22 approved these changes
Thank you @amino19

2021-05-22 10:07 UTC, merged