[Learn] Learning path page sidebar component
layer5io/layer5 pull request #2008
Opened 2021-07-19 17:13 UTC by sudo-NithishKarthik

feat: Add sidebar component for learning path page

**Description**
Implements the sidebar component for learning path page

This PR fixes #1984 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-07-19 17:15 UTC, sudo-NithishKarthik commented
https://user-images.githubusercontent.com/75248557/126200071-e03f278b-d058-4c31-8824-0f49e3acf87d.mov

2021-07-19 17:30 UTC, l5io commented
🚀 Preview for commit 37b408d851db0cff8361cbd222891d061be55989 at: https://60f5b665f4d13b992c77f2c0--layer5ng.netlify.app

2021-07-19 17:34 UTC, leecalcote commented
ooooh, nice.

2021-07-19 17:43 UTC, l5io commented
🚀 Preview for commit 56b7ecf6a0ac649bfda89ac3c73fcdb86d62a7ab at: https://60f5b96ac0d5dd5f87aa677e--layer5ng.netlify.app

2021-07-20 10:08 UTC, Nikhil-Ladha requested changes
Also, the other change wrt to design I have communicated to you on slack, do check that.

2021-07-20 10:08 UTC, Nikhil-Ladha commented on src/components/Learn-Components/TOC-Learning-Path/index.js
> +          {[{name: "Set up", link: "/service-mesh-management/meshery"},{name:"Run Meshery",link:"/service-mesh-management/meshery/getting-started"},{name: "Manage Meshery", link: "/service-mesh-manag
These links should be a href to the sections within the page, and not point to the actual page.
Also, better to have these in a variable above and then use that variable here.

2021-07-20 10:08 UTC, Nikhil-Ladha commented on src/components/Learn-Components/TOC-Learning-Path/index.js
> +                <a href={`/${item.fields.slug}`}>
Same as above

2021-07-24 12:01 UTC, Nikhil-Ladha commented
Hey @sudo-NithishKarthik any updates here?

2021-07-24 12:16 UTC, sudo-NithishKarthik commented
Almost done, will push it soon 👍🏽

2021-07-25 07:25 UTC, sudo-NithishKarthik commented
<img width="1433" alt="Screenshot 2021-07-25 at 12 55 06 PM" src="https://user-images.githubusercontent.com/75248557/126891221-99685593-745b-465b-aa68-8348ee7bcc6d.png">

2021-07-25 07:35 UTC, l5io commented
🚀 Preview for commit 12faf29fa5f8a43492afb71d3b9eb3ff7e938b41 at: https://60fd13d7e0e9a44a2582f1a7--layer5ng.netlify.app

2021-07-25 10:45 UTC, Nikhil-Ladha commented
Looks perfect!
Just 1 small change, a bit unrelated though. Can you also change the `Go Back`Button to a `< Learning Paths` Button, as we have on this [page](https://60fd13d7e0e9a44a2582f1a7--layer5ng.netlify.app/learn-ng/mastering-meshery-istio/introduction-to-service-meshes/istio/getting-started). Also, make the sidebar and the right section aligned at the same level.

2021-07-25 14:21 UTC, sudo-NithishKarthik commented
Yes @Nikhil-Ladha , sure, i was thinking of that as well 😄

2021-07-25 14:43 UTC, leecalcote approved these changes

2021-07-26 05:16 UTC, sudo-NithishKarthik commented
<img width="1439" alt="Screenshot 2021-07-26 at 10 45 41 AM" src="https://user-images.githubusercontent.com/75248557/126936641-9f37a47d-f65f-4c06-921c-ca71978b51b5.png">

2021-07-26 05:24 UTC, l5io commented
🚀 Preview for commit ae8ef4a11cb3b48892af0dc0cea011428ed07cb6 at: https://60fe46ba571f06af9f99622e--layer5ng.netlify.app

2021-07-26 05:41 UTC, Nikhil-Ladha commented
Sorry for not mentioning it earlier, but 2 more small change is required that being:
The Headings of the section should also be hyperlinked i.e, `Couses` and `Pre-requisites`, and also change `Get Started` to `Pre-requisites`.
And, other thing is `Go Back` can be renamed as `Learning Paths`.

2021-07-26 11:43 UTC, sudo-NithishKarthik commented
<img width="1440" alt="Screenshot 2021-07-26 at 5 12 49 PM" src="https://user-images.githubusercontent.com/75248557/126983306-42672c3f-fea6-4b4d-aa19-af4e7d541824.png">

2021-07-26 11:53 UTC, l5io commented
🚀 Preview for commit 4f016c380a505d406acf781ba4a235ce93867ee3 at: https://60fea1c84106972044fb5520--layer5ng.netlify.app

2021-07-26 13:08 UTC, Nikhil-Ladha approved these changes

2021-07-26 13:08 UTC, merged