updated member profile for maintainers
layer5io/layer5 pull request #2013
Opened 2021-07-21 11:50 UTC by Anita-ihuman

Signed-off-by: Anita-ihuman <charlesanita403@gmail.com>

**Description**
I updated the member profiles of Anita Ihuman, Dhruv Patel and Vinayak Sharma .
This PR fixes # an enhancement.

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-07-21 11:59 UTC, l5io commented
🚀 Preview for commit d50bc0aee8a63e776aeee10a5ba611fd20cafe17 at: https://60f80bdf1c112b10d3ca1024--layer5ng.netlify.app

2021-07-21 14:29 UTC, Jashpatel1 approved these changes
Thanks @Anita-ihuman . Congratulations @dhruv0000 @vinayaksh42

2021-07-21 14:31 UTC, Jashpatel1 commented
@Anita-ihuman I guess you will have to add maintainer: yes. Sorry for giving wrong info previously.

2021-07-21 14:53 UTC, l5io commented
🚀 Preview for commit 81a33c87bef17866b5ce3bd730a988736b469589 at: https://60f8348a4fe5e01746f8e4f6--layer5ng.netlify.app

2021-07-22 11:24 UTC, Tanuj22 requested changes

2021-07-22 11:24 UTC, Tanuj22 commented on src/collections/members/dhruv-patel/index.mdx
> +position: maintainer
Just a small nit. Can you change capitalize 'm'

2021-07-22 11:24 UTC, Tanuj22 commented on src/collections/members/vinayak-sharma/index.mdx
> +position: maintainer
same

2021-07-23 15:57 UTC, Tanuj22 approved these changes
Thank you @Anita-ihuman

2021-07-23 15:57 UTC, merged