third chapter- advance concepts of mershery
layer5io/layer5 pull request #2032
Opened 2021-07-27 07:10 UTC by The-Loony-Coder

Signed-off-by: Mritunjay <msengar121@gmail.com>

**Third chapter- advance course**

This PR fixes #1987

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2021-07-27 07:21 UTC, l5io commented
🚀 Preview for commit 88ef36c2467444dd633ffea00aa7755090aca7bc at: https://60ffb3af5288d592ab1febf8--layer5ng.netlify.app

2021-07-27 17:45 UTC, Nikhil-Ladha commented
Update the commit-msg to use `Updates` instead of `Fixes`

2021-07-27 17:52 UTC, Nikhil-Ladha requested changes

2021-07-27 17:52 UTC, Nikhil-Ladha commented on content-learn/mastering-meshery-istio/advance-concepts-of-service-mesh/index.mdx
> +    'deploy-an-application',
This chapter is not a part of this PR, please remove it.

2021-07-27 17:52 UTC, Nikhil-Ladha commented on content-learn/mastering-meshery-istio/advance-concepts-of-service-mesh/istio/deploy-an-application.mdx
> +---
Same as above

2021-07-27 17:52 UTC, Nikhil-Ladha commented on content-learn/mastering-meshery-istio/advance-concepts-of-service-mesh/istio/expose-services.mdx
> +Modify you local `/etc/hosts` file to add an entry for your sample application.
nit: `you` -> `your`

2021-08-06 08:18 UTC, l5io commented
🚀 Preview for commit 1e7f9c3490f3fc5a8cdb9c8889ea2db924f3631f at: https://610cf029fdc6d37cf1d40a52--layer5ng.netlify.app

2021-08-06 08:54 UTC, l5io commented
🚀 Preview for commit 619311743e7cf053483836869f6427deb4fc6f28 at: https://610cf86f2175638d3e6a014f--layer5ng.netlify.app

2021-08-06 10:23 UTC, Nikhil-Ladha approved these changes

2021-08-06 10:23 UTC, merged