Fixed sidebar in learn-ng
layer5io/layer5 pull request #2039
Opened 2021-07-28 14:15 UTC by chinmaym07

Signed-off-by: chinmaym07 <b418020@iiit-bh.ac.in>

**Description**

This PR fixes #

**Notes for Reviewers**
Made Sidebar Sticky for Chapter page & Slightly modified the styles of toc.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

Issue Fixed :

https://user-images.githubusercontent.com/44670961/127337679-b8e2333e-6cee-467c-90dd-373ffbc666ad.mp4

2021-07-28 14:24 UTC, l5io commented
🚀 Preview for commit c20c5ba750211c3c57edfbdaf2817ee3f829e736 at: https://610168398cb185118ff041f8--layer5ng.netlify.app

2021-07-28 14:27 UTC, sudo-NithishKarthik requested changes
<img width="504" alt="Screenshot 2021-07-28 at 7 56 12 PM" src="https://user-images.githubusercontent.com/75248557/127339892-99aabbf8-cd26-42f0-98e8-83924da5ce0d.png">

That's looking great 🎉 
Can you look at this responsiveness issue ?

2021-07-28 15:12 UTC, l5io commented
🚀 Preview for commit f6874432e3ecc9b36773bf4da3fe1ecedef771c3 at: https://6101738d342f2420da88ac18--layer5ng.netlify.app

2021-07-29 16:12 UTC, l5io commented
🚀 Preview for commit 0a2b4b4d89af5ce4b559d4d79218b04e19388f4d at: https://6102d2ffc325973b770ba004--layer5ng.netlify.app

2021-07-29 17:11 UTC, Nikhil-Ladha commented on src/sections/Learn-Layer5/Course-Overview/index.js
> +                to={`/learn-ng/${course.fields.learnpath}/${course.fields.course}/istio/${item}/`}
A relative path will work. Why change to use the absolute path?

2021-07-29 17:12 UTC, Nikhil-Ladha requested changes
The line connecting the dots on the sidebar is not properly aligned. Please fix that.

2021-07-29 20:27 UTC, l5io commented
🚀 Preview for commit ffc006a5f0b51fef60e4197da616b429e4e53d2f at: https://61030edd4a903a866ef032fc--layer5ng.netlify.app

2021-07-30 09:44 UTC, l5io commented
🚀 Preview for commit 07ae502926e24d76827e84df4a706d45b15a5069 at: https://6103c99feb9ff5f71760b4ae--layer5ng.netlify.app

2021-07-30 10:05 UTC, Nikhil-Ladha requested changes
A good fix for the `active link` issue. `useEffect` is the exact solution we needed.
Though a small change is left i.e, the line connecting the dots is still not aligned properly.

2021-07-30 10:05 UTC, Nikhil-Ladha commented on src/components/Learn-Components/TOC-Chapters/index.js
> +
nit: extra space

2021-07-30 14:15 UTC, l5io commented
🚀 Preview for commit 4e3ac7d1cbee436113bbefc492370af22afede47 at: https://6104090d2dce196b5c0f4e30--layer5ng.netlify.app

2021-08-01 16:24 UTC, Nikhil-Ladha approved these changes

2021-08-01 16:33 UTC, l5io commented
🚀 Preview for commit 45375732189aa7a1804394c03ca32fa64ed6a22f at: https://6106cc87ade53d7fcb3d6b49--layer5ng.netlify.app

2021-08-02 12:44 UTC, leecalcote commented
FYI
<img width="1930" alt="Screen Shot 2021-08-02 at 7 39 38 AM" src="https://user-images.githubusercontent.com/7570704/127863673-158d0c6c-0bea-4a09-ac40-b5f5f6b6895c.png">

2021-08-02 12:44 UTC, sudo-NithishKarthik requested changes
<img width="335" alt="Screenshot 2021-08-02 at 6 12 24 PM" src="https://user-images.githubusercontent.com/75248557/127863740-17b4681c-4b1f-461b-b34b-48f600827d99.png">

Can you also look at this line and dot alignment issue @chinmaym07 ?

2021-08-02 16:51 UTC, l5io commented
🚀 Preview for commit a4c7774be298410c7f61b34646a135c7cd46e6f7 at: https://6108223fc714dafebce6f872--layer5ng.netlify.app

2021-08-03 05:05 UTC, sudo-NithishKarthik commented
<img width="323" alt="Screenshot 2021-08-03 at 10 34 43 AM" src="https://user-images.githubusercontent.com/75248557/127960720-53b8598f-350a-4ec2-9e62-e7c0cfab0e5d.png">

It is still not passing through the center, or, is it just in my laptop ? 😕

2021-08-03 05:13 UTC, chinmaym07 commented
I am not sure .. please tell me your resolution at which this issue occurs ?

![image](https://user-images.githubusercontent.com/44670961/127961376-ba644441-6986-4535-83a9-206985850525.png)

2021-08-03 05:15 UTC, sudo-NithishKarthik commented
> I am not sure .. please tell me your resolution at which this issue occurs ?
> 
> ![image](https://user-images.githubusercontent.com/44670961/127961376-ba644441-6986-4535-83a9-206985850525.png)

oh, that's weird. My screen resolution is 
**1440 x 900**

2021-08-03 05:18 UTC, chinmaym07 commented
Strange again 😀 

![image](https://user-images.githubusercontent.com/44670961/127961722-ee30cc33-3457-41f8-be05-27cfda8b74dd.png)

2021-08-03 05:21 UTC, sudo-NithishKarthik commented
what browser are you using ?

2021-08-03 05:21 UTC, chinmaym07 commented
firefox

2021-08-03 05:23 UTC, sudo-NithishKarthik commented
Ig its a browser specific issue, it's neither working with brave nor safari 😕 
can you check with these if possible ?

2021-08-03 05:33 UTC, Nikhil-Ladha commented
It is a browser-specific issue for sure. It works fine for me in Firefox but is not aligned in brave and chrome.

2021-08-03 05:33 UTC, warunicorn19 commented
Also, @chinmaym07 there seems to be a merge conflict, if you could look into that.

2021-08-03 07:50 UTC, l5io commented
🚀 Preview for commit f61387ef45f06437ee19b3c63bbac7772b5c5f56 at: https://6108f50616b098e1c26f75d4--layer5ng.netlify.app

2021-08-05 17:19 UTC, leecalcote commented
Merge conflict fixed.

2021-08-09 12:48 UTC, l5io commented
🚀 Preview for commit 1fb723cb908e95734460d6569b23d921eb1083a9 at: https://611123db842ddbc37b5fc589--layer5ng.netlify.app

2021-08-09 12:53 UTC, sudo-NithishKarthik requested changes
The issues are fixed now 🎉 
Thank you @chinmaym07 
As much as i wan't to get this pr merged, there is just one small thing to be done 😄 , the service mesh switcher is not moving along with the toc, can you also make it sticky ?

2021-08-09 13:18 UTC, Nikhil-Ladha commented
Tip: For the service mesh switcher to move along, move both the divs under a single div and make that div sticky, then it will work perfectly.

2021-08-09 15:12 UTC, chinmaym07 commented
I always mess up while solving conflicts .. sorry will open a new PR 😢

2021-08-09 15:12 UTC, closed without merging