added code snippets
layer5io/layer5 pull request #2144
Opened 2021-08-30 19:20 UTC by debo19

Signed-off-by: Debopriya Bhattacharjee <debopriyabh1908@gmail.com>

**Description**
Added code snippets to [Contribution](https://layer5.io/community/handbook/contribution) page of handbook.

This PR fixes #2137 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2021-08-30 19:26 UTC, warunicorn19 requested changes

2021-08-30 19:26 UTC, warunicorn19 commented on src/sections/Community/Handbook/contributing.js
> +              <Code codeString="git add file.md " /></span></li>
```suggestion
              <Code codeString="git add <file> " /></span></li>
```

2021-08-30 19:31 UTC, l5io commented
🚀 Preview for commit bafda05b879ff9e7e5861ad937bc6b2baf13d932 at: https://612d31c2f74987228e7dd08f--layer5ng.netlify.app

2021-08-30 19:41 UTC, warunicorn19 requested changes
@debo19  could you please reduce the size of the box and reduce the distance between the text and the code snippet just a little

<img width="1440" alt="Screenshot 2021-08-31 at 1 07 49 AM" src="https://user-images.githubusercontent.com/53532328/131395504-8d2a65ab-dfa9-46c6-bf90-20db4eef2b8e.png">

2021-08-30 20:20 UTC, warunicorn19 commented
@leecalcote could you please re-run the build, i can't seem to find the option to, netlify didn't seem to work.

2021-08-30 20:21 UTC, leecalcote commented
Hmm. Hmm.

2021-08-30 20:35 UTC, warunicorn19 commented
@debo19 @leecalcote maybe we could try adding a dummy commit to this PR and let's see if it goes off. Seemed to be working fine 2mins ago.

2021-08-31 02:33 UTC, leecalcote commented on src/sections/Community/Handbook/Handbook.style.js
> +
```suggestion
```

Adding a simple commit to kick the build process....

2021-08-31 02:44 UTC, l5io commented
🚀 Preview for commit 8e698212fa28ca38b54e896847c3ecabd2fcc0e0 at: https://612d970f18078f45556f8684--layer5ng.netlify.app

2021-08-31 08:29 UTC, warunicorn19 approved these changes
LGTM🎉, thanks @debo19

2021-08-31 12:53 UTC, leecalcote approved these changes
Looks great.

2021-09-01 21:59 UTC, Tanuj22 approved these changes

2021-09-01 21:59 UTC, merged