repository_overview_page
layer5io/layer5 pull request #2147
Opened 2021-09-01 17:16 UTC by debo19

Signed-off-by: Debopriya Bhattacharjee <debopriyabh1908@gmail.com>

**Description**
1) Added table to display relevant information about all repositories.
2) Corrected links on the page.
This PR fixes #2139 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2021-09-01 17:26 UTC, l5io commented
🚀 Preview for commit 7995e566891363f5d4854cdca309851f2d9b9680 at: https://612fb772defdc00946e5d89d--layer5ng.netlify.app

2021-09-01 17:37 UTC, warunicorn19 requested changes
![Screenshot_20210901-230603](https://user-images.githubusercontent.com/53532328/131717692-53eb650f-fd14-4a8d-a648-65413a29bec9.jpg)

Some mobile responsive issues.

But good stuff @debo19.

2021-09-01 18:12 UTC, leecalcote commented
Nice. I wonder if we can make some of the redundancy of things like "Repository" less mundane.  Instead of the word "repository", perhaps GitHub logo with a link. Some of these rows will have links to their sites and some won't. Perhaps, some of the rows can have links to specific contributing instructions (e.g. https://docs.meshery.io/project/contributing-ui). 

Is the current hyperlink color Keppel green (darker), not Caribbean green (lighter)? Let's try to maximize the contrast between the link and the background color where we can.

2021-09-01 19:31 UTC, debo19 commented
![sites](https://user-images.githubusercontent.com/85789734/131731962-c4c0152e-1444-40b3-ad51-6ea712a8a374.jpg)

@leecalcote  Instead of adding links can we do something like this?

2021-09-01 20:07 UTC, Anita-ihuman commented
@debo19 this look better and clean too.

2021-09-01 22:04 UTC, leecalcote commented
Ooooh, very nice!

2021-09-01 22:04 UTC, leecalcote approved these changes

2021-09-01 22:21 UTC, Tanuj22 requested changes
@debo19 Nice work. Let me know if you need any clarification here

2021-09-01 22:21 UTC, Tanuj22 commented on src/sections/Community/Handbook/Handbook.style.js
> +     border: 1px solid #dddddd;
Any color that can be used from the theme instead of this? (It's fine if you don't find any)

2021-09-01 22:21 UTC, Tanuj22 commented on src/sections/Community/Handbook/repository.js
> +  let frontend =  data.filter((data) => data.category === "Frontend");
This is creating unnecessary computation. You can clean up the code. Create an array like - 

```
repo_data = [  
  {
    category: "Frontend",
    data: [
    {
    project: "Layer5",
    site: "https://layer5.io/", 
    language: "Gatsby and Strapi", 
    repository:  "https://github.com/layer5io/layer5" , 
    },
    {
    site: "https://meshery.io", 
    language: "Jekyll", 
    repository:  "https://github.com/meshery/meshery" , 
    },
   ]
  },
  {
    category: "Installation Dedicated Repos",
    data: [......]
  },
]
```

2021-09-01 22:21 UTC, Tanuj22 commented on src/sections/Community/Handbook/repository.js
> +        {frontend.map((frontend) => {
After the above step. All the loops can then be combined

2021-09-02 03:48 UTC, warunicorn19 commented
Head's up: merge conflict

2021-09-02 05:59 UTC, l5io commented
🚀 Preview for commit 963a01ebe53a037361fff7d836c5c252b96a4863 at: https://613067d734f27559bb251bfb--layer5ng.netlify.app

2021-09-02 15:34 UTC, l5io commented
🚀 Preview for commit cc2498075e6a2fc854efced167647da9b079f38e at: https://6130ee7519328bea6c829586--layer5ng.netlify.app

2021-09-02 15:49 UTC, debo19 commented
@Tanuj22 I could reduce it to two loops, one for frontend and one for all the backend categories, is that alright?

2021-09-02 16:58 UTC, Tanuj22 requested changes
@debo19 just some minor changes and we are good to go

2021-09-02 16:58 UTC, Tanuj22 commented on src/sections/Community/Handbook/repo-data.js
> +    image: "five",
Just import the image in this file and use that here.

2021-09-02 16:58 UTC, Tanuj22 commented on src/sections/Community/Handbook/repository.js
> +             {frontend.map((frontend) => {
Can you use a better name. `frontendProjects.map(frontendProject)`

2021-09-02 16:58 UTC, Tanuj22 commented on src/sections/Community/Handbook/repository.js
> +          <table className="frontendTable">
A `key` field is missing?

2021-09-02 16:58 UTC, Tanuj22 commented on src/sections/Community/Handbook/repository.js
> +                 let url = (image === "meshery")? meshery :
This is can remove than after the change I suggested in the data file

2021-09-02 16:58 UTC, Tanuj22 commented on src/sections/Community/Handbook/repository.js
> +                      <tr>
`key` missing?

2021-09-02 16:58 UTC, Tanuj22 commented on src/sections/Community/Handbook/repository.js
> +                         <td><a href={site}><img className="site-icon" src={url} /></a></td>
Add `_blank`

2021-09-02 16:58 UTC, Tanuj22 commented on src/sections/Community/Handbook/repository.js
> +                         <td><a href={repository}><img class="github-icon" src={github} /></a></td>
Add `_blank`

2021-09-02 16:58 UTC, Tanuj22 commented on src/sections/Community/Handbook/repository.js
> +          {backend.map((backend) => {
Similar comments like frontend

2021-09-02 16:58 UTC, Tanuj22 commented on src/sections/Community/Handbook/repository.js
> +          {frontend.subdata.map((subdata) => {
Can you fix indentation of this file a bit

2021-09-02 16:58 UTC, Tanuj22 commented on src/sections/Community/Handbook/Handbook.style.js
> +     margin: 20px 0 30px 0;
Use `rem`

2021-09-02 16:58 UTC, Tanuj22 commented on src/sections/Community/Handbook/Handbook.style.js
> +       height: 27px;
Use rem

2021-09-02 16:58 UTC, Tanuj22 commented on src/sections/Community/Handbook/Handbook.style.js
> +       height: 25px;
Use rem

2021-09-02 19:05 UTC, l5io commented
🚀 Preview for commit 88903c30ce63eec0ea9087f8bb296bbd9aea0f14 at: https://61311ff41bfb0100e5dca249--layer5ng.netlify.app

2021-09-02 21:11 UTC, Tanuj22 approved these changes
Thank you @debo19

2021-09-02 21:12 UTC, merged