profile is not visible
layer5io/layer5 pull request #2176
Opened 2021-09-11 18:06 UTC by PuneetDabral

Signed-off-by: Puneet Dabral <puneetdabral2000@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2021-09-11 18:08 UTC, PuneetDabral commented
sir please check and merge it so i  can Calibrate my contribution ......also feel motivated ....!!

2021-09-12 12:42 UTC, warunicorn19 requested changes
I dont think this would work, have you tested out the changes locally? you'd probably have to do `maintainer: yes`. Refer to the community member profile template: https://github.com/layer5io/layer5/blob/master/src/collections/members/_member-profile-template/index.mdx

2021-09-12 12:48 UTC, l5io commented
🚀 Preview for commit 6d190e464e82aa1c2cc4f2fa28b6982169626143 at: https://613df6d1e920e028ec8449d7--layer5ng.netlify.app

2021-09-12 12:48 UTC, PuneetDabral commented
can you please help me sir .. what i cna do

2021-09-13 12:49 UTC, warunicorn19 commented on src/collections/members/rudraksh-pareek/index.mdx
> +
```suggestion
  -smp
```

2021-09-13 12:50 UTC, PuneetDabral commented
@warunicorn19 sir please check and merge it ...issue is solved

2021-09-13 12:52 UTC, warunicorn19 commented
Yes @PuneetDabral almost there, you seem to have removed the `-smp` by mistake if you could add that and then commit again, and this time remember to sign-off like you did the first time. Good work.

2021-09-13 16:10 UTC, PuneetDabral commented
@warunicorn19 now it is ok sir ...check it and merge it

2021-09-13 16:14 UTC, debo19 approved these changes
@PuneetDabral code looks fine now, just sign off your commits for it to be merged. Follow these steps https://github.com/layer5io/layer5/pull/2176/checks?check_run_id=3589333190 and we'll be good to go.

2021-09-13 16:15 UTC, PuneetDabral commented
now sir....

2021-09-13 16:24 UTC, Tanuj22 approved these changes
Thank you @PuneetDabral

2021-09-13 16:25 UTC, merged

2021-09-13 16:28 UTC, PuneetDabral commented
sir how my name and image shows in Contributor List of this  website

2021-09-13 16:41 UTC, leecalcote commented
@PuneetDabral you didn't list the Issue # that this PR addresses in the Issue Description.

2021-09-13 16:41 UTC, leecalcote commented
> sir how my name and image shows in Contributor List of this website

Eventually, here - https://github.com/layer5io/layer5/graphs/contributors