[Blog] Publish the Learning path blogpost
layer5io/layer5 pull request #2349
Opened 2021-11-14 19:55 UTC by Anita-ihuman

**Description**
Created a blog post for the Layer5 learning path
This PR fixes #2323

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-11-14 20:07 UTC, Mr-DG-Wick commented on src/collections/blog/2021-11-15-layer5-learning-path /index.mdx
> +<p/>
```suggestion
</p>
```

2021-11-14 20:10 UTC, Mr-DG-Wick commented on src/collections/blog/2021-11-15-layer5-learning-path /index.mdx
> +  use <a href="https://meshery.io/">Meshery</a> as the management plane to manage the service meshes. It comprises a hands-on tutorial on <a href="https://layer5.io/learn/learning-paths/mastering-ser
```suggestion
  use <a href="https://meshery.io/">Meshery</a> as the management plane to manage the service meshes. It comprises a hands-on tutorial on <a href="https://layer5.io/learn/learning-paths/mastering-service-meshes-for-developers/introduction-to-service-meshes">introduction to Service Meshes</a> and an <a href="https://layer5.io/learn/learning-paths/mastering-service-meshes-for-developers/advance-concepts-of-service-mesh"> introduction to the advanced concepts of Service Meshes</a>. Within each course, you will find
```

2021-11-14 20:10 UTC, Mr-DG-Wick commented on src/collections/blog/2021-11-15-layer5-learning-path /index.mdx
> +  use <a href="https://meshery.io/">Meshery</a> as the management plane to manage the service meshes. It comprises a hands-on tutorial on <a href="https://layer5.io/learn/learning-paths/mastering-ser
```suggestion
  use <a href="https://meshery.io/">Meshery</a> as the management plane to manage the service meshes. It comprises a hands-on tutorial on <a href="https://layer5.io/learn/learning-paths/mastering-service-meshes-for-developers/introduction-to-service-meshes">introduction to Service Meshes</a> and an <a href="https://layer5.io/learn/learning-paths/mastering-service-meshes-for-developers/advance-concepts-of-service-mesh"> introduction to the advanced concepts of Service Meshes</a>. Within each course, you will find
```

2021-11-14 20:23 UTC, Mr-DG-Wick commented on src/collections/blog/2021-11-15-layer5-learning-path /index.mdx
> +import ServiceMesh from "./servicemesh.jpg";
```suggestion
import ServiceMesh from "./servicemeshes.png";
```

2021-11-14 20:24 UTC, Mr-DG-Wick commented on src/collections/blog/2021-11-15-layer5-learning-path /index.mdx
> +import Architecture from "./course-architecture.jpg";
```suggestion
import Architecture from "./course-architecture.png";
```

2021-11-14 20:29 UTC, Mr-DG-Wick requested changes
Thanks for taking this up @Anita-ihuman ! A good rule of thumb is to use .png image format over the .jpg format.

2021-11-14 20:35 UTC, Mr-DG-Wick commented on src/collections/blog/2021-11-15-layer5-learning-path /index.mdx
> +Learning Paths comprise courses that are hand-curated by the maintainers at Layer5 and equip you with the foundational tools like <a href=”https://meshery.io/”>Meshery</a> that assists you in compreh
```suggestion
Learning Paths comprise courses that are hand-curated by the maintainers at Layer5 and equip you with the foundational tools like <a href="https://meshery.io/">Meshery</a> that assists you in comprehending service mesh concepts. <a href="https://layer5.io/learn/learning-paths/mastering-service-meshes-for-developers">Mastering Service Meshes For Developers</a> is the initial Learning Path offering that focuses on Developers and what you need to know to successfully design workloads for a service mesh environment. 
```

2021-11-14 20:36 UTC, Mr-DG-Wick commented on src/collections/blog/2021-11-15-layer5-learning-path /index.mdx
> +After five months of community-based development, the Layer5 <a href="https://layer5.io/learn/learning-paths">Learning Paths</a> project, is officially launched! Exciting as it sounds, in addition to
```suggestion
After five months of community-based development, the Layer5 <a href="https://layer5.io/learn/learning-paths">Learning Paths</a> project, is officially launched! Exciting as it sounds, in addition to the existing free <a href="https://layer5.io/learn">service mesh training resources</a> available to you, Layer5 Learning Paths offer curated guides to assist you in developing your general cloud native networking knowledge and service mesh-specific skills. 
```

2021-11-16 18:29 UTC, warunicorn19 commented
@Anita-ihuman closing this PR and creating a new, the main problem is happening because the file name has a white space in it.

2021-11-16 18:29 UTC, closed without merging