Added callout for handbook
layer5io/layer5 pull request #2357
Opened 2021-11-16 16:36 UTC by YashKamboj

Signed-off-by: YashKamboj <75125203+YashKamboj@users.noreply.github.com>

**Description**Added callout for handbook on community page, newcomers page , and a small on learn course page

This PR fixes #2298 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2021-11-16 16:48 UTC, l5io commented
🚀 Preview for commit efc58db46da8fff211d8f4b8e11f68fc1c86c43d at: https://6193e05b7d352433cd47434c--layer5ng.netlify.app

2021-11-16 17:45 UTC, warunicorn19 commented
Let's not put more than 1 callout on one page. at max. 2

2021-11-17 04:13 UTC, leecalcote requested changes
@YashKamboj will you refactor this PR so that only intentional changes show in the diff? There are too many errant changes in this PR, making it difficult to review and approve.

2021-11-17 07:02 UTC, YashKamboj commented
@leecalcote Yeah , removed the errant changes, they were just because of the prettier extension in my vscode.

2021-11-17 07:11 UTC, l5io commented
🚀 Preview for commit 4a05844f01118f9d33772b2a27d94d1fdca08787 at: https://6194aaa5dc3f86bed921a727--layer5ng.netlify.app

2021-11-28 10:09 UTC, l5io commented
🚀 Preview for commit c065d65a827e5244a6d3dfca22097f648f57447d at: https://61a354e3360b458c9c6be1b1--layer5ng.netlify.app

2021-11-28 11:02 UTC, YashKamboj commented
@warunicorn19 remind??

2021-11-28 14:41 UTC, warunicorn19 commented
@debo19 @Nikhil-Ladha your inputs here would be great.

2021-11-28 17:33 UTC, YashKamboj commented on src/sections/Community/index.js
> +        <DiscussCallout />
On which should it be then?? @debo19

2021-11-28 18:37 UTC, YashKamboj commented on src/sections/Learn-Layer5/Course-Overview/index.js
> +            <HandbookCallout image={handbookcallourbng} />
About the Layer5 banner below which shows up , we can make a new image cropping the banner @debo19

2021-11-28 18:45 UTC, YashKamboj commented on src/sections/Learn-Layer5/Course-Overview/index.js
> +            <HandbookCallout image={handbookcallourbng} />
> 

The idea could be great  @debo19

2021-11-29 10:36 UTC, debo19 commented on src/sections/Community/index.js
> +        <DiscussCallout />
Ideally, https://layer5.io/community/newcomers should work. Though I don't see a space here as well to fit a small call-out 🤔

2021-11-29 10:56 UTC, YashKamboj commented on src/sections/Community/index.js
> +        <DiscussCallout />
@debo19 we can make  a banner on the newcomers page

2022-01-09 18:33 UTC, closed without merging