[task] added service mesh performance resource
layer5io/layer5 pull request #2359
Opened 2021-11-16 17:41 UTC by Mr-DG-Wick

Signed-off-by: Mr-DG-Wick <deepakgdkg1g8868@gmail.com>

**Description**

This PR fixes #2337

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2021-11-16 18:19 UTC, YashKamboj commented
@Mr-DG-Wick  looks like you forgot to self close the "img" tags on lines 113, 247, 279, 303 and 454.

2021-11-16 18:24 UTC, warunicorn19 commented on src/collections/resources/analyzing-service-mesh-performance/analyzing-service-mesh-performance.mdx
> +<TopicsWrapper>
```suggestion
<ResourcesWrapper>

```

2021-11-16 18:24 UTC, warunicorn19 commented on src/collections/resources/analyzing-service-mesh-performance/analyzing-service-mesh-performance.mdx
> +</TopicsWrapper>
```suggestion
</ResourcesWrapper>
```

2021-11-16 18:28 UTC, Mr-DG-Wick commented
Thanks for the review @YashKamboj @warunicorn19

2021-11-16 18:39 UTC, l5io commented
🚀 Preview for commit 7c0b0f093830f2536de750d93d143bb88f4e19af at: https://6193fa6a9ac8855642c76262--layer5ng.netlify.app

2021-11-16 19:54 UTC, leecalcote commented
@Mr-DG-Wick good stuff. A couple of the images have broken links in the build preview. Will you take a moment to also add a special section/callout to the IEEE article, too?

2021-11-16 20:00 UTC, Mr-DG-Wick commented
@leecalcote haven't I done already on top? 😅
The image part was intentional as I wanted to ask you for the images. Can you help me with the higher resolution images as I guess it was sent to you through mail in one of the comments when I was reading the doc?

2021-11-16 20:03 UTC, leecalcote commented
@Mr-DG-Wick, oh, yes, you did already. 🙂 I missed that.

2021-11-16 22:51 UTC, warunicorn19 commented
Ughh, i’m sorry i’ll look into this in the morning.

2021-11-17 06:35 UTC, l5io commented
🚀 Preview for commit 232a73a80991fbc112bb46b6f29b6f08d1268af0 at: https://6194a24df02645b6fa515021--layer5ng.netlify.app

2021-11-17 09:41 UTC, l5io commented
🚀 Preview for commit face66b9aaa38eecb0d1398159dcac0c6accfeda at: https://6194cddcf02645ee71515024--layer5ng.netlify.app

2021-11-17 11:12 UTC, Mr-DG-Wick commented
Go to merge? @leecalcote @warunicorn19

2021-11-18 19:57 UTC, warunicorn19 commented
@leecalcote is this good to merge?

2021-11-21 22:12 UTC, debo19 requested changes

2021-11-21 22:12 UTC, debo19 commented on src/collections/resources/analyzing-service-mesh-performance/analyzing-service-mesh-performance.mdx
> +<img src="x" alt="image req"/>
missing image here

2021-11-21 22:12 UTC, debo19 commented on src/collections/resources/analyzing-service-mesh-performance/analyzing-service-mesh-performance.mdx
> +      <a className="blog" href="https://www.nxtbook.com/nxtbooks/ieee/bridge_issue3_2021/index.php#/p/16">Analyzing Service Mesh Performance</a> - Published in issue 3 of IEEE Bridge October 2021
```suggestion
      <a className="blog" href="https://www.nxtbook.com/nxtbooks/ieee/bridge_issue3_2021/index.php#/p/16"> Analyzing Service Mesh Performance</a> - Published in issue 3 of IEEE Bridge October 2021

```

2021-11-21 22:12 UTC, debo19 commented on src/collections/resources/analyzing-service-mesh-performance/analyzing-service-mesh-performance.mdx
> +      <img src="{cover}" align="right" alt="IEEE The Bridge 2021 Issue 3 cover" />
```suggestion
      <img src={cover} align="right" alt="IEEE The Bridge 2021 Issue 3 cover" />

```
Broken image.

2021-11-21 22:12 UTC, debo19 commented on src/collections/resources/analyzing-service-mesh-performance/analyzing-service-mesh-performance.mdx
> +necessary or refuses to publish performance data because such tests can be 1) arduous to create and sustain a capable harness, 2) a point-in-time
Can you add an ordered list here instead of inline numbering?

2021-11-21 22:12 UTC, debo19 commented on src/collections/resources/analyzing-service-mesh-performance/analyzing-service-mesh-performance.mdx
> +a suitable test harness. A service mesh management plane can be such a tool. As the multi-mesh manager, <a href="https://meshery.io">Meshery</a>
```suggestion
a suitable test harness. A service mesh management plane can be such a tool. As the multi-mesh manager, <a href="https://meshery.io"> Meshery</a> 

```

2021-11-22 12:51 UTC, Mr-DG-Wick commented
Thanks for the review @debo19 😄 
All changes done.

2021-11-22 12:52 UTC, l5io commented
🚀 Preview for commit da79f82ba3a185862afec954edfd45886b324f45 at: https://619b92305c9584f300e11fde--layer5ng.netlify.app

2021-11-27 12:17 UTC, debo19 reviewed
https://user-images.githubusercontent.com/85789734/143680904-4617780d-e934-4d9e-99dd-26680cfb6e25.mp4

@Mr-DG-Wick The cover image in the intro is too big. Also, I don't think it's required either, can you remove the image and just keep the text here?

2021-11-28 21:02 UTC, Mr-DG-Wick commented
Nice suggestion @debo19 . I agree on this one myself, but this image was added by @leecalcote. Let's see what Lee thinks and I'll take work on your suggestion asap 😄

2021-11-29 10:26 UTC, debo19 commented
Alright @Mr-DG-Wick, in that case, we still need the image to be smaller. One way could be to place the image in a column beside the text in the intro.  Can you work on that so we can see how it looks?

2021-11-29 17:41 UTC, warunicorn19 commented
> Analyzing.Service.Mesh.Performance._.Layer5.-.The.Service.Mesh.Company.-.Google.Chrome.2021-11-27.17-44-29.mp4 
> @Mr-DG-Wick The cover image in the intro is too big. Also, I don't think it's required either, can you remove the image and just keep the text here?

I'm pretty sure this is not the sizing that we need to stick, it needs to be way smaller.

2021-11-29 17:44 UTC, Mr-DG-Wick commented
> Alright @Mr-DG-Wick, in that case, we still need the image to be smaller. One way could be to place the image in a column beside the text in the intro. Can you work on that so we can see how it looks?

Sounds good @debo19 , on it.

2021-12-01 13:45 UTC, l5io commented
🚀 Preview for commit 178a0734b31b5eb42ceacec07625c861caad6b37 at: https://61a77bfb734e200be69e15e2--layer5ng.netlify.app

2021-12-03 09:12 UTC, Mr-DG-Wick commented
@debo19 @warunicorn19 @leecalcote @YashKamboj Good to merge?

2021-12-03 09:25 UTC, YashKamboj commented
@Mr-DG-Wick it would look better if you add a liitle padding or margin around the images, now there is no space between the text and the image![Screenshot_2021-12-03-14-54-51-37_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/75125203/144578487-636ae613-acbb-4eef-86c6-4ccd211a3a3c.jpg)

2021-12-04 02:42 UTC, leecalcote commented
Yes, only two minor items left:

1) reduce the size of the second and third images (left or right aligned so text wraps) with hyperlink so that the viewer may click to enlarge the image.
2) (what @YashKamboj said)  add margin to the first image.

Good to go.

2021-12-06 19:15 UTC, l5io commented
🚀 Preview for commit 1a7d57d1e98f5802b41ff20ce186f74fa68fb3f8 at: https://61ae612c03a63715d4d5a18d--layer5ng.netlify.app

2021-12-06 19:22 UTC, warunicorn19 requested changes
There are still some issues with the images. The aspect ratios are off. 
<img width="1440" alt="Screenshot 2021-12-07 at 12 50 32 AM" src="https://user-images.githubusercontent.com/53532328/144908683-c54dc055-138c-4113-a2b9-9d38a086707d.png">

Also the image of the code snippet becomes really small when screen size is removed.

2021-12-06 19:57 UTC, Mr-DG-Wick commented
> There are still some issues with the images. The aspect ratios are off. <img alt="Screenshot 2021-12-07 at 12 50 32 AM" width="1440" src="https://user-images.githubusercontent.com/53532328/144908683-c54dc055-138c-4113-a2b9-9d38a086707d.png">
> 
> Also the image of the code snippet becomes really small when screen size is removed.

yup @warunicorn19 figuring it out still.

2021-12-06 20:22 UTC, l5io commented
🚀 Preview for commit 8b28bdb100bd9a8092c341971893d6bec38ed183 at: https://61ae70e253d59a1e5bfb8a7c--layer5ng.netlify.app

2021-12-06 20:44 UTC, l5io commented
🚀 Preview for commit a1e6af6e61edc345cbdf3180daeb1361704dd190 at: https://61ae75fde40be02902c185b4--layer5ng.netlify.app

2021-12-06 22:35 UTC, leecalcote commented
Looking good here. ![image](https://user-images.githubusercontent.com/7570704/144933729-d46ce582-46f3-41cf-ac68-9d2e2cf1b173.png)

2021-12-13 11:46 UTC, l5io commented
🚀 Preview for commit 45fdeccb03855e997b4196bb98c56655732faf5d at: https://61b73213ba045a69ab2a6183--layer5ng.netlify.app

2021-12-13 12:05 UTC, l5io commented
🚀 Preview for commit b8020d7745aa3044898cfaf2d8bb0f4dbf0ca6ad at: https://61b736e61fc60bf65732a12e--layer5ng.netlify.app

2021-12-13 14:42 UTC, l5io commented
🚀 Preview for commit cddbd9365846af1ff11c41675a965d5792c680ff at: https://61b75b61586b1f1372fcd49f--layer5ng.netlify.app

2021-12-13 16:01 UTC, debo19 approved these changes
LGTM 🎉

2021-12-14 11:00 UTC, warunicorn19 approved these changes
LGTM, Thank you @Mr-DG-Wick for seeing this to the end.

2021-12-14 11:00 UTC, merged