Add chinese version
layer5io/layer5 pull request #2376
Opened 2021-11-26 02:29 UTC by Aisuko

Signed-off-by: aisuko <urakiny@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-11-26 02:31 UTC, Aisuko commented
Here @Micost

2021-11-26 07:01 UTC, gyohuangxin reviewed
@Aisuko Great, and I leave suggestion for some typo.

2021-11-26 12:47 UTC, Aisuko commented
Hi @warunicorn19 , Would you mind help us to check the CI error. I saw you are the master on this project.

2021-11-26 13:13 UTC, warunicorn19 commented
Sure @Aisuko, i will take a look 😃

2021-11-26 13:30 UTC, warunicorn19 requested changes

2021-11-26 13:30 UTC, warunicorn19 commented on src/collections/events/kubecon-china-2021/index.mdx
> +<li><Link to="/community/members/aisuko-li">Aisuko Lee</li>
```suggestion
<li><Link to="/community/members/aisuko-li">Aisuko Lee</Link></li>
```

2021-11-26 13:44 UTC, warunicorn19 requested changes

2021-11-26 13:44 UTC, warunicorn19 commented on src/collections/events/kubecon-china-2021/index.mdx
> +<li><Link to="/community/members/aisuko-li">Aisuko Lee</li>
```suggestion
<li><Link to="/community/members/aisuko-li">Aisuko Lee</Link></li>
```

2021-11-26 13:55 UTC, l5io commented
🚀 Preview for commit 93f72812978e3b8019308950876e7c38dd5cebbd at: https://61a0e6e760728c0dc2a57e51--layer5ng.netlify.app

2021-11-26 14:02 UTC, warunicorn19 approved these changes
@Aisuko fixed the build fail. Merge at will.

2021-11-26 16:47 UTC, navendu-pottekkat commented
@Aisuko Could we go English, Mandarin, English, Mandarin ...

Or English first completely and then Mandarin?

I think either of these would be better.

Let me also confirm the other participants.

2021-11-27 05:14 UTC, Aisuko commented
> @Aisuko fixed the build fail. Merge at will.

Thank you @warunicorn19 👍

2021-11-27 05:17 UTC, Aisuko commented
> @Aisuko Could we go English, Mandarin, English, Mandarin ...
> 
> Or English first completely and then Mandarin?
> 
> I think either of these would be better.
> 
> Let me also confirm the other participants.

Yes, the format that you said is very clear than current. English go first completely and than Mandarin would be good.

2021-11-28 01:29 UTC, l5io commented
🚀 Preview for commit 28f7f3c39b17a04343e036cb0fade6c21b076966 at: https://61a2db09f91bffb8d106d788--layer5ng.netlify.app

2021-11-30 20:28 UTC, leecalcote approved these changes
Thank you, gents. This is excellent.

2021-11-30 20:28 UTC, merged

2021-11-30 20:30 UTC, leecalcote commented
@gyohuangxin, if we can get you started on running service mesh performance benchmarks, then let's get your name on the SMP office hours and you into the discussion (office hours) at KubeCon.

2021-12-01 03:20 UTC, gyohuangxin commented
> @gyohuangxin, if we can get you started on running service mesh performance benchmarks, then let's get your name on the SMP office hours and you into the discussion (office hours) at KubeCon.

@leecalcote Yes, I can run SMP and get started on developing SMP Github action, it's good for me to join the office hours, thanks! Please let me know if I can be of any help.