New article added in the Layer5 Newsroom
layer5io/layer5 pull request #2394
Opened 2021-12-02 15:55 UTC by MukulKolpe

**Description**

This PR fixes #2389

**Notes for Reviewers**
Added "6 CNCF Service Mesh Tools" article in the Layer5 Newsroom.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

2021-12-02 19:40 UTC, leecalcote requested changes
Uh-oh - - https://github.com/layer5io/layer5/runs/4397405029?check_suite_focus=true#step:3:147

2021-12-02 19:41 UTC, leecalcote commented on src/collections/news/2021-10-15-6-cncf-service-mesh-tools/index.mdx
> +eurl: https://containerjournal.com/features/6-cncf-service-mesh-tools/#:~:text=5.%20Meshery,of%20Service%20Mesh%20Performance%20(SMP).
```suggestion
eurl: https://containerjournal.com/features/6-cncf-service-mesh-tools/#:~:text=5.%20Meshery,of%20Service%20Mesh%20Performance%20(SMP).
```
```suggestion
eurl: https://containerjournal.com/features/6-cncf-service-mesh-tools
```

2021-12-02 19:41 UTC, leecalcote commented on src/collections/news/2021-10-15-6-cncf-service-mesh-tools/index.mdx
> +**Read the full article on [Container Journal](https://containerjournal.com/features/6-cncf-service-mesh-tools/#:~:text=5.%20Meshery,of%20Service%20Mesh%20Performance%20(SMP).).**
```suggestion
**Read the full article on [Container Journal](https://containerjournal.com/features/6-cncf-service-mesh-tools).**
```

2021-12-02 20:59 UTC, merged

2021-12-03 04:42 UTC, MukulKolpe commented
Thank you @leecalcote !!