Adding Manav Kapoor's Profile as a Community Member
layer5io/layer5 pull request #2406
Opened 2021-12-08 15:10 UTC by Deepansharora27

**Description**

This PR fixes #2404 

**Notes for Reviewers**

- [ ] Yes, I signed my commits.

2021-12-08 15:12 UTC, Deepansharora27 commented
Also, tagging @leecalcote @warunicorn19  for the update

2021-12-08 15:13 UTC, warunicorn19 commented
@Deepansharora27 Seems like you forgot to sign off😅

2021-12-08 15:16 UTC, Deepansharora27 commented
@Yeah Sorry for that @warunicorn19 
Solved it 
Will keep that in mind for future PR's

2021-12-08 15:39 UTC, Deepansharora27 commented
The Preview Build was failing 
I guess the reason for it was that I made a typo while specifying the Path of the Image 
Have Fixed it Now !!

2021-12-08 19:03 UTC, warunicorn19 requested changes
@Deepansharora27 the build is failing because of the "" used in the bio, could you please remove those.

2021-12-08 19:08 UTC, leecalcote commented
@manav1403 🎈 !

2021-12-08 19:09 UTC, manav1403 commented
> @manav1403 🎈 !

🎉🎉😁

2021-12-08 21:57 UTC, warunicorn19 requested changes

2021-12-08 21:57 UTC, warunicorn19 commented on src/collections/members/manav-kapoor/index.mdx
> +bio: "I love technology, so my work is nothing but my love. #lovefortechnology"
```suggestion
bio: I love technology, so my work is nothing but my love. #lovefortechnology
```

2021-12-09 03:30 UTC, Deepansharora27 commented
> @Deepansharora27 the build is failing because of the "" used in the bio, could you please remove those.

But, in the Profile Member Template it was mentioned to include the bio in double quotations and if we hop onto @leecalcote profile template as well, his bio is also enclosed within double quotes.

2021-12-09 06:45 UTC, warunicorn19 commented
Yes, @Deepansharora27 you are right, let me take a look.

2021-12-09 07:03 UTC, l5io commented
🚀 Preview for commit 9c677ffc935724c555cb224451bdc90875dc9bfa at: https://61b1a9b7455d75e64e5c1849--layer5ng.netlify.app

2021-12-09 07:06 UTC, warunicorn19 commented
https://61b1a9b7455d75e64e5c1849--layer5ng.netlify.app/community/members/manav-kapoor

@manav1403^^ waiting for your all-clear.

2021-12-09 17:46 UTC, manav1403 approved these changes

2021-12-09 17:47 UTC, manav1403 commented
> https://61b1a9b7455d75e64e5c1849--layer5ng.netlify.app/community/members/manav-kapoor
> 
> @manav1403^^ waiting for your all-clear.

Thanks @Deepansharora27 and @warunicorn19 :)

2021-12-09 22:50 UTC, leecalcote approved these changes
Awesome.

thank you, @Deepansharora27

2021-12-09 22:50 UTC, merged