chore(events): Added Event Measuring Service Mesh Performance 101
layer5io/layer5 pull request #2425
Opened 2021-12-18 11:54 UTC by Abhijay007

Signed-off-by: Abhijay Jain <Abhijay007j@gmail.com>

**Description**

Added Event Measuring Service Mesh Performance 101 

This PR fixes #2421 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-12-18 12:05 UTC, l5io commented
🚀 Preview for commit 826ad914191ee9b751e4ed986a97dc9b5601b81e at: https://61bdce498450846e0f09a6e6--layer5ng.netlify.app

2021-12-19 15:38 UTC, leecalcote requested changes

2021-12-19 15:38 UTC, leecalcote commented on src/collections/events/devconf/index.mdx
> +  This talk answers these questions by empowering attendees with at-hand tooling
This description starts without context for what "the questions" are.

2021-12-19 16:27 UTC, l5io commented
🚀 Preview for commit fddf8a556eca0fa174d1ed33a35ecafc03be21d7 at: https://61bf5d3b2671bc319b71091e--layer5ng.netlify.app

2021-12-20 08:10 UTC, Mr-DG-Wick reviewed
hi @Abhijay007 thank you for working on this!
Gave some suggestions that you may look into.

2021-12-20 08:10 UTC, Mr-DG-Wick commented on src/collections/events/devconf/index.mdx
> +Questions arise like:
```suggestion

```

2021-12-20 08:10 UTC, Mr-DG-Wick commented on src/collections/events/devconf/index.mdx
> +Benchmarking a service mesh and your workload’s performance is no simple task.
```suggestion
Benchmarking a service mesh and your workload’s performance is no simple task. Questions arise like:
```

2021-12-20 08:10 UTC, Mr-DG-Wick commented on src/collections/events/devconf/index.mdx
> +Which load generator should you use and what signals should you measure?
can you please add these questions as an unordered list?

2021-12-20 08:32 UTC, Abhijay007 commented
@Mr-DG-Wick it's done, is it fine now? 

![image](https://user-images.githubusercontent.com/64387054/146736416-efcd616c-d9fe-4bf0-832e-8de4fb565630.png)

2021-12-20 08:45 UTC, l5io commented
🚀 Preview for commit 99837c59548bc02d008d382cc61a3ec80e93be6e at: https://61c04236fafca8d927baf9ce--layer5ng.netlify.app

2021-12-20 08:51 UTC, Mr-DG-Wick approved these changes
LGTM! 🎉 🥳 
Thank you @Abhijay007 !

2021-12-26 10:24 UTC, adithyaakrishna requested changes
@Abhijay007 Could you make this small change? Thanks for your contribution 🎉

2021-12-26 10:24 UTC, adithyaakrishna commented on src/collections/events/devconf/index.mdx
> +title: "DEVCONF 2021"
```suggestion
title: "DEVCONF 2022"
```

2021-12-26 10:28 UTC, Abhijay007 commented on src/collections/events/devconf/index.mdx
> +title: "DEVCONF 2021"
sure !!

2021-12-26 10:37 UTC, adithyaakrishna commented
@Abhijay007 could you please check the DCO failing issue?

2021-12-26 10:37 UTC, Abhijay007 commented
I don't know why these tests are failing? As I already signed DCO

2021-12-26 10:38 UTC, adithyaakrishna commented
Can you ping me in Slack?
Let's have a call and I'll help ya with this

2021-12-26 10:38 UTC, Abhijay007 commented
> @Abhijay007 could you please check the DCO failing issue?

I already signed that but don't know why it is failing

2021-12-26 10:39 UTC, Abhijay007 commented
> Can you ping me in Slack? Let's have a call and I'll help ya with this

ok sure

2021-12-26 10:44 UTC, closed without merging