Filter menu hidden in mobile view
layer5io/layer5 pull request #2462
Opened 2022-01-08 20:04 UTC by Ciggzy1312

Signed-off-by: Deepayan <deepayanmukherjee1312@gmail.com>

**Description**
Added hide button to keep filters hidden in mobile view
This PR fixes #2439 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-01-08 20:18 UTC, l5io commented
🚀 Preview for commit a2ec18ae031238c6b8ff6cc40349bd4b70f6e369 at: https://61d9f13e3d5c03b974ae27a0--layer5ng.netlify.app

2022-01-08 20:33 UTC, warunicorn19 commented
Package-lock will have to be reverted here.

2022-01-09 08:09 UTC, YashKamboj commented
@Ciggzy1312 there is no button to hide the menu between 1000px and 750px, and making the default state as hidden for the menu would also be good idea.

https://user-images.githubusercontent.com/75125203/148674424-082b56e9-6c1a-4a01-9ac9-472322284d67.mp4

2022-01-09 12:08 UTC, Ciggzy1312 commented
Nice catch @YashKamboj 
Will fix it

2022-01-10 13:22 UTC, Nikhil-Ladha commented
The current resources page is spread out way toooo much!
Maybe you could send out a different PR after this to fix that, it should look similar to `/blog` (wrt to the width)

2022-01-10 13:26 UTC, warunicorn19 commented
@Nikhil-Ladha I think the reason that it is spread out is because of the way the filters work in resources. It is a global filter. Though the code could use some refactoring.

2022-01-10 14:04 UTC, Nikhil-Ladha commented
> @Nikhil-Ladha I think the reason that it is spread out is because of the way the filters work in resources. It is a global filter. Though the code could use some refactoring.

Wdym by "global-filter" ? Whatever data it filters it is within the page itself, so what's the issue in enclosing everything within a single "container" tag?

2022-01-10 14:07 UTC, warunicorn19 commented
Actually the filter works on blogs and news as well if I'm not wrong. @debo19 would probably be able to explain it better.

2022-01-10 14:08 UTC, warunicorn19 commented
I guess we can enclose it in a single container tag 🤔

2022-01-10 14:50 UTC, debo19 commented
> Actually the filter works on blogs and news as well if I'm not wrong. @debo19 would probably be able to explain it better.

@warunicorn19 It's a styling issue, that shouldn't be a problem. @Ciggzy1312 I'll look into this in my open PR, you can go ahead with adding the Open filter button as discussed today.

2022-01-10 14:56 UTC, warunicorn19 commented
I completely misunderstood what @Nikhil-Ladha was saying🤦‍♂️.

2022-01-12 20:17 UTC, l5io commented
🚀 Preview for commit a88db7aa482100762850ddd7bcc4915e8d6cc2a9 at: https://61df36d2a6ffc0398dd9eec6--layer5ng.netlify.app

2022-01-13 11:47 UTC, debo19 requested changes

2022-01-13 11:47 UTC, debo19 commented on src/sections/Resources/Resources-grid/filters.js
> +                <FiFilter className="filter-icon"/>
![open](https://user-images.githubusercontent.com/85789734/149320919-54fa004c-ade8-4959-b9e6-30f9b5618502.jpg)

Can you enclose this inside a Button? Also, increase the space between the resource card and the button.

2022-01-13 11:47 UTC, debo19 commented on src/sections/Resources/Resources-grid/filters.js
> +            <span>Close Filters</span>
![clearafter](https://user-images.githubusercontent.com/85789734/149321817-e6ade112-d9c8-4f82-b435-19b83f16397f.jpg)

We still need the `Clear Filters` option like we have now. 

![clearbefore](https://user-images.githubusercontent.com/85789734/149321798-8a9da854-97e2-49eb-b15d-03c1a68c84df.jpg)

2022-01-13 12:09 UTC, debo19 commented on src/sections/Resources/Resources-grid/filters.js
> +                <FiFilter className="filter-icon"/>
Align the text to the center of the icon.

2022-01-13 16:31 UTC, l5io commented
🚀 Preview for commit d06a61b8b41a19ec3948f024195799dbdaca1140 at: https://61e0538778d1d60062a586b4--layer5ng.netlify.app

2022-01-14 05:54 UTC, l5io commented
🚀 Preview for commit 91640c950e3a43cf5abf2c47c874d666f560bbbc at: https://61e10fc6a3cde2aad7bc1671--layer5ng.netlify.app

2022-01-17 16:42 UTC, l5io commented
🚀 Preview for commit f5eb5d0a7e7fd118dfba55bbc8de3b50cd89b3e7 at: https://61e59c1020b5dcbf1e908eb1--layer5ng.netlify.app

2022-01-17 20:51 UTC, leecalcote commented
Heads-up - the arrow is being line-wrapped (in Safari, at least) -
<img width="721" alt="Screen Shot 2022-01-17 at 2 50 49 PM" src="https://user-images.githubusercontent.com/7570704/149835680-a31a17c7-ebc1-408a-8d1d-1947c29c6aad.png">

2022-01-22 11:35 UTC, closed without merging