[Community] Community Managers page
layer5io/layer5 pull request #2486
Opened 2022-01-16 12:03 UTC by Chadha93

Signed-off-by: Gaurav Chadha <gauravchadha1676@gmail.com>

**Description**

- Removed Community from "Community MeshMates" title.
- Added a new entry of section under Community > Members >  Community Managers(under MesMates).
- Updated the gatsby graphql query for managers.
- New page for Layer5 Community Managers.
- Fix other minor lint errors for some files.

This PR fixes #2484 

**Notes for Reviewers**
Page and query for managers tested OK

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-01-16 12:17 UTC, l5io commented
🚀 Preview for commit 36b7f2484ca56bf76d9bb4368daf74431e3b9519 at: https://61e40ca6232a13ae711873c1--layer5ng.netlify.app

2022-01-16 15:50 UTC, warunicorn19 commented
@Chadha93 could we discuss this on the websites' call tomorrow if you're available.

2022-01-16 15:55 UTC, Chadha93 commented
> @Chadha93 could we discuss this on the websites' call tomorrow if you're available.?

Sure @warunicorn19 sounds good.

2022-01-16 15:56 UTC, warunicorn19 commented
Thank you @Chadha93

2022-01-17 02:50 UTC, leecalcote commented
remove mega menu item

2022-01-17 03:03 UTC, l5io commented
🚀 Preview for commit d317eb1c109e9334fb26334babf9371a6d712777 at: https://61e4dc39a71e1ebdc073b330--layer5ng.netlify.app

2022-01-17 14:23 UTC, l5io commented
🚀 Preview for commit 7c5dab2cdb5bd99080b415445d7b44dca0236b9c at: https://61e57b75a71e1e793f73af46--layer5ng.netlify.app

2022-01-18 19:30 UTC, l5io commented
🚀 Preview for commit 208b31a1c02dd0f915a4048d9351835e851a1938 at: https://61e714e3acb7ff139ab77fa1--layer5ng.netlify.app

2022-01-18 19:31 UTC, Chadha93 commented
@warunicorn19 Updated according to the suggestions made on the call, let's review and tie this off. :)

2022-01-18 19:44 UTC, warunicorn19 requested changes

2022-01-18 19:44 UTC, warunicorn19 commented on src/sections/Community/CommunityManagers/index.js
> +          <h2> What Does the Community Managers Do? </h2>
```suggestion
          <h2> What Does a Community Manager Do? </h2>
```

2022-01-18 19:44 UTC, warunicorn19 commented on src/sections/Community/CommunityManagers/index.js
> +          <p>Checkout their Community roles and responsibilites on <a href="https://layer5.io/community/handbook/community-roles">Community Handbook</a></p>
```suggestion
          <p>Take a look at the <Link to="/community/handbook">Community Handbook</a></p>
```

2022-01-18 19:44 UTC, warunicorn19 commented on src/sections/Community/CommunityManagers/index.js
> +
```suggestion
import {Link} from "gatsby";
import { IoIosArrowRoundForward } from "react-icons/io";

```

2022-01-18 19:44 UTC, warunicorn19 commented on src/sections/Community/Meshmates/index.js
> +          <h4> Explore about Community Manager at <a href="/community/managers">Layer5 Community Managers</a></h4>
```suggestion
          <h4> Get to know about <Link to="/community/managers">Layer5 Community Managers <IoIosArrowRoundForward /></a></h4>
```

2022-01-18 22:50 UTC, l5io commented
🚀 Preview for commit 3800d8a1d4bc733bd42c5fe19d9fad43e647ac0f at: https://61e743e4492e1500ac708549--layer5ng.netlify.app

2022-01-18 22:52 UTC, warunicorn19 approved these changes
LGTM! Thanks @Chadha93

2022-01-18 22:52 UTC, merged