[Site Performance] Image optimization
layer5io/layer5 pull request #2533
Opened 2022-01-22 23:00 UTC by debo19

Signed-off-by: Debopriya Bhattacharjee <debopriyabh1908@gmail.com>

**Description**
1. Removed duplicate images in various folders. Imported images from /assets folder instead.
2. Recommending the use of `<StaticImages/>` instead of `<img>` to improve image optimization and site performance.

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-01-22 23:06 UTC, Abhijay007 commented
@debo19 this PR is related to [this](https://github.com/layer5io/layer5/issues/2172) issue, right?

2022-01-22 23:11 UTC, debo19 commented
@Abhijay007 it's a part of this, yes.

2022-01-22 23:14 UTC, l5io commented
🚀 Preview for commit 0fc108f746cc222211426947de70ab6402fc0349 at: https://61ec8f810b7692bcda055a69--layer5ng.netlify.app

2022-01-22 23:26 UTC, Abhijay007 approved these changes
LGTM 👍

2022-01-22 23:46 UTC, leecalcote commented on src/components/SocialLinks-Color/index.js
> +          <a href="https://slack.layer5.io/" target="_blank" rel="noreferrer">
```suggestion
          <a href="https://slack.layer5.io/" target="_blank">
```

Let's make a point of leaving out  `rel="noreferrer"` on links within the layer5.io domain.

2022-01-22 23:47 UTC, leecalcote commented on src/components/SocialLinks/index.js
>              rel="noreferrer"
```suggestion
```

2022-01-22 23:47 UTC, leecalcote commented on src/sections/Community/Handbook/projects.js
> +import PatternsLogo from "../../../assets/images/service-mesh-patterns/service-mesh-pattern.svg";
From PNG to SVG and from duplicate to centralized. Nice work.

2022-01-22 23:50 UTC, leecalcote approved these changes
`img` to `StaticImage` ✔️

2022-01-23 00:04 UTC, l5io commented
🚀 Preview for commit 62bbb7896173714d569c68717fade8c5ffe05ada at: https://61ec9b120b7692c7400554d0--layer5ng.netlify.app

2022-01-23 03:20 UTC, Nikhil-Ladha commented on gatsby-config.js
> +    "gatsby-plugin-image",
These are already used, check line 367.
Please undo this

2022-01-23 03:20 UTC, Nikhil-Ladha commented on gatsby-config.js
> +    "gatsby-plugin-image",
All 3 of them

2022-01-23 03:26 UTC, Nikhil-Ladha commented on src/sections/Meshery/meshery-operator/index.js
> +                <StaticImage src="../../../assets/images/meshery-operator/meshery-operator.png" className="logo" />
One change, in order to keep the code clean.

After all the imports,  assign the image path which is going be used in the static image component to a variable like
`const Operator="enter the image path here"` and then use this variable name as the `src` value in `StaticImage` component.

2022-01-23 03:26 UTC, Nikhil-Ladha commented on src/sections/Meshery/meshery-operator/index.js
> +                <StaticImage src="../../../assets/images/meshery-operator/meshery-operator.png" className="logo" />
Make this update at other places as well in the PR, where you are using StaticImage.

2022-01-23 03:27 UTC, Nikhil-Ladha reviewed
Also, have you removed all the images which are unused and is replaced by the generic image?

2022-01-23 03:27 UTC, Nikhil-Ladha requested changes
Few changes are needed as mentioned above

2022-01-23 08:08 UTC, debo19 commented
> Also, have you removed all the images which are unused and is replaced by the generic image?

I've done that for most logos. Haven't checked for other images yet.

2022-01-23 08:15 UTC, l5io commented
🚀 Preview for commit da93e85a76633b003eb4a3f64a8204cb4337c93f at: https://61ed0e16bc4aa13c28b3b327--layer5ng.netlify.app

2022-01-23 11:46 UTC, Nikhil-Ladha commented
> > Also, have you removed all the images which are unused and is replaced by the generic image?
> 
> I've done that for most logos. Haven't checked for other images yet.

Ahh...cool. Just for the files which you have made the changes in this PR. Others van be tackled in a separate PR , if need be.

2022-01-23 11:48 UTC, Nikhil-Ladha approved these changes
Looks good 👌🏼

2022-01-23 11:48 UTC, merged

2022-01-23 20:35 UTC, leecalcote commented
It would be good to update the CONTRIBUTING.md to include things like:

- use of `StaticImage` vs `img`.
- location of images / assets
- not to use `rel="noreferrer"` on internal hyperlinks (external only).
- use of theme colors.
- others...