Reformatting of the single column blog list view
layer5io/layer5 pull request #2540
Opened 2022-01-25 09:58 UTC by AbhishekJamhoriya

Signed-off-by: AbhishekJamhoriya <jamhoriya.1@iitj.ac.in>

**Description**
changed the UI of the single column blog list view from broad to dense.
This PR fixes #248

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-01-25 11:01 UTC, Nikhil-Ladha commented
Can you list the issue that this PR resolves?
The mentioned issue number is incorrect.

2022-01-25 14:30 UTC, l5io commented
🚀 Preview for commit 6137da9413aa43c7b0a309692c5ca4269a2fa47e at: https://61f00919a3887219990682cd--layer5ng.netlify.app

2022-01-25 14:39 UTC, leecalcote commented
Ooooh, nice. This is looking pretty good, @AbhishekJamhoriya

2022-01-25 16:15 UTC, AbhishekJamhoriya commented
Thanks @leecalcote

2022-01-25 16:15 UTC, AbhishekJamhoriya commented
> Can you list the issue that this PR resolves? The mentioned issue number is incorrect.

Done.

2022-01-25 16:53 UTC, warunicorn19 requested changes
The cards are looking a bit weird in smaller views, could you please reduce the extra whitespace on the top and the bottom. 
<img width="453" alt="Screenshot 2022-01-25 at 11 52 01 AM" src="https://user-images.githubusercontent.com/53532328/151022059-258709bd-cf05-4af0-bdb0-10e1575c622d.png">

2022-01-26 12:09 UTC, Nikhil-Ladha requested changes
Also, while we are on this page I think it is better to update the limit from 8 to 10 for blogs per page as we have a lot of tags now, which goes far below the blogs section. So, this will accommodate that.
Update this https://github.com/layer5io/layer5/blob/8d2b25cf4f3f5e68ce664e76868c81d97854c1b9/gatsby-node.js#L271
to 10.

2022-01-26 12:09 UTC, Nikhil-Ladha commented on src/sections/Blog/Blog-list/blogList.style.js
>  		font-size: 1.75rem;
Let's make this 1.5rem

2022-01-26 12:09 UTC, Nikhil-Ladha commented on src/sections/Blog/Blog-list/index.js
> +  console.log("data",data);
Remove this

2022-01-26 12:09 UTC, l5io commented
🚀 Preview for commit bcae184b13ffaf944aef8bbe05760d9ba0526909 at: https://61f139a7e43c3ea68e15903e--layer5ng.netlify.app

2022-01-28 06:08 UTC, l5io commented
🚀 Preview for commit 3d97517e0a89f55f2572254a54c4bf63ada47252 at: https://61f387881b85074641a257ee--layer5ng.netlify.app

2022-01-28 06:15 UTC, Nikhil-Ladha approved these changes
LGTM 👍🏼

2022-01-28 06:18 UTC, Nikhil-Ladha commented
@warunicorn19 do you wanna review or not 😂 .....otherwise please clear the path for merging :p

2022-01-31 04:19 UTC, warunicorn19 commented
So sorry I missed this @Nikhil-Ladha😅

2022-01-31 04:19 UTC, merged