Site Performance : Careers page Image optimization
layer5io/layer5 pull request #2543
Opened 2022-01-25 16:51 UTC by YashKamboj

Signed-off-by: YashKamboj <75125203+YashKamboj@users.noreply.github.com>

**Description**
Replaced  to for improving image optimization and site performance, and also moved images to the respected folders in order to achieve the same.
This PR fixes #2172 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-01-25 17:01 UTC, Nikhil-Ladha commented
Prefer `updates` over `fixes` when referring to the perf issue so that it doesn't get's closed when the PR is merged.

2022-01-25 17:03 UTC, l5io commented
🚀 Preview for commit 10990646d2e9375cffa0ac7b7ef4d97e2d7f1e3b at: https://61f02ce329ac3170c7fbf789--layer5ng.netlify.app

2022-01-25 17:03 UTC, Nikhil-Ladha requested changes

2022-01-25 17:03 UTC, Nikhil-Ladha commented on src/sections/Careers/Careers-Internship-grid/index.js
> -import Peek_Img from "../../../assets/images/layer5/layer5-peek-card-edited.svg";
Add a line break after all the imports, for readabillity.

2022-01-25 17:03 UTC, Nikhil-Ladha commented on src/sections/Careers/index.js
> +const Lee_and_Rigs = "../../assets/images/careers/Lee-and-Rigs-Caballero-of-Google.jpeg";
Please don't do this.
Keep all the imports together and variables separate from it.
Add this after line: 10 (after a line break)

2022-01-26 04:43 UTC, l5io commented
🚀 Preview for commit 399fe80ab90ce9d23df47c33f0a0bda57eb70b29 at: https://61f0d1192d8d5517c167dd47--layer5ng.netlify.app

2022-01-26 11:56 UTC, Nikhil-Ladha approved these changes

2022-01-26 11:56 UTC, merged