add Rss feed to events
layer5io/layer5 pull request #2556
Opened 2022-01-29 09:19 UTC by Sunnyio

Signed-off-by: Sunny Kumar <sunny514173@gmail.com>

**Description**

This PR fixes #2554

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-01-29 09:32 UTC, l5io commented
🚀 Preview for commit 54f7806805c192eee52e8ec5188588d17be7b68f at: https://61f50915d5bc6ee5fed06078--layer5ng.netlify.app

2022-02-03 05:09 UTC, Nikhil-Ladha requested changes

2022-02-03 05:09 UTC, Nikhil-Ladha commented on gatsby-config.js
> +            title: "Layer5"
Make it `Layer5 Events`.

2022-02-03 05:10 UTC, Nikhil-Ladha commented
Also, @Sunnyio once this PR is merged please fetch the latest code from upstream and update your fork. I see the file contains some old data, which might create conflicts in future PRs.

2022-02-03 06:17 UTC, Sunnyio commented
Sure @Nikhil-Ladha. Can you please review it again?

2022-02-03 06:24 UTC, l5io commented
🚀 Preview for commit 1ad32ca976c5b55b2a8597969cca4eb2fea6f8bd at: https://61fb74b116218c265a7c5bb7--layer5ng.netlify.app

2022-02-03 07:35 UTC, Nikhil-Ladha approved these changes

2022-02-03 07:36 UTC, merged