Added Tutorials in resources collections
layer5io/layer5 pull request #2575
Opened 2022-02-02 11:28 UTC by YashKamboj

Signed-off-by: YashKamboj <75125203+YashKamboj@users.noreply.github.com>

**Description**
Added Tutorials in resources collections
This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-02-02 11:45 UTC, l5io commented
🚀 Preview for commit 95d01370a3e7bf69ba3f349f237b3e9e90455d00 at: https://61fa6e758d3b5a00634e6b90--layer5ng.netlify.app

2022-02-03 05:14 UTC, Nikhil-Ladha requested changes
Never have file/folder/image name with spaces! Please update them to use a hyphen (-) instead.
Also, no need for the folder/image names to be capitalized.

2022-02-03 09:47 UTC, l5io commented
🚀 Preview for commit 19ea31bca6cc1c25acd56e885029219908ace84a at: https://61fba455804d9464a0c3da7a--layer5ng.netlify.app

2022-02-03 15:57 UTC, debo19 reviewed
Since you've created an entirely new collection, the "Related Resources" is not configured for each tutorial. Now instead of doing that all over again, I think the better way will be to just include a `tutorials` folder inside the `resources` folder itself. Check out the `recorded webinar` inside `resources`. That will unite this with other resources.

2022-02-03 15:57 UTC, debo19 commented on src/collections/tutorials/Resources.style.js
> +export const ResourcesWrapper = styled.div`
This file is not required.

2022-02-03 18:10 UTC, YashKamboj commented
@debo19 can you help me , i can't find why its failing, didn't changed much which may cause this error.

2022-02-03 18:11 UTC, warunicorn19 requested changes

2022-02-03 18:16 UTC, warunicorn19 commented on src/collections/resources/tutorials/contributing-to-meshery-API-swagger-documentation/index.mdx
> +import { ResourcesWrapper } from "../../Resources.style.js";
```suggestion
import { ResourcesWrapper } from "../Resources.style.js";
```

2022-02-03 18:17 UTC, warunicorn19 commented on src/collections/resources/tutorials/contributing-to-meshery-API-swagger-documentation/index.mdx
> +import { ResourcesWrapper } from "../../Resources.style.js";
this stylesheet is right outside the resource folder

2022-02-03 18:40 UTC, debo19 requested changes

2022-02-03 18:40 UTC, debo19 commented on src/sections/Resources/Resources-grid/filters.js
> +                    filter: { fields: { collection: { in: ["blog", "resources", "news", "events", "tutorials"] } }, frontmatter: { published: { eq: true } , resource: { eq: true} }}
```suggestion
                    filter: { fields: { collection: { in: ["blog", "resources", "news", "events"] } }, frontmatter: { published: { eq: true } , resource: { eq: true} }}
```
This won't be required anymore.

2022-02-03 18:40 UTC, debo19 commented on src/sections/Resources/Resources-grid/filters.js
> +                  filter: { fields: { collection: { in: ["blog", "resources", "news", "events", "tutorials"] } }, frontmatter: { published: { eq: true } , resource: { eq: true} }}
```suggestion
                  filter: { fields: { collection: { in: ["blog", "resources", "news", "events"] } }, frontmatter: { published: { eq: true } , resource: { eq: true} }}
```

2022-02-03 18:40 UTC, debo19 commented on gatsby-config.js
> +        path: `${__dirname}/src/collections/resources/tutorials`,
No changes will be needed in the gatsby-config now.

2022-02-03 18:40 UTC, debo19 commented on src/sections/Resources/Resources-grid/DataWrapper.js
> +                    fields: { collection: { in: ["blog", "resources", "news", "events", "tutorials"] } }
```suggestion
                    fields: { collection: { in: ["blog", "resources", "news", "events"] } }
```

2022-02-04 10:57 UTC, YashKamboj commented
@debo19 Do you know why is the build failing can't find the reason, my development server is also failing when opening any resources with related resources.

2022-02-04 10:59 UTC, asubedy commented
@YashKamboj add a `tags` field after category field that should solve the error. Like this:
<img width="154" alt="image" src="https://user-images.githubusercontent.com/51183483/152517681-d274d0cd-0866-469d-b929-6e852cd107fa.png">

2022-02-04 11:17 UTC, debo19 commented
> @YashKamboj add a `tags` field after category field that should solve the error. Like this: <img alt="image" width="154" src="https://user-images.githubusercontent.com/51183483/152517681-d274d0cd-0866-469d-b929-6e852cd107fa.png">

Yes :grimacing: That isn't very obvious right now :sweat: I will go ahead and create a resource template and add a brief note on each of these fields that are required.

2022-02-04 11:29 UTC, YashKamboj commented
@asubedy Thnx it worked .

2022-02-04 11:41 UTC, l5io commented
🚀 Preview for commit 77f29c6a4e1d384abf19d80314f4acc28f16eb58 at: https://61fd1075fe40ddb485ac7174--layer5ng.netlify.app

2022-02-04 11:57 UTC, debo19 requested changes

2022-02-04 11:57 UTC, debo19 commented on src/collections/resources/tutorials/functional-testing-with-cypress-in-meshery-ui/index.mdx
> +title: "Functional Testing with Cypress in Meshery UI"
This is a blog post right - https://layer5.io/blog/meshery/functional-testing-with-cypress-in-meshery-ui
We can remove this from tutorials.

2022-02-04 11:57 UTC, debo19 commented on src/collections/resources/tutorials/introduction-to-all-layer5-repositories/index.mdx
> +        <iframe src="https://docs.google.com/document/d/e/2PACX-1vQEnQ6m6uvAYPFLlBdKQLoB36YKrHh3A7EBSUVfMkSleoDagO4sa2WYg0tDQk51Su6gloAwHUhijO6W/pub?embedded=true"
This doesn't look good inside an `iframe`. Instead, just add a brief note to check out the `Repository Overview` and link to https://layer5.io/community/handbook/repository-overview

2022-02-04 12:05 UTC, debo19 reviewed
Try adding a small heading before each slide or recording. ("Tutorial Slides" "Tutorial Recording")

2022-02-04 17:38 UTC, l5io commented
🚀 Preview for commit 94164485e65df49f15977737463df141f94a1ae3 at: https://61fd641004d7f04e6fa8dffc--layer5ng.netlify.app

2022-02-04 20:09 UTC, warunicorn19 commented
slide deck on the first tutorial is broken

2022-02-05 14:20 UTC, debo19 commented on src/collections/resources/tutorials/introduction-to-all-layer5-repositories/index.mdx
> +        <iframe src="https://docs.google.com/document/d/e/2PACX-1vQEnQ6m6uvAYPFLlBdKQLoB36YKrHh3A7EBSUVfMkSleoDagO4sa2WYg0tDQk51Su6gloAwHUhijO6W/pub?embedded=true"
@YashKamboj After the recording, you can just add a button like we have for any [event](https://layer5.io/community/events/project-office-hours-service-mesh-performance-at-kubecon-na-2021) to say "Check out the Layer5 Repository Overview"

2022-02-05 14:30 UTC, debo19 commented on src/collections/resources/tutorials/tutorial-on-contributing-to-layer5-and-working-with-git.mdx
> +      <h1> Tutorial Slides </h1>
```suggestion
      <h3> Tutorial Slides </h3>
```
`<h3>` will be better here.

2022-02-05 14:34 UTC, debo19 commented on src/collections/resources/tutorials/tutorial-on-contributing-to-layer5-and-working-with-git.mdx
> +      <h1> Tutorial Slides </h1>
Not just this, the rest of the headings

2022-02-05 14:52 UTC, YashKamboj commented
@warunicorn19 working fine for me, can you check again

2022-02-05 17:27 UTC, l5io commented
🚀 Preview for commit 726f22d669b9791817c5b017c78e3c23b423f8fe at: https://61feb31bf95e0155df905517--layer5ng.netlify.app

2022-02-05 17:47 UTC, l5io commented
🚀 Preview for commit 375ccb3b6d6498b24df1b862fbbca6829128c8e0 at: https://61feb804f8236b57b571f06d--layer5ng.netlify.app

2022-02-06 17:14 UTC, debo19 requested changes

2022-02-06 17:14 UTC, debo19 commented on src/collections/resources/tutorials/beginner-guide-to-contributing-to-meshery-and-mesheryctl.mdx
> +author: Navendu Pottekkat
```suggestion
```
We avoid adding authors to resources. Please make this change in the other files as well.

2022-02-06 17:14 UTC, debo19 commented on src/collections/resources/tutorials/introduction-to-meshey-ctl.mdx
> +        <iframe className="iframe" src="https://www.youtube.com/embed/wK7Q-zbJ3gQ&t=3s"
This links seems to be broken for me. Can you check this once?

2022-02-06 17:14 UTC, debo19 commented on src/collections/resources/tutorials/beginner-guide-to-contributing-to-meshery-and-mesheryctl.mdx
> +thumbnail: ../../../assets/images/tutorials/intro-meshery-ctl.png
I think you need to change the thumbnail for this one. You seem to have added two duplicate images for [this](https://61feb804f8236b57b571f06d--layer5ng.netlify.app/resources/service-mesh/beginners-guide-to-contributing-to-meshery-and-mesheryctl) and [Intro to mesheryctl](https://61feb804f8236b57b571f06d--layer5ng.netlify.app/resources/service-mesh/an-introduction-to-mesheryctl)

2022-02-06 17:46 UTC, l5io commented
🚀 Preview for commit bc76432d2b1601ef7f595b7fef349463c345a278 at: https://620008fee12dde4653326457--layer5ng.netlify.app

2022-02-06 18:20 UTC, warunicorn19 commented
@Nikhil-Ladha everytime I try to see the preview I get this.
<img width="1440" alt="Screenshot 2022-02-06 at 1 18 18 PM" src="https://user-images.githubusercontent.com/53532328/152695311-378adbbc-1731-4993-bc74-40021dbe1761.png">
Do you think this might be happening becaue of the `gatsby-robots-txt` ?

2022-02-07 01:46 UTC, Nikhil-Ladha commented
@warunicorn19 possibly. As, I see the robots file js also not what I intended it to be and I think that's because of the way we create previews.
I will send a PR to revert the changes soon.
Though, I am not seeing such message while opening the preview.

2022-02-07 02:34 UTC, leecalcote commented
FWIW: Whether in Safari or Chrome, I don't see these messages either.

2022-02-09 11:09 UTC, Nikhil-Ladha commented
@YashKamboj some conflicts!

2022-02-16 20:14 UTC, debo19 approved these changes
LGTM, thanks @YashKamboj 🙌

2022-02-17 11:33 UTC, leecalcote requested changes
@YashKamboj will you be so kind as to ensure that all slide deck cover images are the same size? They are all coming from the same source: a Google Slide. Let's ensure that the fit to the size of the resources cards precisely and are of the exact same size.

2022-02-28 07:00 UTC, merged