See more is inside the card
layer5io/layer5 pull request #2680
Opened 2022-03-24 17:41 UTC by Akshit42-hue

**Description**

This PR fixes #2679 

**Notes for Reviewers**
Now the see more is inside the card

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-03-24 17:42 UTC, Akshit42-hue commented
@Nikhil-Ladha please do have a look

2022-03-25 13:00 UTC, Akshit42-hue commented
@Abhijay007 @Nikhil-Ladha can you please give me any update

2022-03-25 15:09 UTC, Nikhil-Ladha commented on src/components/Card/Card.style.js
> +        padding: 0rem 2rem;
Make the change in the blog CSS only, and not in the component CSS.

2022-03-26 05:11 UTC, Akshit42-hue commented
@Nikhil-Ladha Please do have a look

2022-03-26 05:22 UTC, l5io commented
🚀 Preview for commit 0d5be154d7ec60bc12fbb98c7e4d64d667050d5d at: https://623ea2255b53867cfc136a1f--layer5ng.netlify.app

2022-03-26 17:13 UTC, Abhijay007 approved these changes
LGTM !! 👍

2022-03-27 12:52 UTC, Akshit42-hue commented
@Abhijay007 @Nikhil-Ladha can you please add **openforce** label

2022-03-27 15:52 UTC, Abhijay007 commented
> @Abhijay007 @Nikhil-Ladha can you please add **openforce** label

done :)

2022-03-28 04:44 UTC, Nikhil-Ladha requested changes
You are still changing the CSS of the component. Please revert that.
And, only update the CSS for the Card component in the blogs code itself.

2022-03-28 06:45 UTC, Akshit42-hue commented
I am sorry but I am not understanding what you are trying to say.Can you please explain more about it @Nikhil-Ladha 
 Only the "Service Mesh Specifications and Why They Matter" card css I want to change. Am I right

2022-03-31 08:15 UTC, Nikhil-Ladha commented
Make the change to the [Blog-grid CSS](https://github.com/layer5io/layer5/blob/master/src/sections/Blog/Blog-grid/blogGrid.style.js) only. So, that other pages which are using the Card component don't get affected by the fixed height change.

2022-03-31 12:10 UTC, Akshit42-hue commented
Thanks for clarifying @Nikhil-Ladha

2022-03-31 12:13 UTC, Akshit42-hue commented
Please do have a look @Nikhil-Ladha

2022-03-31 12:26 UTC, l5io commented
🚀 Preview for commit 9e8d7c12fad06073333f3a5499af057180d632f0 at: https://62459d43f065fd520cd4a97b--layer5ng.netlify.app

2022-03-31 12:40 UTC, Nikhil-Ladha commented on src/sections/Blog/Blog-grid/blogGrid.style.js
> +
Move this under the below `media` tag for `max-width: 992px`, above that it is not required.

2022-03-31 14:15 UTC, Akshit42-hue commented
Required changes have been done @Nikhil-Ladha

2022-03-31 16:59 UTC, Nikhil-Ladha approved these changes

2022-03-31 16:59 UTC, merged