Add's validation so that at least one account is provided in meshmap form.
layer5io/layer5 pull request #2719
Opened 2022-04-16 11:18 UTC by SAEb-ai

Signed-off-by: Md Shahbaz Alam <shahbazalam75508@gmail.com>

**Description**

This PR fixes #2689.

**Notes for Reviewers**

- Add's a validation so that at least one account information is provided in meshmap form before the actual submission.
- Video Illustration:
  

https://user-images.githubusercontent.com/69013647/163672942-55746e9b-ffb5-4f4b-a1ad-47d456d403d2.mp4

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

2022-04-16 11:24 UTC, SAEb-ai commented
@warunicorn19 @leecalcote Please take a look. Thanks!!

2022-04-16 15:32 UTC, l5io commented
🚀 Preview for commit 1f4fc4d0134325e02a4493ac6499848db9672218 at: https://625ae0f61f553d23f390b9ce--layer5ng.netlify.app

2022-04-16 15:59 UTC, warunicorn19 requested changes
Okay I see a small problem with this, on the first try if someone doesn't enter any of the accounts, all the fields of the form disappear, ideally the data of the form should be there with just the error message.

2022-04-18 11:13 UTC, debo19 commented
@SAEb-ai Let's discuss this in the Websites call today, if you're available?

2022-04-18 14:22 UTC, leecalcote commented
@SAEb-ai did we get this one figured out?

2022-04-27 16:09 UTC, leecalcote commented
Yo, @SAEb-ai, where are we at on this one?

2022-04-29 08:04 UTC, leecalcote commented
@warunicorn19 will you take over this abandoned PR?

2022-04-29 08:05 UTC, warunicorn19 commented
Yup, I'll take a look @leecalcote

2022-04-29 08:25 UTC, SAEb-ai commented
@leecalcote Sorry I was giving my university exams. That's why I was a bit inactive on Github. Now it's over. I wish to address the requested changes further. Can I please do that?

2022-04-29 08:37 UTC, leecalcote commented
Thank you, sir.

2022-04-29 08:38 UTC, leecalcote commented
@SAEb-ai, yes, if you can complete in the next 12 hours.

2022-05-02 07:17 UTC, debo19 commented
@SAEb-ai updates on this?

2022-05-02 10:20 UTC, SAEb-ai commented on src/sections/Meshmap/index.js
> +                        org.value=values.org;
Can you please give some suggestions how I can change the role value beacause it's saying undefined when I am changing it in the same manner as above?

2022-05-02 10:23 UTC, SAEb-ai commented
@warunicorn19 @leecalcote @debo19 Can you please take a look at my above mentioned https://github.com/layer5io/layer5/pull/2719#pullrequestreview-958915420? Thanks!!

2022-05-02 12:44 UTC, l5io commented
🚀 Preview for commit e4df8f8c5f0f350e3ab6c400a56893d67027c924 at: https://626fd14da152cf2dba375f1e--layer5ng.netlify.app

2022-05-06 05:52 UTC, SAEb-ai commented on src/sections/Meshmap/index.js
> +                        org.value=values.org;
Resolved this by tracking the initialvalue of role.

2022-05-06 05:55 UTC, SAEb-ai commented
@warunicorn19 @leecalcote @debo19 I have resolved [this issue](https://github.com/layer5io/layer5/pull/2719#discussion_r862737978) now. Can please take a look over the PR now? Thanks!!

2022-05-06 06:20 UTC, l5io commented
🚀 Preview for commit 1744a9497a6edef3e7b64fc4b903a7f2db8d6edc at: https://6274bdac6cb5ef2e59ade776--layer5ng.netlify.app

2022-05-06 06:55 UTC, Chadha93 requested changes
@SAEb-ai Thank you for updating the PR, it works well, just a minor change suggested to update then we are good to merge this.

2022-05-06 06:55 UTC, Chadha93 commented on src/sections/Meshmap/index.js
> +                        {validateAccounts && <p style={{margin:"0px",color:"red"}}>{errorAccounts}</p>}
@SAEb-ai please use className to avoid inline styling.

2022-05-06 11:57 UTC, warunicorn19 approved these changes
Looking good, we can take care of the inline styling later.

2022-05-06 11:57 UTC, merged

2022-05-11 06:55 UTC, Nikhil-Ladha commented
@warunicorn19 seems like this is needed for the docker-extension form too. Are you planning to take it up?

2022-05-11 07:37 UTC, SAEb-ai commented
I can take that @Nikhil-Ladha.Thanks!!

2022-05-11 07:38 UTC, Nikhil-Ladha commented
> I can take that @Nikhil-Ladha .Thanks!!

Please try to send it by today.

2022-05-11 09:34 UTC, leecalcote commented
Thanks, @SAEb-ai. Many people interested in the Docker Extension given the announcement at DockerCon.

2022-05-11 10:17 UTC, SAEb-ai commented
@leecalcote I am working on it and will try to send a PR in a hour!!

2022-05-11 11:15 UTC, SAEb-ai commented
Do I also have to implement the roles section @Nikhil-Ladha @leecalcote?

2022-05-11 11:32 UTC, Nikhil-Ladha commented
> Do I also have to implement the roles section @Nikhil-Ladha @leecalcote?

Probably, yes.....but waiting for Lee's confirmation.
Considering the form initially never had the account/roles field in them

2022-05-11 11:38 UTC, Nikhil-Ladha commented
Hey @SAEb-ai while testing, can you please comment out the hook and just use console.log?