Added meet-up caption
layer5io/layer5 pull request #2736
Opened 2022-04-28 16:49 UTC by St80ene

Signed-off-by: etiene <etienejames5@gmail.com>

**Description**

This PR fixes #2734

**Notes for Reviewers**
- Added caption to Open Source Community Meetup, March 2022 picture
### Screenshot
![Screenshot from 2022-04-28 17-35-29](https://user-images.githubusercontent.com/51080127/165803495-32865194-2198-4f11-88ef-ac5ff80bf1c4.png)

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-04-28 16:51 UTC, leecalcote commented
Thank you, @St80ene

2022-04-28 16:52 UTC, leecalcote commented
Is the site building and running for you locally? The build preview failed.

2022-04-28 16:54 UTC, St80ene commented
It required installing a package called "react-is" during the development.
I removed it before pushing because it was already a part of the packages.
I'll have to add it back. I wanted to avoid having conflicts.

2022-04-28 16:57 UTC, Nikhil-Ladha requested changes

2022-04-28 16:57 UTC, Nikhil-Ladha commented on src/sections/Company/About/index.js
> +                  <p className="meetup-caption">Layer5 community members at Open Source Africa Community conference, March 2022.</p>
Insteead of `p` tga use `figcaption` and wrap the complete `img` and `figcaption` within a `figure`

2022-05-02 13:26 UTC, Nikhil-Ladha requested changes
The extra package is redundant and not required.
Also, please undo the changes to the file which are not related to the issue.

2022-05-05 21:05 UTC, leecalcote commented
Merge conflicts...

2022-05-05 21:05 UTC, leecalcote commented
Gents, allow me to collaborate here and get this over the hump....

2022-05-06 12:50 UTC, St80ene commented
No problem. I'll do that. I've been stuck on that same issue for some time now.
Thanks

2022-05-06 12:50 UTC, closed without merging