[Blog] ServiceMeshCon 2022 talk with Intel - MeshMark
layer5io/layer5 pull request #2792
Opened 2022-05-14 21:11 UTC by Chadha93

Signed-off-by: Gaurav Chadha <gauravchadha1676@gmail.com>
**Description**
ServiceMeshCon 2022 talk with Intel - MeshMark

This PR fixes #

**Notes for Reviewers**
MERGE AFTER 17 MAY Central Time only
This blog will boost SEO :)

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-05-14 21:24 UTC, l5io commented
🚀 Preview for commit 51be01b10bc501cb6e060bcbb7afcbe21629b036 at: https://62801d7f523926396bb6d5ac--layer5ng.netlify.app

2022-05-14 22:25 UTC, leecalcote requested changes

2022-05-14 22:25 UTC, leecalcote commented on src/collections/blog/2022/2022-05-14-service-meshcon-talk-intel/index.mdx
> +Let's take an example workload a console application, load it into the visual designer, take a look at the service splitting functionality of console and note in this case we're assigning a weight of
```suggestion
Let's take an example workload a  Consul application, load it into the visual designer, take a look at the service splitting functionality of console and note in this case we're assigning a weight of three when we can change that to four to derive its mesh Mark which is a mesh utilization efficiency calculation of the efficiency by which that network function is being performed.
```

2022-05-14 22:25 UTC, leecalcote commented on src/collections/blog/2022/2022-05-14-service-meshcon-talk-intel/index.mdx
> +<h3>Lee demonstrates MeshMap with an example of console application</h3>
```suggestion
<h3>Lee demonstrates MeshMap with an example Consul application</h3>
```

2022-05-15 03:43 UTC, l5io commented
🚀 Preview for commit 3c86b46202ce74bcb2718f848cb461c8696305a5 at: https://628076904adca66839e72f38--layer5ng.netlify.app

2022-05-15 06:07 UTC, leecalcote commented on src/collections/blog/2022/2022-05-14-service-meshcon-talk-intel/index.mdx
> +title: "MeshMark: Service Mesh value measurement"
```suggestion
title: "MeshMark: Cloud Native Value Measurement"
```

2022-05-15 06:07 UTC, leecalcote commented on src/collections/blog/2022/2022-05-14-service-meshcon-talk-intel/index.mdx
> +description: "ServiceMeshCon 2022 talk with Intel"
```suggestion
description: "An open index for measuring performance of cloud native infrastructure in context of the value provided to your business."
```

2022-05-15 06:20 UTC, l5io commented
🚀 Preview for commit 5f8fa362ceb7f976bc89f3ddee0d110f9899812d at: https://62809b0552fefc7c219e5917--layer5ng.netlify.app

2022-05-16 13:45 UTC, leecalcote commented on src/collections/blog/2022/2022-05-14-service-meshcon-talk-intel/index.mdx
> +category: "MeshMark"
```suggestion
category: "Service Mesh Performance"
```

2022-05-16 20:51 UTC, leecalcote commented on src/collections/blog/2022/2022-05-14-service-meshcon-talk-intel/index.mdx
> +import slidesTAG from "../../../events/kubecon-china-2021/cncf-tag-network-and-service-mesh-working-group-kubecon-china-2021-lee-calcote-ken-owens.pdf";
Thanks

2022-05-16 20:52 UTC, leecalcote commented
Make sure that MeshMark is always one word. It shows as two words in a few places.

2022-05-16 22:22 UTC, merged