Add event meshmates lightning talk
layer5io/layer5 pull request #2827
Opened 2022-05-24 23:00 UTC by shivaylamba

Signed-off-by: shivay <shivaylamba@gmail.com>

**Description**

This PR fixes #2791 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-05-24 23:13 UTC, l5io commented
🚀 Preview for commit 5dc9d6056997c26915cefff2a096751127a95a37 at: https://628d65f4f9906a1d84444dcb--layer5ng.netlify.app

2022-05-25 10:11 UTC, shivaylamba commented
@kayceeDev actually the reason I added 24th was because my talk is on 24th. Are we supposed to add the event start date?

2022-05-25 10:21 UTC, kayceeDev commented
> @kayceeDev actually the reason I added 24th was because my talk is on 24th. Are we supposed to add the event start date?

Thanks for the clarity. Looks good to me

2022-05-25 10:22 UTC, kayceeDev approved these changes

2022-05-25 10:23 UTC, kayceeDev approved these changes

2022-05-25 20:46 UTC, leecalcote requested changes
When we have more than one talk at the conference, it's ideal that we use the conference start date. In this case, it's probably not worth changing. What is worth changing is the image used. Ideally, it doesn't have dates or hashtags overlaid, but is just the conference logo (with colored background).

2022-05-25 20:51 UTC, leecalcote requested changes

2022-05-25 20:51 UTC, leecalcote commented on src/collections/events/ossna-2022/index.mdx
> +<h3>Lightning Talk: MeshMates : A New Way of Expanding Open Source Community Mentorship</h3>
```suggestion
<h3>MeshMates: A New Way of Expanding Open Source Community Mentorship</h3>
```

2022-05-25 20:51 UTC, leecalcote commented on src/collections/events/ossna-2022/index.mdx
> +Therefore Layer5 ( part of CNCF ) introduced a program called Meshmates. MeshMates who are members part of the Layer5 community, provide one to one mentorship to new joiners in the community, from he
```suggestion
Therefore Layer5 ( a CNCF member company) introduced a program called <Link to="/community/meshmates">Meshmates</Link>. MeshMates who are members part of the Layer5 community, provide one to one mentorship to new joiners in the community, from helping them identifying areas of projects to engage within, working groups to join, and in helping community members grow in their open source and cloud native knowledge.
```

2022-05-25 20:51 UTC, leecalcote commented on src/collections/events/ossna-2022/index.mdx
> +Therefore Layer5 ( part of CNCF ) introduced a program called Meshmates. MeshMates who are members part of the Layer5 community, provide one to one mentorship to new joiners in the community, from he
This will require the import of `Link`.

2022-05-26 08:45 UTC, shivaylamba commented
I have resolved the comments @leecalcote, but I can't find any better image as compared to the current one for the conference. 
This is another image, but not sure if it is the best one
![OSS-NA-22-HeroBanner-v3-B-purple](https://user-images.githubusercontent.com/19529592/170452774-a74b998b-7697-47e4-87ba-a1029eeb91d6.jpeg)
Here;s another one: https://blogs.vmware.com/opensource/files/2022/05/open_source_summit-576x324.png

Please let me know which is the best one which could choose.

2022-05-26 08:56 UTC, l5io commented
🚀 Preview for commit 0ae058f9cb09bd209ac004243d60e4ac4783a471 at: https://628f4019b2a6183e8d12bb94--layer5ng.netlify.app

2022-05-26 22:16 UTC, leecalcote commented
@shivaylamba, I've made one for you. Here you go -
![oss-na-2022](https://user-images.githubusercontent.com/7570704/170588683-3c85b582-11f1-4d3f-9ba4-91d6ac43ead0.png)

2022-05-26 22:23 UTC, shivaylamba commented
Thank you very much @leecalcote I have updated the image

2022-05-26 22:24 UTC, leecalcote approved these changes
💥 Looking good!

2022-05-26 22:24 UTC, merged