[Event] - Added Docker Community Meetup Event - Bengaluru
layer5io/layer5 pull request #2894
Opened 2022-06-09 16:59 UTC by adithyaakrishna

Signed-off-by: Adithya Krishna <adikrish@redhat.com>

**Description**

This PR adds a new talk and event regarding the upcoming in-person docker developer community meetup at Bengaluru

Meetup Link: https://www.meetup.com/Docker-Bangalore/events/285342797/

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-06-09 17:19 UTC, l5io commented
🚀 Preview for commit 4c1e2d6c292b4d95e52284756f916e9a8eb24a9f at: https://62a22b5e0fe16c105302f1f5--layer5.netlify.app

2022-06-09 17:21 UTC, leecalcote commented
@Nikhil-Ladha regarding the large file size of this image, do we still have an image bot enabled on this repo? I don't think so, since it isn't always desirable. 

@adithyaakrishna, can you use .webp or .jpg (given that is is largely a photo) to reduce from ~9MB to ~350k?

2022-06-09 17:21 UTC, leecalcote requested changes
Contents look good. Image is pending file size reduction.

2022-06-09 17:38 UTC, Nikhil-Ladha commented
> @Nikhil-Ladha regarding the large file size of this image, do we still have an image bot enabled on this repo? I don't think so, since it isn't always desirable.

Seems like access is revoked. Shall I re-configure it to allow image optimizations?

2022-06-09 17:58 UTC, leecalcote commented
@Nikhil-Ladha, no thank you. Often it trades off minimization for quality past the limit that I'm willing to tolerate (so much that visitors of the site will surely notice the poor quality).

2022-06-09 18:14 UTC, adithyaakrishna commented
> @Nikhil-Ladha regarding the large file size of this image, do we still have an image bot enabled on this repo? I don't think so, since it isn't always desirable.
> 
> @adithyaakrishna, can you use .webp or .jpg (given that is is largely a photo) to reduce from ~9MB to ~350k?

Done Dona Done ✅

2022-06-09 18:20 UTC, l5io commented
🚀 Preview for commit 5c94032f2938cdaff43aced546f132502d82945b at: https://62a239c67438661c84568cfb--layer5.netlify.app

2022-06-09 18:31 UTC, Chadha93 commented
@adithyaakrishna blog is not visible in the preview, is it due to change in image file type?

2022-06-09 18:44 UTC, Chadha93 commented
Oops, I missed it, 😅 Yes yes it's an event. Thanks @adithyaakrishna

2022-06-09 18:46 UTC, adithyaakrishna commented
There's a small change 😶 

@leecalcote Should this be of a type Meetup or an Event?

2022-06-09 20:16 UTC, leecalcote commented
> There's a small change 😶
> 
> @leecalcote Should this be of a type Meetup or an Event?

It's been a while, but let's go with a Meetup, please.

2022-06-10 11:42 UTC, l5io commented
🚀 Preview for commit d13aeea1bb9d531ca46f98013b6db56eda46714d at: https://62a32e08ac4cbc2c58d49926--layer5.netlify.app

2022-06-10 14:57 UTC, leecalcote commented on src/collections/events/docker-developer-community-meetup-2022/index.mdx
> +    <Link to="https://linkedin.com/in/uravgkarthik">Karthik Ravishankar</Link>
General note: `<Link>` is for internal URLs only. `<a>` is used for external URLs.
Specific rule: Only links to community member profiles are allowed here. It'd be great to have a link to Karthik's social profile. It's something that he'll need to earn in the community first, though.

2022-06-10 14:58 UTC, leecalcote commented on src/collections/events/docker-developer-community-meetup-2022/index.mdx
> +    <Link to="https://linkedin.com/in/uravgkarthik">Karthik Ravishankar</Link>
```suggestion
  <li>
```

2022-06-10 15:01 UTC, leecalcote commented on src/collections/events/docker-developer-community-meetup-2022/index.mdx
> +product: Meshery Extensions
@debo19 is this a resource category?

2022-06-10 15:02 UTC, leecalcote commented on src/collections/events/docker-developer-community-meetup-2022/index.mdx
> +  we share on the latest Meshery Docker Extension and how you can manage your cloud native applications using it.
```suggestion
  we share on the Meshery Docker Extension and how you can manage your cloud native applications using it.
```

2022-06-10 15:03 UTC, leecalcote commented on src/collections/events/docker-developer-community-meetup-2022/index.mdx
> +</h2>
```suggestion
<h2>Composing Cloud Native Infrastructure with Docker Desktop and Meshery</h2>
```

Removing duplicate link.

2022-06-10 15:04 UTC, leecalcote commented on src/collections/events/docker-developer-community-meetup-2022/index.mdx
> +<br />
```suggestion
```

Removing unnecessary line break.

2022-06-10 15:04 UTC, leecalcote commented on src/collections/events/docker-developer-community-meetup-2022/index.mdx
> +<br />
```suggestion
```

2022-06-10 15:05 UTC, leecalcote commented on src/collections/events/docker-developer-community-meetup-2022/index.mdx
> +This talk can help the attendees to improve upon their K8s or docker deployments as well as help them in managing different service meshes simultaneously. I have a pretty basic knowledge of cloud-nat
```suggestion
This talk can help the attendees to improve upon their K8s or Docker deployments as well as help them in managing different service meshes simultaneously. I have a pretty basic knowledge of cloud native stuff having worked with Kubernetes, Docker, Helm, and using some of the service meshes, trying them out for different stuff or applications. I have been using Docker Desktop for the past year and a half. I’m also a maintainer of Meshery and have contributed to several other open source projects.
```

2022-06-10 15:06 UTC, leecalcote commented
Great job on reducing the image file size. 👍

2022-06-10 15:07 UTC, leecalcote commented on src/collections/events/docker-developer-community-meetup-2022/index.mdx
> +  <li>
```suggestion
  <li>Karthik Ravishankar
```

2022-06-10 15:09 UTC, leecalcote approved these changes
Good to go other than the question of `product` category. // @debo19

2022-06-10 17:49 UTC, merged