Added Executive Bio to member profile
layer5io/layer5 pull request #2931
Opened 2022-06-25 21:10 UTC by debo19

Signed-off-by: Debopriya Bhattacharjee <debopriyabhattacharjee@Debopriyas-MacBook-Air.local>

**Description**

https://user-images.githubusercontent.com/85789734/175790580-29a3ead4-79c2-4bb6-8b1c-b7ec8f1d0f7a.mov

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-06-25 21:39 UTC, leecalcote commented
@debo19 the recorded demo looks great. If the activated modal can be referenced by URL, I will put the URL to use. Can the photo in the modal be a different, second photo?

2022-06-25 21:46 UTC, debo19 commented
@leecalcote Yes, the photo can be different. About the url, I'll try to figure it out.

2022-07-01 23:54 UTC, leecalcote commented on src/collections/members/lee-calcote/index.mdx
> +company: Layer5
I have added this.

2022-07-01 23:55 UTC, leecalcote commented on src/collections/members/lee-calcote/index.mdx
> +company: Layer5
Please use this second photo in the alternative bio

2022-07-02 22:54 UTC, debo19 commented
@Nikhil-Ladha @warunicorn19 do you know why the build is failing?

2022-07-03 07:15 UTC, Nikhil-Ladha commented
Is it getting built locally?

2022-07-03 09:13 UTC, warunicorn19 requested changes

2022-07-03 09:13 UTC, warunicorn19 commented on src/sections/app.style.js
> +            box-shadow: 0px 0px 8px 1px rgba(0,179,159,1);
Could you please not hard code the color here.

2022-07-03 09:13 UTC, warunicorn19 commented on src/sections/Community/Member-single/memberSingle.style.js
> +                            color: #00b39f;
Please use a color from the theme.

2022-07-03 12:56 UTC, debo19 commented
> Is it getting built locally?

Yup it does

2022-07-03 12:59 UTC, Nikhil-Ladha commented
> > Is it getting built locally?
> 
> Yup it does

I am asking about `make build` not `make site`.

2022-07-03 13:21 UTC, debo19 commented
> I am asking about `make build` not `make site`.
Yeah both of them are working fine locally.

2022-07-03 18:12 UTC, Nikhil-Ladha commented
> > I am asking about `make build` not `make site`.
> 
> Yeah both of them are working fine locally.

Ok
In that case, I think the `react-modal` library is making the bundle heavy and leading to a memory crash. Can you try making a commit with the `Modal` component commented out, and see if that allows the build process or not?

2022-07-05 21:16 UTC, leecalcote commented
If the individually published page is too much of a pain in the rump, we can forego it for now, until the exec team is larger.

2022-07-19 17:40 UTC, merged