Add VMware as partner and link it to logo on homepage
layer5io/layer5 pull request #2944
Opened 2022-06-28 21:20 UTC by Santosh1176

Signed-off-by: Santosh Kaluskar <dtshbl@gmail.com>

**Description**
Adds VMware as a partner and link it to the logo on the homepage

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-06-29 00:25 UTC, leecalcote commented
@Santosh1176 we've got to do something about your linter/formatter. The overwhelming majority of the changes here are not necessarily desired.

2022-06-30 05:07 UTC, Nikhil-Ladha requested changes

2022-06-30 05:07 UTC, Nikhil-Ladha commented on src/sections/Home/Partners-home/partners-home-data.js
> +    innerDivStyle: "partner__block__inner",
We already have VMware added just above this, no need to add it again.
Just update the `imageRoute` above to point to `/partners#VMware`

2022-06-30 09:26 UTC, l5io commented
🚀 Preview for commit 04d6db2df8ab586ea367fdcac83e994dd115e80a at: https://62bd6bd4c7cb036a196dbec8--layer5.netlify.app

2022-07-01 22:19 UTC, leecalcote commented
Merge conflicts, @Santosh1176

2022-07-02 06:18 UTC, l5io commented
🚀 Preview for commit 2285f3acde2db605b585c62368a964f9968d4c6d at: https://62bfe2c2207c5202a6aaae79--layer5.netlify.app

2022-07-04 19:39 UTC, leecalcote approved these changes
LGTM

2022-07-04 19:41 UTC, Nikhil-Ladha approved these changes

2022-07-04 19:41 UTC, merged

2022-07-05 03:18 UTC, Santosh1176 commented
Thank you!