[MeshMap] Increase internal links
layer5io/layer5 pull request #2956
Opened 2022-07-02 22:43 UTC by debo19

Signed-off-by: Debopriya Bhattacharjee <debopriyabhattacharjee@Debopriyas-MacBook-Air.local>

**Description**
- Used the new Rotational CTA for `Resources` and `Events`
 - Added CTA on `News` sidebar

<img width="1101" alt="Screenshot 2022-07-03 at 4 11 27 AM" src="https://user-images.githubusercontent.com/85789734/177018020-3e50e410-fd5a-4969-a236-c166bd29432a.png">
<img width="224" alt="Screenshot 2022-07-03 at 4 10 15 AM" src="https://user-images.githubusercontent.com/85789734/177018010-d62a550d-5651-42df-ae8a-462d29e866c6.png">

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-07-02 22:56 UTC, l5io commented
🚀 Preview for commit aacca231ccb36ba869be202f67a7644f66ce9eaa at: https://62c0cc9b9c3edd18d87a715a--layer5.netlify.app

2022-07-04 12:45 UTC, Nikhil-Ladha commented on src/sections/Company/News-single/Sidebar.js
> +      </Link>
Or maybe, `CTA_ImageOnly` ?

2022-07-04 13:36 UTC, Nikhil-Ladha requested changes
Considering the image of MeshMap, I think it is better to opt for `opacity: 0.5` in `CTA_FullWidth` and `CTA_Bottom` for responsive views, instead of `filter: brightness(0.5)`. Can you please update that (both the places)?

Also, the content seems to be crossing the limits and moving beyond the boundaries! :p
What I mean to say is, after 992px the text is peeking outside the CTA box, that needs to be fixed as well.

Rest looks good.

2022-07-04 13:42 UTC, Nikhil-Ladha commented on src/components/Call-To-Actions/CTA_Bottom/index.js
> +        text-align: left;
Do we really need this?

2022-07-04 13:45 UTC, Nikhil-Ladha commented on src/components/Call-To-Actions/CTA_Bottom/index.js
>          a {
`a` needs a `text-align: center` as well.

2022-07-04 13:54 UTC, Nikhil-Ladha commented
Having this CTA in action brought about a lot of small CSS issues, which got ignored earlier.
Sorry for the extra trouble @debo19 , hopefully you won't mid taking care of it :)

2022-07-05 21:15 UTC, leecalcote commented
You get a CTA! You get a CTA! We all get CTAs!

2022-07-07 22:58 UTC, leecalcote commented
The CTA in /resources is looking pretty good. I could be missing something (like the need for an increased amount of padding within the border of the CTA), but think this is good to go.

2022-07-11 07:06 UTC, l5io commented
🚀 Preview for commit e18569d34733e1fb1ecdeed2c267022d2561f928 at: https://62cbcb7ded70286127d428ce--layer5.netlify.app

2022-07-12 08:21 UTC, Nikhil-Ladha commented on src/components/Call-To-Actions/CTA_Bottom/index.js
> +          height: 16rem;
add `align-self: center` here.

2022-07-12 08:23 UTC, Nikhil-Ladha commented on src/components/Call-To-Actions/CTA_Bottom/index.js
> +          height: 16rem;
Same applies for `CTA_Fullwidth`

2022-07-13 20:19 UTC, debo19 commented
@Nikhil-Ladha With different images, the styles for `CTA_Bottom` and `CTA_FullWidth` are not completely in accordance. While I've used the icon with a transparent background in the `CTA_Bottom` here, it required padding and the other changes you suggested. However, if we use one like the default `community` image, your previous styles work well. Should we look into the styles for `CTA_FullWidth` when we actually put it to use? 

<img width="518" alt="Screenshot 2022-07-14 at 1 36 10 AM" src="https://user-images.githubusercontent.com/85789734/178825991-9ed7ffee-22b7-4b7a-8338-f5882969b592.png">

2022-07-15 18:29 UTC, Nikhil-Ladha commented
> @Nikhil-Ladha With different images, the styles for `CTA_Bottom` and `CTA_FullWidth` are not completely in accordance. While I've used the icon with a transparent background in the `CTA_Bottom` here, it required padding and the other changes you suggested. However, if we use one like the default `community` image, your previous styles work well. Should we look into the styles for `CTA_FullWidth` when we actually put it to use?
> 
> <img alt="Screenshot 2022-07-14 at 1 36 10 AM" width="518" src="https://user-images.githubusercontent.com/85789734/178825991-9ed7ffee-22b7-4b7a-8338-f5882969b592.png">

Sure, we can handle the other one later on.

2022-07-15 18:34 UTC, l5io commented
🚀 Preview for commit 299548575ba250c70d2f98a7d240f7a45ac7d2a7 at: https://62d1b2bf0eebee5ff09d4624--layer5.netlify.app

2022-07-15 19:02 UTC, debo19 commented
Added one CTA to blogs too.

2022-07-16 07:11 UTC, Nikhil-Ladha approved these changes
Looking good!

2022-07-16 07:12 UTC, merged