Performance Improvement in the Handbook section
layer5io/layer5 pull request #3070
Opened 2022-08-12 15:03 UTC by legendarykamal

**Description**

This PR fixes #3014 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-08-12 15:18 UTC, l5io commented
🚀 Preview for commit db4d4d652a06382a01e6eda24be7f368d16483b3 at: https://62f66ef0a954bc032cc98811--layer5.netlify.app

2022-08-12 15:29 UTC, debo19 requested changes

2022-08-12 15:29 UTC, debo19 commented on src/sections/Community/Handbook/projects.js
> +              <Link to="/community/meshmates"><img className="project-description-icon" src={meshmateicon} alt="meshmateicon" /> MeshMates </Link>, catch-all org, “home base”.
```suggestion
              <Link to="/community/meshmates"><img className="project-description-icon" src={meshmateicon} alt="MeshMate icon" /> MeshMates </Link>, catch-all org, “home base”.
```

2022-08-12 15:29 UTC, debo19 commented on src/sections/Community/Handbook/projects.js
> +              <img className="project-description-icon" src={hawkIcon} alt="hawkIcon" /> , community with{" "}
```suggestion
              <img className="project-description-icon" src={hawkIcon} alt="Nighthawk Icon" /> , community with{" "}
```

2022-08-12 15:29 UTC, debo19 commented on src/sections/Community/Handbook/projects.js
> +              <img className="project-description-icon" src={mesheryoperatoricon} alt="mesheryoperatoricon" /> and MeshSync{" "}
```suggestion
              <img className="project-description-icon" src={mesheryoperatoricon} alt="Meshery Operator Icon" /> and MeshSync{" "}
```

2022-08-12 15:29 UTC, debo19 commented on src/sections/Community/Handbook/projects.js
> +              <img className="project-description-icon" src={mesherysyncicon} alt="mesherysyncicon" />
```suggestion
              <img className="project-description-icon" src={mesherysyncicon} alt="MeshSync icon" />
```

2022-08-12 15:29 UTC, debo19 commented on src/sections/Community/Handbook/repository.js
> +                              <img className="site-icon inline" src={image} />&nbsp;{project} alt="project" </td>
```suggestion
                              <img className="site-icon inline" alt="project" src={image} />&nbsp;{project} </td>
```

2022-08-13 11:47 UTC, legendarykamal commented on src/sections/Community/Handbook/repository.js
> +                              <img className="site-icon inline" src={image} />&nbsp;{project} alt="project" </td>
resolved :+1:

2022-08-13 12:05 UTC, l5io commented
🚀 Preview for commit b6739159a6eccdaab9bb7d7cde10ea1a2e1e8876 at: https://62f793356b267d187a98d46f--layer5.netlify.app

2022-08-22 09:05 UTC, l5io commented
🚀 Preview for commit e694a43ca6e8cd7d2261c9e79e27e434cc62f04a at: https://6303461af0b2c9445f040bab--layer5.netlify.app

2022-08-23 12:29 UTC, debo19 reviewed
<img width="1223" alt="Screenshot 2022-08-23 at 5 59 06 PM" src="https://user-images.githubusercontent.com/85789734/186158174-cb856f89-15b3-439a-b9fe-984241ec2f71.png">
Please make this image full width.

2022-08-23 15:30 UTC, legendarykamal commented
@debo19  done! I have alligned it full space considering the code images above it.
![image](https://user-images.githubusercontent.com/95926324/186199380-47a318c0-d96a-401f-bcc5-cf5d3b1295d0.png)

2022-08-31 06:34 UTC, legendarykamal commented
@debo19  changes pushed :100:

2022-08-31 06:47 UTC, l5io commented
🚀 Preview for commit c1b35fbf18c3e257d7beb565d22812f89266e1a1 at: https://630f0380f4a0b02e19e0189c--layer5.netlify.app

2022-09-01 14:39 UTC, merged