Added cards on the Integration Collection page
layer5io/layer5 pull request #3090
Opened 2022-08-18 19:30 UTC by sahilsuman933

Signed-off-by: Sahil Suman <sahilsuman933@gmail.com>

**Description**
- Added cards on the integration collection page
This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-08-18 19:45 UTC, l5io commented
🚀 Preview for commit e3863ad7bbb80556651ca2fba18490b8befaeb29 at: https://62fe967dbd8b8f11b3ce1af0--layer5.netlify.app

2022-08-18 20:20 UTC, l5io commented
🚀 Preview for commit 47a79181595678e2c8b35eb1f008543b8de4eed3 at: https://62fe9eb662b8a5006b583905--layer5.netlify.app

2022-08-19 05:24 UTC, Nikhil-Ladha reviewed
Can you please update the `overflow-y: scroll` to `overflow-y: hidden` on the `ConactFormModal` component?

2022-08-19 05:25 UTC, Nikhil-Ladha commented
Also, I think the whole card should be clickable, else just having that border transition on-hover could be misleading to the user 🤔 
Thoughts @leecalcote @debo19

2022-08-19 05:55 UTC, sahilsuman933 commented
@Nikhil-Ladha Done.

2022-08-19 06:03 UTC, l5io commented
🚀 Preview for commit f51297092f78e5caf6097cf86fb9f6e9ad1b6089 at: https://62ff27295cd704474153632b--layer5.netlify.app

2022-08-19 13:34 UTC, l5io commented
🚀 Preview for commit 9c0d07e65cbf9d29a93a12c28632f5aaebc1f901 at: https://62ff90e1e40e660ac7360782--layer5.netlify.app

2022-08-19 15:06 UTC, leecalcote requested changes
Regarding the two graphics used in the cards: we never want to use the icons from that stock flat icon site - I forget the name of it - but these are too generic, too overused, too cheap, etc.

2022-08-19 15:08 UTC, leecalcote commented
> @Nikhil-Ladha Done.

The cards are still not clickable. Please use 1px border on hover (not 5px).

2022-08-19 15:10 UTC, leecalcote commented
The expanding text animation for the main description of the integration is nice. Regarding "See Documentation -->", it's nice to have the arrow animate on hover. It is undesirable to have "See Documentation -->" animate on page load.


<img width="532" alt="Screen Shot 2022-08-19 at 10 07 58 AM" src="https://user-images.githubusercontent.com/7570704/185649735-20255cac-ecf3-4c08-b53c-53f6a83860b2.png">

2022-08-19 16:25 UTC, sahilsuman933 commented
@leecalcote card is not clickable cause we have yet to decide whether the whole card should be clickable or only the button. I think it would be better to remove the animation on the card and directly apply the border cause it doesn't make sense to have a clickable card here.

Also, when we finalize the SVG icons for these cards, I will update that.

2022-08-19 16:27 UTC, leecalcote commented
@sahilsuman933 that's fine: only the button is clickable and the border will be reduced and persistently displayed. That'll work. We're still not linking to the integrations page publicly. Push, push, go, go.

2022-08-19 17:35 UTC, Nikhil-Ladha commented on src/sections/Meshery/Meshery-integrations/Individual-Integrations/individual-integrations.style.js
> +					}
```suggestion
					transition: padding 0.5s ease;	
                                }
```

2022-08-19 17:36 UTC, Nikhil-Ladha commented on src/sections/Meshery/Meshery-integrations/Individual-Integrations/index.js
> +      <section className="herosection">``
```suggestion
      <section className="herosection">
```

2022-08-19 17:52 UTC, l5io commented
🚀 Preview for commit 5a116f70d0f2fca8d6f3a290172b69faed3378c8 at: https://62ffcd55139e411886e5224b--layer5.netlify.app

2022-08-19 18:38 UTC, l5io commented
🚀 Preview for commit f3306885718806e6c380302a3d6f16f7eeebecfb at: https://62ffd82d44ba2e2042d4ff00--layer5.netlify.app

2022-08-19 18:44 UTC, leecalcote commented on src/sections/Meshery/Meshery-integrations/Card.js
> +          url="#"
```suggestion
          url="https://docs.meshery.io/extensibility"
```

2022-08-19 18:48 UTC, leecalcote commented on src/sections/Meshery/Meshery-integrations/Individual-Integrations/index.js
> +            <Button primary className="get-started" title="Get Started" url="https://layer5.io/service-mesh-management/meshery/getting-started" />
Ideally, this is a relative path.

2022-08-19 18:49 UTC, leecalcote commented on src/sections/Meshery/Meshery-integrations/Individual-Integrations/index.js
> +            <Button primary className="get-started" title="Get Started" url="https://layer5.io/service-mesh-management/meshery/getting-started" />
with `alt` defined.

2022-08-19 19:16 UTC, l5io commented
🚀 Preview for commit 517578b22cee8a6225673bfdf1e63ef0efd5580b at: https://62ffe121613477287fc38861--layer5.netlify.app

2022-08-20 05:55 UTC, Nikhil-Ladha approved these changes

2022-08-20 05:56 UTC, merged