Fixed FAQ section issue#3079
layer5io/layer5 pull request #3102
Opened 2022-08-22 03:24 UTC by sourav-sharma7

Signed-off-by: sourav-sharma7 <souravsharma1321@gmail.com>

**Description**
FAQ section fixed and button links added

This PR fixes #3079

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-08-22 03:41 UTC, l5io commented
🚀 Preview for commit 703adda4a4a58e9cf3a480e1696bf351ef783866 at: https://6302fa4dab4f3a19abe375f4--layer5.netlify.app

2022-08-22 17:42 UTC, Nikhil-Ladha requested changes

2022-08-22 17:42 UTC, Nikhil-Ladha commented on src/assets/data/faq/index.js
> -      question: "Does Meshery manage service meshes?",
This question should be there as well.
The answer for the same is already provided by Debopriya in the issue comments, update accordingly.

2022-08-22 17:42 UTC, Nikhil-Ladha commented on src/assets/data/faq/index.js
> +        'Take advantage of these extension points for working with different service meshes via adapters, different load generators and different providers. Use Meshery’s REST API or its GraphQL API
Use double quotes

2022-08-23 08:44 UTC, sourav-sharma7 commented on src/assets/data/faq/index.js
> +        'Take advantage of these extension points for working with different service meshes via adapters, different load generators and different providers. Use Meshery’s REST API or its GraphQL API
Done. Please have a look.

2022-08-23 08:57 UTC, l5io commented
🚀 Preview for commit 97af9ecd3cee38cb0130e659f980a10ec33a9a37 at: https://63049625a5f44e4b4c625975--layer5.netlify.app

2022-08-23 09:44 UTC, Nikhil-Ladha approved these changes

2022-08-23 09:44 UTC, merged