Fix and verify all broken links
layer5io/layer5 pull request #3110
Opened 2022-08-23 09:02 UTC by JustinSalcedo

**Description**

This PR fixes #3044, fixing **63** of the [69 broken links](https://docs.google.com/spreadsheets/d/10t0NSlxQVbLS7_uPEJIY6AmkFib-HHqqj_UvGovJL8Q/edit#gid=0) found across the website.

Many broken links were duplicated or affected by the same bug. I listed each broken link according to its line number.

2: 'Get the Book'
```diff
// src/collections/service-mesh-books/service-mesh-patterns/index.mdx
-  <Button primary className="banner-btn one pa-8" title="Get the Book" url="hhttps://www.oreilly.com/library/view/service-mesh-patterns/9781492086444/" external="true"/>
+  <Button primary className="banner-btn one pa-8" title="Get the Book" url="https://www.oreilly.com/library/view/service-mesh-patterns/9781492086444/" external="true"/>
```

[3, 14, 18, 31, 38]: '致力于解决服务网格使用中碰到的棘手问题'
```diff
// src/collections/events/kubecon-china-2021/index.mdx
- <h2><a href="https://sched.co/nPOK">致力于解决服务网格使用中碰到的棘手问题</a></h2>
+ <h2><a href="https://kccncosschn21.sched.com/event/pcbq/ji-jie-zhi-ke-zha-mu-solving-the-service-mesh-adopters-dilemma-anita-ihuman-layer5?iframe=no">致力于解决服务网格使用中碰到的棘手问题</a></h2>

// src/collections/events/kubecon-china-2021/index.mdx
- <h2><a href="https://sched.co/nPOK">致力于解决服务网格使用中碰到的棘手问题</a></h2>
+ <h2><a href="https://kccncosschn21.sched.com/event/pcbq/ji-jie-zhi-ke-zha-mu-solving-the-service-mesh-adopters-dilemma-anita-ihuman-layer5?iframe=no">致力于解决服务网格使用中碰到的棘手问题</a></h2>
```

[4, 15, 19, 32, 39]: 'CNCF TAG Network and Service Mesh Working Group'
```diff
// src/collections/events/kubecon-china-2021/index.mdx
- Talk Link: https://sched.co/pTl8
+ Talk Link: https://kccncosschn21.sched.com/event/pcYk/cncf-tag-jie-zhang-re-jie-yuan-cncf-tag-network-and-service-mesh-working-group-lee-calcote-layer5-ed-warnicke-cisco-ken-owens-fiserv?iframe=no

- <h2><a href="https://sched.co/pTl8">CNCF TAG Network and Service Mesh Working Group</a></h2>
+ <h2><a href="https://kccncosschn21.sched.com/event/pcYk/cncf-tag-jie-zhang-re-jie-yuan-cncf-tag-network-and-service-mesh-working-group-lee-calcote-layer5-ed-warnicke-cisco-ken-owens-fiserv?iframe=no">CNCF TAG Network and Service Mesh Working Group</a></h2>

// src/collections/events/kubecon-china-2021/index.mdx
- Talk Link: https://sched.co/pTl8
+ Talk Link: https://kccncosschn21.sched.com/event/pcYk/cncf-tag-jie-zhang-re-jie-yuan-cncf-tag-network-and-service-mesh-working-group-lee-calcote-layer5-ed-warnicke-cisco-ken-owens-fiserv?iframe=no

- <h2><a href="https://sched.co/pTl8">CNCF TAG Network and Service Mesh Working Group</a></h2>
+ <h2><a href="https://kccncosschn21.sched.com/event/pcYk/cncf-tag-jie-zhang-re-jie-yuan-cncf-tag-network-and-service-mesh-working-group-lee-calcote-layer5-ed-warnicke-cisco-ken-owens-fiserv?iframe=no">CNCF TAG Network and Service Mesh Working Group</a></h2>
```

5: "Contributor's Journey Map"
```diff
// src/sections/Community/Calendar/index.js
- Begin your journey by <a href="http://slack.layer5.io">joining the community Slack</a>. Then, use the resources linked in our <a href="community/newcomers">Contributor's Journey Map </a>
+ Begin your journey by <a href="http://slack.layer5.io">joining the community Slack</a>. Then, use the resources linked in our <a href="newcomers">Contributor's Journey Map </a>

// src/sections/Community/index.js
- Begin your journey by <a href="http://slack.layer5.io">joining the community Slack</a>. Then, use the resources linked in our <a href="community/newcomers">Contributor's Journey Map </a>
+ Begin your journey by <a href="http://slack.layer5.io">joining the community Slack</a>. Then, use the resources linked in our <a href="newcomers">Contributor's Journey Map </a>
```

[6, 7]: 'Link'
```diff
// src/collections/service-mesh-workshops/2019_10_15_all_things_open_raleigh/index.mdx
- eurl: https://allthingsopen.org/talk/using-service-meshes-workshop-extended-session/
+ eurl: https://2019.allthingsopen.org/talk/using-service-meshes-workshop-extended-session/

// src/collections/service-mesh-workshops/2020_01_16_cloud_native_austin/index.mdx
- eurl: https://allthingsopen.org/talk/using-service-meshes-workshop-extended-session/
+ eurl: https://2019.allthingsopen.org/talk/using-service-meshes-workshop-extended-session/
```

[8, 9]: Nighthawk Image
```diff
// src/sections/Community/Handbook/repo-data.js
- repository: "https://github.com/layer5io/nighthawk",
+ repository: "https://github.com/layer5io/getnighthawk",

- repository: "https://github.com/layer5io/smi-conformance",
+ repository: "https://github.com/layer5io/meshery-smi-conformance-action",
```

[10, 11, 12, 13, 16, 17, 25, 26, 27, 33, 36, 37]: 'Navendu Pottekkat'
```diff
// src/collections/blog/2021/2021-06-25-she-code-africa-contributhon-boot-camp/index.mdx
- <li><Link to="/community/members/navendu-pottekkat">Navendu Pottekkat</Link></li>
+ <li>Navendu Pottekkat</li>

// src/assets/data/tutorials/index.js
- link: "/community/members/navendu-pottekkat",

// src/collections/blog/2021/2021-06-25-she-code-africa-contributhon-boot-camp/index.mdx
- <li><Link to="/community/members/navendu-pottekkat">Navendu Pottekkat</Link></li>
+ <li>Navendu Pottekkat</li>

// src/collections/events/introduction-to-istio/index.mdx
- <Link to="/community/members/navendu-pottekkat">Navendu Pottekkat</Link>
+ Navendu Pottekkat

// src/collections/events/kubecon-china-2021/index.mdx
- <li><Link to="/community/members/navendu-pottekkat">Navendu Pottekkat</Link></li>
+ <li>Navendu Pottekkat</li>
```

[20, 21, 22]: 'Nighthawk Developers'; 'Nighthawk Maintainers'; 'Nighthawk Users'
```diff
- <li><a href="http://developers@nighthawk.dev">Nighthawk Developers</a></li>
- <li><a href="http://maintainers@nighthawk.dev">Nighthawk Maintainers</a></li>
- <li><a href="http://users@nighthawk.dev">Nighthawk Users</a></li>
+ <li><a href="https://groups.google.com/a/getnighthawk.dev/g/developers">Nighthawk Developers</a></li>
+ <li><a href="https://groups.google.com/u/2/a/getnighthawk.dev/g/maintainers">Nighthawk Maintainers</a></li>
+ <li><a href="https://groups.google.com/a/getnighthawk.dev/g/users">Nighthawk Users</a></li>
```

23: 'Nighthawk'
```diff
// src/collections/news/2022/2022-05-18-meshmark-the-cloud-native-value-measurement/meshmark-the-cloud-native-value-measurement.md
- With the project’s <Link to="/company/news/analyzing-service-mesh-performance">approach to performance analysis</Link> published in IEEE The Bridge, ongoing analysis of nearly 40,000 performance test results will comprise the initial release of the <a href="https://smp-spec.io/dashboard">Service Mesh Performance Dashboard</a>, also unveiling at KubeCon EU. <Link to="/cloud-native-management/meshery">Meshery</Link>, the cloud native manager, orchestrates the provisioning and configuration of Kubernetes and each service mesh. With <Link to="projects/nighthawk">Nighthawk</Link> embedded, Meshery’s performance management functions are what drives the tests run within the CNCF Lab.
+ With the project’s <Link to="/company/news/analyzing-service-mesh-performance">approach to performance analysis</Link> published in IEEE The Bridge, ongoing analysis of nearly 40,000 performance test results will comprise the initial release of the <a href="https://smp-spec.io/dashboard">Service Mesh Performance Dashboard</a>, also unveiling at KubeCon EU. <Link to="/cloud-native-management/meshery">Meshery</Link>, the cloud native manager, orchestrates the provisioning and configuration of Kubernetes and each service mesh. With <Link to="/projects/nighthawk">Nighthawk</Link> embedded, Meshery’s performance management functions are what drives the tests run within the CNCF Lab.
```

24: 'Layer5 technology partner'
```diff
// src/collections/news/2022/2022-05-10-layer5-joins-docker-extension-program-bringing-kubernetes-and-service-mesh-management-to-docker-with-meshery/index.mdx
- As a user of the Meshery Docker Extension, <Link to="/community/members/nic-jackson">Nic Jackson</Link>, Principal Developer Advocate of HashiCorp, can <Link to="/blog/docker/extending- [...]

2022-08-23 11:38 UTC, debo19 requested changes

2022-08-23 11:38 UTC, debo19 commented on src/sections/Community/Calendar/index.js
> +                Begin your journey by <a href="http://slack.layer5.io">joining the community Slack</a>. Then, use the resources linked in our <a href="newcomers">Contributor's Journey Map </a>
```suggestion
                Begin your journey by <a href="http://slack.layer5.io">joining the community Slack</a>. Then, use the resources linked in our <Link to="/community/newcomers">Contributor's Journey Map </Link>
```

2022-08-23 11:38 UTC, debo19 commented on src/sections/Community/index.js
> +                  Begin your journey by <a href="http://slack.layer5.io">joining the community Slack</a>. Then, use the resources linked in our <a href="newcomers">Contributor's Journey Map </a>
```suggestion
                  Begin your journey by <a href="http://slack.layer5.io">joining the community Slack</a>. Then, use the resources linked in our <Link to="/community/newcomers">Contributor's Journey Map </Link>
```

2022-08-23 11:38 UTC, debo19 commented on src/sections/Community/index.js
> +                  Begin your journey by <a href="http://slack.layer5.io">joining the community Slack</a>. Then, use the resources linked in our <a href="newcomers">Contributor's Journey Map </a>
Use `<Link>` tag for all internal links

2022-08-23 11:43 UTC, l5io commented
🚀 Preview for commit 2fc66ad264ea7214e4591babe165a85396c25c57 at: https://6304bce98e94907034f04904--layer5.netlify.app

2022-08-23 12:01 UTC, debo19 requested changes

2022-08-23 12:01 UTC, debo19 commented on src/collections/events/introduction-to-istio/index.mdx
> +- [Meshery](/service-mesh-management/meshery) (Mac, Windows or Linux)
```suggestion
- [Meshery](/cloud-native-management/meshery) (Mac, Windows or Linux)
```

2022-08-23 19:04 UTC, JustinSalcedo commented on content-learn/mastering-service-meshes-for-developers/introduction-to-service-meshes/linkerd/expose-services.mdx
> +You may use http://localhost, <span>http://</span>kubernetes.docker.internal or your host's IP address.
This is an English grammar correction, but I can change it back anyways.

2022-08-23 19:39 UTC, l5io commented
🚀 Preview for commit d97693f8fb37be744e97bf5e512dc14caec16993 at: https://63052c582f395500b693e0c4--layer5.netlify.app

2022-08-25 10:49 UTC, l5io commented
🚀 Preview for commit 706a1ade0c6eed6a588bdd5df1483286c3597a4d at: https://6307531fff7afd0304235580--layer5.netlify.app

2022-08-25 10:50 UTC, debo19 approved these changes
LGTM 🎉 Thank you @JustinSalcedo

2022-08-25 10:50 UTC, merged

2022-08-26 06:45 UTC, JustinSalcedo commented
You're all welcome, @debo19 . What a pleasure!