[News] Added The Ultimate List of Open Source Cloud-Native Tools
layer5io/layer5 pull request #3156
Opened 2022-09-06 16:09 UTC by legendarykamal

**Description**
Added The Ultimate List of Open Source Cloud-Native Tools

This PR fixes #3128 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-09-06 16:28 UTC, l5io commented
🚀 Preview for commit f277c416cd69f1453c78579f6e99fb0f81f7d403 at: https://631774807092690316fb21ab--layer5.netlify.app

2022-09-06 17:30 UTC, debo19 commented on .gitpod.yml
> +# This configuration file was automatically generated by Gitpod.
I think you've added the wrong file. Index file is missing.

2022-09-07 20:22 UTC, debo19 requested changes

2022-09-07 20:22 UTC, debo19 commented on src/collections/news/2022/2022-09-06-the-ultimate-list-of-opensource-cn-tools/index.mdx
> +date: 2022-08-29 00:00:08 +0000
```suggestion
date: 2022-08-29 00:00:08 +0000
category: Coverage
```

2022-09-07 20:22 UTC, debo19 commented on src/collections/news/2022/2022-09-06-the-ultimate-list-of-opensource-cn-tools/index.mdx
> +date: 2022-08-29 00:00:08 +0000
This should fix the build fail

2022-09-08 02:39 UTC, leecalcote commented on src/collections/news/2022/2022-09-06-the-ultimate-list-of-opensource-cn-tools/index.mdx
> +<h3>Service Mesh Tools</h3>
Add links to the /meshery and the /service-mesh-performance and the /projects/service-mesh-interface-conformance pages, please.

2022-09-08 02:52 UTC, l5io commented
🚀 Preview for commit 1060a29ba624ba4a821ca2991db1b0a7770d2ac5 at: https://63195868530c54195b09819c--layer5.netlify.app

2022-09-08 13:14 UTC, l5io commented
🚀 Preview for commit 05d2bb98decc08f41a140714473fa38739389bdb at: https://6319ea3c9797eb008995ed1b--layer5.netlify.app

2022-09-08 13:30 UTC, leecalcote commented
Please ensure that there is whitespace between sections and between section headings and their content.

<img width="405" alt="Screen Shot 2022-09-08 at 8 28 40 AM" src="https://user-images.githubusercontent.com/7570704/189134884-a68f6601-8468-4098-9a38-90f27c781960.png">


Don't forget the period after SMP.

Let's go ahead an include a copy of the full article in this post, please.

2022-09-08 20:00 UTC, legendarykamal commented
ok @leecalcote  I thought Read the full article would lead but yes Lets include the full article :smiley:

2022-09-09 04:04 UTC, legendarykamal commented
@leecalcote Included the full code coverage with minor new line changes ,  :+1:

2022-09-09 04:17 UTC, l5io commented
🚀 Preview for commit 1d74b8f64074fc49ef74fdd8185bf79bedb9d790 at: https://631abe2389b56260b607af67--layer5.netlify.app

2022-09-09 04:58 UTC, leecalcote commented
This is a bit odd - how is it that the single news page for a piece of news lists the same piece of news as the first related article at the bottom of the page? 

We might have a query issue.

2022-09-09 12:11 UTC, merged

2022-09-09 14:37 UTC, legendarykamal commented
> This is a bit odd - how is it that the single news page for a piece of news lists the same piece of news as the first related article at the bottom of the page?
> 
> We might have a query issue.

yes @leecalcote I have personally tried to solve this and opened up a new issue for this . Related posts actually queries all the post that are latest by date hence it reflects below.

2022-09-09 21:07 UTC, leecalcote commented
@legendarykamal, this is very much appreciated. Thank you for taking the initiative to enhance the behavior here.