Removed duplicated pattern
layer5io/layer5 pull request #3160
Opened 2022-09-08 05:58 UTC by Nawaz027

Signed-off-by: Nawaz027 <nawazsiddiqui27@gmail.com>

**Description**
removed one of the duplicated filters on patterns page from area I section.
Link of the webpage:
https://layer5.io/learn/service-mesh-books/service-mesh-patterns

This PR fixes https://github.com/layer5io/layer5/issues/3151

This PR fixes #3151

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-09-08 06:46 UTC, l5io commented
🚀 Preview for commit c7318899b0e588062ed693cb8482f9d0fe8c3594 at: https://63198f5e1a0850413efc040e--layer5.netlify.app

2022-09-08 13:01 UTC, legendarykamal requested changes
I still see both the filters 
![image](https://user-images.githubusercontent.com/95926324/189128419-bc120451-8ef5-4a2b-ab54-29bb7eed7841.png)

2022-09-09 08:40 UTC, Nikhil-Ladha commented on src/collections/service-mesh-books/service-mesh-patterns/tableData.js
> -  },
Where is the chapter repeated?

2022-09-15 04:09 UTC, Nawaz027 commented
Sorry, I accidently removed table data. Now it's being fixed. Also category column is being removed and service mesh pattern is visible now.

2022-09-15 17:03 UTC, legendarykamal commented
@Nawaz027 please do fix the dco issue.

2022-09-21 22:50 UTC, leecalcote commented
Creating new deployment preview...

2022-09-21 23:06 UTC, l5io commented
🚀 Preview for commit 430d04fa7850e153017d03561603f37f585155ba at: https://632b986d2cf1860595a9f1fc--layer5.netlify.app

2022-09-29 14:24 UTC, Nikhil-Ladha commented
I still don't get where is this text duplicated, can you please point me to it? 🤔

2022-09-29 15:22 UTC, legendarykamal commented
hi @Nikhil-Ladha text isnt duplicated , please see the filters here https://github.com/layer5io/layer5/pull/3160#pullrequestreview-1100703670

2022-09-29 15:24 UTC, Nikhil-Ladha commented
Ok, I see. Perhaps a better issue description is needed...

2022-09-29 15:30 UTC, legendarykamal commented
> Ok, I see. Perhaps a better issue description is needed...

updated

2022-10-10 08:02 UTC, debo19 commented
@Nawaz027 will you discuss this on the websites call today?

2022-10-11 11:32 UTC, Nikhil-Ladha commented
@Nawaz027 any updates here?

2022-10-18 21:07 UTC, leecalcote commented
Other than DCO, is there do you approve, @legendarykamal?

2022-10-31 15:27 UTC, leecalcote commented
Thanks for jumping and helping, @Nawaz027. Much appreciated.

There does not seem to be a duplication of patterns, which leaves me wondering what is being fixed here. It seems that we are deleting a valid pattern in this PR.

2022-10-31 15:28 UTC, leecalcote commented
@Nawaz027 or @legendarykamal will you take a moment to confirm, please?

2022-10-31 15:39 UTC, legendarykamal approved these changes
other than DCO, everything looks good @leecalcote .

2022-10-31 15:42 UTC, legendarykamal reviewed
Let us close this as it has been already successfully solved in another PR by @tiger-yash .

Thank you @Nawaz027 for contributing .

2022-10-31 15:42 UTC, closed without merging