Add padding to the text below 767px on page : /docker-extension-meshery
layer5io/layer5 pull request #3331
Opened 2022-10-15 18:11 UTC by tinniaru3005

**Description**
Fixed the issue by adding a padding of 15 px to left and right

This PR fixes #3324 
Closes #3324 
**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-10-15 18:54 UTC, leecalcote commented
Thanks, @tinniaru3005 🙂

2022-10-17 06:37 UTC, Nikhil-Ladha requested changes

2022-10-17 06:37 UTC, Nikhil-Ladha commented on src/sections/Docker-Meshery/dockerMeshery.style.js
> +    .jFTZLO {
This won't work, as this is a temp/random className generated at the time of bundling.
Please use the actual className that the component has, or if needed add a new className to it.

2022-10-17 06:51 UTC, l5io commented
🚀 Preview for commit 74c091e562db0be6bdd5767880001038ca6e6740 at: https://634cfaad47ed83287edf1214--layer5.netlify.app

2022-10-17 19:17 UTC, tinniaru3005 commented
Hey @Nikhil-Ladha, I made the changes. Can you please confirm if it looks fine now?

2022-10-17 19:32 UTC, tinniaru3005 commented
Hey @sahilsuman933, for the last commit I did it using VSCode. I hopw now it will work.
![signoff](https://user-images.githubusercontent.com/62856848/196266062-1df7fd1b-bed9-490e-83a6-fff50b51f1b3.png)

For the previous commits I was not aware of it. Do I need to close the PR, delete the branch, commit again and send the PR?

2022-10-17 19:33 UTC, leecalcote commented
@tinniaru3005 you can follow these instructions to amend your sign-off to older commits - https://github.com/layer5io/layer5/pull/3331/checks?check_run_id=8943201532

2022-10-17 19:46 UTC, l5io commented
🚀 Preview for commit 9dcbf730c4e3fda645cdcd14b63cb4a6b7810b2b at: https://634db04f6810a61683e51086--layer5.netlify.app

2022-10-17 20:09 UTC, closed without merging