Gap on the page from 913px to 971px on page: layer5.io/docker-extension-meshery is solved
layer5io/layer5 pull request #3384
Opened 2022-10-19 18:28 UTC by UtkarshMishra12

Signed-off-by: Utkarsh Mishra <nasautkarsh@gmail.com>

**Description**
 Gap on the page from 913px to 971px on page: layer5.io/docker-extension-meshery is solved
This PR fixes #3361 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-10-19 18:31 UTC, UtkarshMishra12 commented
@Nikhil-Ladha I have made the changes, let me know your thoughts about it. 😊

2022-10-19 18:52 UTC, l5io commented
🚀 Preview for commit feeb9995cd032b7a1d972899cbcf67bc4b247cd2 at: https://635046fb4a2c3f00b4fbdb46--layer5.netlify.app

2022-10-19 19:06 UTC, Nikhil-Ladha requested changes

2022-10-19 19:06 UTC, Nikhil-Ladha commented on src/sections/General/Navigation/navigation.style.js
> +    @media (min-width:768px){
It should be limited from `912px to 992px` as for other screen resolutions it is constrained by the `Container` component.

2022-10-19 19:56 UTC, UtkarshMishra12 commented
Do I have to replace the above line with this line? @Nikhil-Ladha 
@ media (min-width:912px) and (max-width:992px){
    max-width:850px;
}

2022-10-19 20:10 UTC, Nikhil-Ladha commented
> Do I have to replace the above line with this line? @Nikhil-Ladha @ media (min-width:912px) and (max-width:992px){ max-width:850px; }

Yup

2022-10-20 05:16 UTC, l5io commented
🚀 Preview for commit 4cc919b9ed42d05a6dacfdf99591f4c972675c61 at: https://6350d9448ccbf0695e7ecc77--layer5.netlify.app

2022-10-20 05:33 UTC, Nikhil-Ladha approved these changes

2022-10-20 05:33 UTC, merged