Add an infinite carousel in the partner section
layer5io/layer5 pull request #3496
Opened 2022-12-03 16:57 UTC by roottool

Signed-off-by: Teruaki Atake <operation.versatile.roottool@gmail.com>

**Description**

This PR fixes #3476
This PR adds an infinite carousel in the partner section.

The infinite carousel is only activated when the window width size is 1400px over.
It is not activated when the window width size is 1400px or less. The partner section shows as before.

Ref. https://github.com/layer5io/layer5/issues/3476#issuecomment-1332155290

![responsive partners](https://user-images.githubusercontent.com/11808736/205452364-20690fb6-ee5c-4826-82f2-1754349e77e1.gif)

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-12-03 18:56 UTC, Nikhil-Ladha requested changes
Well, if all the carousel is needed then it is for smaller width screens and not for higher resolution. I think you just did the opposite of what I meant 😅 .
While you do so, update the `slidesToShow` count to `5` for the initial view and then reduce it as needed such that the entire screen width is covered.

2022-12-03 19:00 UTC, l5io commented
🚀 Preview for commit 1240ac2bebb0223b83707aa2971382398b89e393 at: https://638b9c68eae3365dc8f11682--layer5.netlify.app

2022-12-23 18:49 UTC, eeshaanSA commented
@roottool 👀👀

2022-12-30 07:08 UTC, UtkarshMishra12 commented
@roottool Please update

2022-12-30 19:22 UTC, roottool commented
I'm sorry to response too late.

**Description**

I changed two points.

- I put the partner slider out of `Container` component.
  - This is to achieve full width. By `maxWidth`, `Container` has margins on both sides.
- I enabled [`variableWidth`](https://kenwheeler.github.io/slick/#:~:text=%7D%29;-,Variable%20Width,-Previous) and [`centerMode`](https://kenwheeler.github.io/slick/#:~:text=%3C/div%3E-,Center%20Mode,-Previous) in slick.
  - This is because many partner icons are expanded in the area.
  - The margins between icons are the default values in slick.

**Screenshot**

![Responsive partners](https://user-images.githubusercontent.com/11808736/210102933-f55f8e91-cd9e-4aa2-9b03-1c359ae5d701.gif)

2023-01-05 10:39 UTC, l5io commented
🚀 Preview for commit 96cfde9adbbd2fa1d64b28426a8183619450824d at: https://63b6a85917967e0b0c68fdf3--layer5.netlify.app

2023-01-10 15:38 UTC, Nikhil-Ladha commented
The partner logos need not have to be full-size. Please retain (update to) the current size of the images.
Also, as I said we need not be showing the carousel until and unless the images have started to get cut off. With that said, for me at 1920px the logos are not cropped. So, check (use the dev console) the resolution at which the logos are starting to cut off and update the carousel `breakpoint` to that value.

2023-01-15 21:58 UTC, eeshaanSA commented
@roottool you should demo your work in the websites call. // @UtkarshMishra12

2023-01-30 13:44 UTC, gurpreet-legend commented
I'll work on this :) @eeshaanSA

2023-01-30 13:46 UTC, mohit-marathe commented
Hello @eeshaanSA, I'm a newcomer, can I work on this?

2023-01-31 21:17 UTC, eeshaanSA commented
Assigning in the order of requests. @roottool since there has been no update from you on this PR for over 3 weeks, I am assigning this issue to @gurpreet-legend

2023-01-31 22:56 UTC, leecalcote commented
@gurpreet-legend, please carry this forward.

2023-02-10 20:15 UTC, gurpreet-legend commented
@eeshaanSA , the image size issue has been fixed and it's also responsive now. Infinite carousel will only appear at large screen sizes.  You can review the PR :)

2023-02-12 05:56 UTC, eeshaanSA commented
Thats great, @gurpreet-legend .

2023-02-12 05:56 UTC, eeshaanSA commented
We can discuss this tomorrow in the Websites Call, where you'll gets tonnes of feedback. 😀

2023-02-23 18:41 UTC, merged