[Community] Member Profile: Utkarsh Mishra
layer5io/layer5 pull request #3521
Opened 2022-12-15 11:21 UTC by tinniaru3005

Signed-off-by: Arunima Chaudhuri <arunimachaudhuri2020@gmail.com>

**Description**
Add Utkarsh Mishra's member profile
This PR fixes #3515 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-12-15 11:22 UTC, tinniaru3005 commented
@UtkarshMishra12 Have a look.

2022-12-15 11:44 UTC, UtkarshMishra12 requested changes

2022-12-15 11:44 UTC, UtkarshMishra12 commented on src/collections/members/utkarsh-mishra/index.mdx
> +linkedin: Lucknow, India
@tinniaru3005 Please swap the information of( LinkedIn & Location )

2022-12-15 11:58 UTC, tinniaru3005 commented
@UtkarshMishra12 👀

2022-12-15 20:21 UTC, tinniaru3005 commented
Hey @UtkarshMishra12 do you have any idea why the build is taking so long.

2022-12-16 06:29 UTC, UtkarshMishra12 commented
> Hey @UtkarshMishra12 do you have any idea why the build is taking so long.

I don't know why it's taking so long. Maybe @Chadha93 can tell you about it?

2022-12-16 16:50 UTC, UtkarshMishra12 approved these changes
LGTM! Thanks @tinniaru3005 😊
@Chadha93 Why the Preview Site is failing any Idea about it?

2022-12-19 13:17 UTC, Nikhil-Ladha approved these changes

2022-12-19 13:18 UTC, merged