added [News] The Most Innovative Cloud Management Companies
layer5io/layer5 pull request #3612
Opened 2023-01-11 11:03 UTC by ShadyResurrected

**Description**

This PR fixes #3608
Added [News] The Most Innovative Cloud Management Companies

**Notes for Reviewers**

- [ShadyResurrected] Yes, I signed my commits.

2023-01-11 13:01 UTC, l5io commented
🚀 Preview for commit 600235901f9e908041ca39f48e17355d25b6200b at: https://63beb23e9e60f00255bfc77b--layer5.netlify.app

2023-01-11 17:50 UTC, leecalcote commented on src/collections/news/2023/2023-01-11-the-most-innovative-cloud-management-companies/index.mdx
> +subtitle: ""
```suggestion
subtitle: "Layer5 recognized as one of the most innovative cloud management companies"
```

2023-01-11 17:51 UTC, leecalcote requested changes
Thanks, @ShadyResurrected. We'll need a different image for this news article.

2023-01-11 18:08 UTC, l5io commented
🚀 Preview for commit e0b0a390eaa89fe39215afd9d86f93332434f76c at: https://63befaa9ec760c09b811133b--layer5.netlify.app

2023-01-11 18:53 UTC, l5io commented
🚀 Preview for commit b39f535d64323321345cd9e4831319a479daa54d at: https://63bf052d423d1e1ab19f2dcd--layer5.netlify.app

2023-01-13 02:40 UTC, l5io commented
🚀 Preview for commit b39f535d64323321345cd9e4831319a479daa54d at: https://63c0c41da3f71f31e7965e2e--layer5.netlify.app

2023-01-13 06:21 UTC, leecalcote commented on src/collections/news/2023/2023-01-11-the-most-innovative-cloud-management-companies/index.mdx
> +published: false
```suggestion
published: true
```

2023-01-13 16:15 UTC, leecalcote commented
Deploy preview building...

2023-01-13 21:39 UTC, leecalcote approved these changes
Thank you, @ShadyResurrected. This looks great. 👍

2023-01-13 21:40 UTC, merged