add meshmap project card in projects grid
layer5io/layer5 pull request #3652
Opened 2023-01-20 12:21 UTC by avikt18

**Description**
This PR adds a new card for the project MeshMap in the projects grid on this [webpage](https://layer5.io/projects)

This PR fixes #3621 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-01-20 12:44 UTC, l5io commented
🚀 Preview for commit 5d8c4be921d50253c7e2ffe59310835dc6d30156 at: https://63ca8bfad0155f210ec419b5--layer5.netlify.app

2023-01-20 16:00 UTC, avikt18 commented
Oops!! The lighthouseCI test is failing :eyes: @leecalcote

2023-01-20 18:08 UTC, leecalcote commented
> Oops!! The lighthouseCI test is failing 👀 @leecalcote

@ayushthe1 will be coming around on these items. 👍

2023-01-20 18:14 UTC, leecalcote requested changes

2023-01-20 18:14 UTC, leecalcote commented on src/sections/Projects/Project-grid/index.js
> +            <Link to="/projects/nighthawk" className="project__card nine">
```suggestion
            <Link to="/cloud-native-management/meshmap" className="project__card nine">
```

2023-01-20 18:50 UTC, l5io commented
🚀 Preview for commit 2a28bb935f14815e46c710774e2d4fe11f4b5979 at: https://63cae1beb4c06915adffd9f2--layer5.netlify.app

2023-01-20 19:03 UTC, Chadha93 requested changes
@avikt18 Please use rem instead of px for height, width, and margins...

2023-01-20 20:12 UTC, avikt18 commented
Ohh..okay @Chadha93

2023-01-21 12:05 UTC, Nikhil-Ladha commented
> Ohh..okay @Chadha93. I will fix it for margins. Do you also want me to change image heights and widths to rem? because all the images have it in px

Yes, please take the equal (or closest) value in `rem` and use `rem` for `width`/`height` as well

2023-01-21 14:26 UTC, l5io commented
🚀 Preview for commit d285da7a9ee31f51d1a109ff1fef1d0b97b49e82 at: https://63cbf5ccf84df005e683b5c5--layer5.netlify.app

2023-01-22 06:17 UTC, Chadha93 approved these changes
Cool :ok_hand:  Thank you @avikt18

2023-01-22 06:18 UTC, merged