[Homepage] bug: fixed too much whitespace in banner4
layer5io/layer5 pull request #3710
Opened 2023-02-06 22:20 UTC by Oghene-kevwe

Signed-off-by: Idise Praise <Idisepraise@gmail.com>

**Description**

This PR fixes #3686

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-02-06 22:21 UTC, leecalcote commented
@ShuvamChatterjee28 would you like offer review here?

2023-02-06 22:44 UTC, l5io commented
🚀 Preview for commit a6df39b5b3a28f258df9416314a0851c178b4c1a at: https://63e1822aa0965b1c1fa0bd45--layer5.netlify.app

2023-02-07 04:32 UTC, ShuvamChatterjee28 commented
Hello @leecalcote, certainly I would love to review this one. Thanks.

2023-02-07 12:50 UTC, ShuvamChatterjee28 commented
LGTM, I am approving the changes.

2023-02-07 12:50 UTC, ShuvamChatterjee28 approved these changes

2023-02-07 13:01 UTC, Shivam-AfA approved these changes
Looks good.

2023-02-08 10:24 UTC, leecalcote approved these changes
Thanks, @Oghene-kevwe, all. 👍

2023-02-08 10:32 UTC, leecalcote requested changes
I still see the following behavior in Safari:

<img width="2410" alt="Screenshot 2023-02-08 at 4 25 18 AM" src="https://user-images.githubusercontent.com/7570704/217503544-3d798797-aea1-41eb-9e16-93dd43bba8dd.png">
<img width="1158" alt="Screenshot 2023-02-08 at 4 25 28 AM" src="https://user-images.githubusercontent.com/7570704/217503570-6f999c14-d219-4921-87a1-59bea0320870.png">

2023-02-09 19:24 UTC, leecalcote commented
@Shivam-AfA keep a watchful eye, please.

@Oghene-kevwe, will you be fixing the outstanding issues screenshot'ed above?

2023-02-09 19:38 UTC, ShuvamChatterjee28 commented
@leecalcote I also see from the Safari, the section below the navbar is hooked. However in the chrome it is showing differently. I don't have much frontend knowledge, but I think it is causing because it is hooked with the navbar. Please correct if I am wrong.

2023-02-09 19:49 UTC, Shivam-AfA commented
@leecalcote This is strange. It appears different on my pc. I guess I'll have to use cross check with Safari for UI based issues.

2023-02-10 01:02 UTC, Oghene-kevwe commented
@leecalcote yes, I will definitely fix it

2023-02-11 13:45 UTC, Nikhil-Ladha commented on src/components/BGImage/BGImage.styles.js
> +    top: 35%;
The fix is not simply updating the `top` value. It requires drilling through the CSS of the `BGImage` component and updating the `position` value to `relative` and `absolute` based on resolution.

2023-02-12 17:19 UTC, leecalcote commented
This is a relatively urgent issue.

2023-02-12 17:35 UTC, Nikhil-Ladha commented
I will wait till afternoon tomorrow, if @Oghene-kevwe doesn't push a fix by then will make the update myself.

2023-02-12 19:43 UTC, ShuvamChatterjee28 commented
Hey, I would like to work on this one. If I can't complete it within tomorrow mid-night, then please feel free to complete it. This will be a good chance for me to learn CSS.

2023-02-12 20:43 UTC, Oghene-kevwe commented
@leecalcote @Nikhil-Ladha  I'm sorry for the late response. I will push a fix before tomorrow.

2023-02-13 06:28 UTC, ShuvamChatterjee28 commented
Hey, I can see a good part of my fix is here. Thank you @Nikhil-Ladha for adding the suggested part. I have learned a lot to solve this one. Very happy to see it. :)

2023-02-13 06:29 UTC, Nikhil-Ladha commented
> Hey, I can see a good part of my fix is here. Thank you @Nikhil-Ladha for adding the suggested part. I have learned a lot to solve this one. Very happy to see it. :)

Yeah, np :)

2023-02-13 06:43 UTC, l5io commented
🚀 Preview for commit b56b07bcfbafaad8febcad70b32c3ff8ebc31cda at: https://63e9db57ccbb6b2815b19f83--layer5.netlify.app

2023-02-13 06:51 UTC, merged

2023-02-13 06:54 UTC, ShuvamChatterjee28 commented
@Nikhil-Ladha #3745 and #3691 is also fixed with this fix.