[repository overview] fix: overflow occurring on the repository overview page
layer5io/layer5 pull request #3834
Opened 2023-02-28 01:10 UTC by Aditya-A-G

**Description**

This PR fixes #3807 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [&#x2714; ] Yes, I signed my commits.

2023-02-28 01:33 UTC, l5io commented
🚀 Preview for commit 4800a3be5c42fe9d3f6f37934c923a31dc1a7e86 at: https://63fd598cccddc826b77892d9--layer5.netlify.app

2023-03-01 19:13 UTC, tinniaru3005 requested changes
Hey, @Aditya-A-G Great work. Just a small change: 
- Remove part 1 as marked in the image
- Mobe the heading to the top
![rep-overview](https://user-images.githubusercontent.com/62856848/222240944-38bf87af-c17f-4654-8c58-4ee06b2949c8.png)

2023-03-02 18:47 UTC, leecalcote reviewed
Thanks for this, @Aditya-A-G.

Gosh, does all of this need to change?

2023-03-03 08:00 UTC, Aditya-A-G commented
Thanks for reviewing the pull request, @leecalcote  I made the changes proposed because there were inconsistent spacing issues across multiple pages of the community handbook. If you have any specific concerns or suggestions for improvement, please let me know and I will be happy to address them. Also are you good with the proposed suggestions by @tinniaru3005

2023-03-03 08:08 UTC, Aditya-A-G commented
Additionally, I made some changes to the styles to improve readability by moving them around in the file

2023-03-03 11:21 UTC, Nikhil-Ladha requested changes

2023-03-03 11:21 UTC, Nikhil-Ladha commented on src/sections/Community/Handbook/Handbook.style.js
> -    }
Apart from these lines there are no actual changes in this PR. Please revert the other changes and limit the changes only to those that are needed.

2023-03-03 11:25 UTC, Nikhil-Ladha commented
Yea, please address the feeedback given by @tinniaru3005 .

> Additionally, I made some changes to the styles to improve readability by moving them around in the file

No neeed for such changes, please revert them.

2023-03-03 13:06 UTC, l5io commented
🚀 Preview for commit 50e4022c0c23f3d8dd4fa56851ba64f0b9f04577 at: https://6401f03906ae110f5b42bbb8--layer5.netlify.app

2023-03-03 13:53 UTC, Nikhil-Ladha commented
Please follow the steps mentioned [here](https://github.com/layer5io/layer5/pull/3834/checks?check_run_id=11742855318) to fix the DCO check.

2023-03-03 13:58 UTC, Nikhil-Ladha requested changes
Please disable any prettify plugin that you have and limit the changeset to only the required changes.

2023-03-03 15:25 UTC, l5io commented
🚀 Preview for commit 31c9e2974045e52ac7e10ead6f91c3cacea864b7 at: https://640210e08bf47f2f6ac60dd9--layer5.netlify.app

2023-03-03 16:37 UTC, Nikhil-Ladha approved these changes

2023-03-03 16:39 UTC, tinniaru3005 approved these changes
LGTM :)

2023-03-03 16:42 UTC, merged