fixed margin issue in mobile screen on coverage and press-release buttons
layer5io/layer5 pull request #3842
Opened 2023-03-01 08:47 UTC by ishaandwivedi1234

**Description**

Earlier coverage and Press-release buttons were touching the borders of the page when "/company/news" page was viewed on mobile screens. 

This PR fixes #

In this PR following changes have been made: - 

1. Class button container can now flex-wrap, which allows both the buttons to be in column orientation when there is not enough space for  both of them to be in a single row
2. Added separate CSS rules, for normal and small mobile screens specifying the margins. 
3. No static sizing is used, therefore buttons are responsive in every screen size. 

Following are the screenshots of various screen sizes : 

**1. Desktop Size**
<img width="1074" alt="Screenshot 2023-03-01 at 1 42 31 PM" src="https://user-images.githubusercontent.com/50709505/222086634-af04297f-bddf-47d2-b0ef-fbac49c207e6.png">

**2. Normal Mobile Screen** 

<img width="466" alt="Screenshot 2023-03-01 at 1 42 48 PM" src="https://user-images.githubusercontent.com/50709505/222086719-6942527b-858c-4eb2-87e6-6eefe7dd3803.png">

**3. Small Mobile Screen**
<img width="466" alt="Screenshot 2023-03-01 at 1 42 58 PM" src="https://user-images.githubusercontent.com/50709505/222086826-7349ad5a-a4a8-464c-888f-38f9bfcffa79.png">

**4. Foldable Mobiles** 
<img width="466" alt="Screenshot 2023-03-01 at 1 43 05 PM" src="https://user-images.githubusercontent.com/50709505/222086942-27214469-5e8b-437b-833c-26b53e9e8026.png">

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-03-01 09:06 UTC, l5io commented
🚀 Preview for commit 4a56b2cab9fd03e742cc02df70ba9b7a91aa2769 at: https://63ff1511589fdf5377e15760--layer5.netlify.app

2023-03-03 11:05 UTC, Nikhil-Ladha requested changes
Looks good, though a couple of changes still needeed.
1. Fix the start/end value of media queries to resolve this issue.
![Screenshot 2023-03-03 at 4 32 03 PM](https://user-images.githubusercontent.com/29438875/222704292-36fb3602-f395-4618-8ca4-cf28d84a3d54.png)

2. Center align the search bar for screen widths 990px to 768px
![Screenshot 2023-03-03 at 4 31 44 PM](https://user-images.githubusercontent.com/29438875/222704458-7e71891f-9e5d-4094-addb-a737445abcab.png)

3. Remove the unnecessary top-margin for the page heading. Ovveeride the `PageHeader` component style in the page's stylesheet don't update the stylesheet of the generic component itself.

2023-03-03 11:11 UTC, ishaandwivedi1234 commented
Thanks, @Nikhil-Ladha for reviewing, I'll fix the mentioned issues.

2023-03-06 12:07 UTC, Chadha93 commented
@ishaandwivedi1234   Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

2023-03-06 12:15 UTC, ishaandwivedi1234 commented
> @ishaandwivedi1234 Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

Absolutely, I was also hoping to have a discussion about this :), Currently, I am currently unable to access the meeting minutes document, but I have requested permission to do so. @Chadha93

2023-03-06 12:18 UTC, Chadha93 commented
> > @ishaandwivedi1234 Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)
> 
> Absolutely, I was also hoping to have a discussion about this :), Currently, I am unable to access the meeting minutes document, but I have requested permission to do so. @Chadha93

Fill this in to get access: https://layer5.io/newcomers. Also, You can add your item as suggestions also.

2023-03-13 06:45 UTC, Nikhil-Ladha commented
Still figuring out the changes needed here @ishaandwivedi1234 ?

2023-03-13 16:02 UTC, ishaandwivedi1234 commented
> Still figuring out the changes needed here @ishaandwivedi1234 ?

@Nikhil-Ladha I will commit the changes ASAP

2023-04-14 07:44 UTC, closed without merging