blank space removed from meshery section
layer5io/layer5 pull request #3904
Opened 2023-03-06 07:24 UTC by ShravaniAK

**Description**

This PR fixes #3900 

**Notes for Reviewers**
earlier in tablet view 

<img width="806" alt="Screenshot 2023-03-06 at 12 52 14 PM" src="https://user-images.githubusercontent.com/97099574/223044596-4c256593-3d6f-4b44-8251-85dc9b1060c4.png">

now 

<img width="833" alt="Screenshot 2023-03-06 at 12 51 31 PM" src="https://user-images.githubusercontent.com/97099574/223044654-9ea6620c-7112-4fe6-be04-4406411bf31c.png">

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-03-06 07:47 UTC, l5io commented
🚀 Preview for commit e7744b9c2b99798252a2a3af716c992a072815f4 at: https://640599eddccd424ef0b127ff--layer5.netlify.app

2023-03-08 23:55 UTC, leecalcote requested changes

2023-03-08 23:55 UTC, leecalcote commented on src/sections/Meshery/meshery.style.js
> +                .meshery-hero-img {
Am I reading this wrong or did you repeat the same class twice? If so, is there a special need to do so?

2023-03-08 23:55 UTC, leecalcote commented
Thank you for working on this, @ShravaniAK 👍

2023-03-09 02:40 UTC, ShravaniAK commented
@leecalcote can you please review it once again , I have corrected the mistake and aligned text to center.

2023-03-09 02:57 UTC, l5io commented
🚀 Preview for commit f78d05c8c613dce4c77e97a10944e42092d7d679 at: https://64094aa814f8464bd3d6b560--layer5.netlify.app

2023-03-09 13:11 UTC, swagataroy30 commented
Hey, some spacing is required between the two buttons and else looks good!

![Screenshot from 2023-03-09 18-19-20](https://user-images.githubusercontent.com/116095538/224028827-32d968d1-1948-40ad-9d70-ee601389a8b5.png)

2023-03-09 13:15 UTC, swagataroy30 commented
The border radius of the meshery video is not consistent in smaller devices, just a suggestion i don't know if it's meant to be that way ... @leecalcote your views on it ?

![Screenshot from 2023-03-09 18-37-51](https://user-images.githubusercontent.com/116095538/224033342-6d256e5f-f2c2-4fbe-b3ce-587704c988a1.png)

2023-03-09 13:34 UTC, ShravaniAK commented
@swagataroy30 Its not because of border radius , but width issue , i have corrected everything now , and thanks for informing .

2023-03-09 13:55 UTC, l5io commented
🚀 Preview for commit 3e42a99d36dea1a2e18fd67ea0e5b9f053d6d233 at: https://6409e4deae02200a973d9cc9--layer5.netlify.app

2023-03-10 07:05 UTC, Nikhil-Ladha commented on src/sections/Meshery/meshery.style.js
> +                    margin-bottom: .75rem;
You don't need to add same styles again for other media queries until and unless we are restricting the CSS upto a resolution, which we are not in this case. So, please o though the code and remove all duplicate declarations and verify everything looks good.

2023-03-11 12:39 UTC, l5io commented
🚀 Preview for commit 5036f39041985b63837b6185cbe0b1de26bb4c8a at: https://640c762adcf74667d34b2c8c--layer5.netlify.app

2023-03-13 05:44 UTC, Chadha93 commented
@ShravaniAK  Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

2023-03-13 06:57 UTC, Nikhil-Ladha approved these changes

2023-03-13 06:58 UTC, merged