Fixes #3928
layer5io/layer5 pull request #3935
Opened 2023-03-09 19:41 UTC by parmishh

**Description**

This PR fixes #3928 

**Notes for Reviewers**
fixes https://github.com/layer5io/layer5/issues/3928

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-03-09 20:00 UTC, l5io commented
🚀 Preview for commit bd7ad72522f2e4c0094590c4f8074a332fa0ac55 at: https://640a3a7960ff180088e65fa7--layer5.netlify.app

2023-03-10 05:59 UTC, Nikhil-Ladha commented on src/sections/General/Footer/footer.style.js
> +          }
Could be aggregated under one media query.
Also, for media queries it is better to use `px` unit for resolutions over `rem`.

2023-03-10 06:05 UTC, Nikhil-Ladha requested changes
Thee issue is still not resolved. I could still see the `Terms` button being overlapped by the `Scroll-to-top` button for most of the screen resolutions after 1350px.

2023-03-10 06:10 UTC, parmishh commented
@Nikhil-Ladha yes I got it working to fix for 1350px +. And also reducing code length. Will update it soon.

2023-03-10 09:16 UTC, parmishh commented
@Nikhil-Ladha 
I have done some changes looking responsive on most devices mobile/desktop.
Have a look.

https://user-images.githubusercontent.com/91942072/224275073-d86e2072-7048-443b-9c8d-ead6317023c1.mp4

2023-03-10 09:49 UTC, parmishh commented
@Nikhil-Ladha @Chadha93 please have a look.😊

2023-03-10 10:39 UTC, l5io commented
🚀 Preview for commit aaf662149babb017520f779a1e24a1c0b966e182 at: https://640b08da0692467f9adc6378--layer5.netlify.app

2023-03-10 10:43 UTC, Nikhil-Ladha commented on src/sections/General/Footer/footer.style.js
> +           }
There is still an overlap in mobile view.
So, btter solution is reduce the width/height of the `scroll-to-top` button in mobile view and increase the bottom value such that the button lies in between the subscribe button the policies. And, increase the top margin a bit for the terms, status line.

2023-03-10 18:56 UTC, parmishh commented
@Nikhil-Ladha thanks for suggestions I have changed the approach!
I have made the scrolltotop button smaller and given bottom so that it does not cover the terms button.
Have a look.
<img width="380" alt="ll" src="https://user-images.githubusercontent.com/91942072/224402721-32632346-a67e-4440-9a3c-4e00c5c924df.PNG">

2023-03-10 19:11 UTC, l5io commented
🚀 Preview for commit fae6f564eb9b5dbce9a0effbb46dfc598990319d at: https://640b807341acc82523df9ef8--layer5.netlify.app

2023-03-10 20:05 UTC, Nikhil-Ladha commented
The scroll-to-top button is now positioned incorrectly even for desktop view, along with that the size is reduced as well.
Those changes should be limited to mobile view only, probably after (leess than) a screen resolution of 600px or so. Please check that and update the code accordingly, and check for responsiveness before re-requesting for review and by that I mean do your due intelligence 🙏🏼

2023-03-10 20:07 UTC, Nikhil-Ladha commented
And, also update the PR title to be something more meanigful and descriptive.

2023-03-11 07:06 UTC, closed without merging