margin added to subscribe button
layer5io/layer5 pull request #3948
Opened 2023-03-12 04:53 UTC by ShravaniAK

**Description**

This PR fixes #3897 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-03-12 05:16 UTC, l5io commented
🚀 Preview for commit 0546ff8f258dfd09c56298b517bcb3d6307d53c4 at: https://640d5f89e2d91e2c1fea5822--layer5.netlify.app

2023-03-13 05:46 UTC, Chadha93 commented
@ShravaniAK  Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

2023-03-13 06:49 UTC, Nikhil-Ladha commented on src/sections/General/Footer/footer.style.js
> +			margin-bottom:14px;
Let's limit this proprty to mobile view only, and update the value to `0.75rem` instead of using `px`

2023-03-17 07:05 UTC, leecalcote requested changes
Pending incorporation of Nikhil's feedback.

2023-03-17 20:07 UTC, l5io commented
🚀 Preview for commit d9f8012afd2c8c1fe9ff77dffb56956724749158 at: https://6414c7d9a5113f2d7cbaec1d--layer5.netlify.app

2023-03-18 07:34 UTC, Nikhil-Ladha commented on src/sections/General/Footer/footer.style.js
> +			margin-bottom:14px;
This is still not implemented correctly.
You will need to use a media query to address this comment.

2023-03-18 14:13 UTC, hirentimbadiya reviewed
as @Nikhil-Ladha said @ShravaniAK has made changes for px to rem but didn't implemented media queries to address the commit.

2023-03-24 16:47 UTC, l5io commented
🚀 Preview for commit e7b825c89dd857fc27cf259497a16d2865725a0f at: https://641dd379c88dc1108760b63f--layer5.netlify.app

2023-03-24 19:34 UTC, Nikhil-Ladha approved these changes
lgtm!
Thank you @ShravaniAK 🙏🏼

2023-03-24 19:34 UTC, merged