Update k8s-multi-cluster.mdx
layer5io/layer5 pull request #4030
Opened 2023-04-01 06:24 UTC by ShivangShandilya

**Description**

This PR fixes #3995 

**Notes for Reviewers**

The commented blog can now be viewed.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-04-03 15:45 UTC, thisiskaransgit approved these changes

2023-04-04 12:20 UTC, l5io commented
🚀 Preview for commit 76b0fbe0de7ddf396e8d489f4177469efc965465 at: https://642c15fb22909c136842cf99--layer5.netlify.app

2023-04-07 13:36 UTC, l5io commented
🚀 Preview for commit 212928dd7115f882db66d81c95b7b36f826c1463 at: https://64301b70fd33ef40bdae09b5--layer5.netlify.app

2023-04-09 15:42 UTC, leecalcote requested changes
Thank you, gents. I wonder if we might have this hyperlink changed to use the `<Link>` component. The `<Link>` component is to be used for all internal site links, while the `<a>` tags are for any external site links.

2023-04-09 16:57 UTC, ShivangShandilya commented
> Thank you, gents. I wonder if we might have this hyperlink changed to use the `<Link>` component. The `<Link>` component is to be used for all internal site links, while the `<a>` tags are for any external site links.

hmm, I think we can do that

2023-04-09 17:08 UTC, ShivangShandilya commented
> Thank you, gents. I wonder if we might have this hyperlink changed to use the `<Link>` component. The `<Link>` component is to be used for all internal site links, while the `<a>` tags are for any external site links.

@leecalcote I think I was able to do what you were asking for, mind taking a look if it's correct or not?

2023-04-09 17:25 UTC, l5io commented
🚀 Preview for commit 78b62f6e9cf380f3a944e25df1a3ac3c8cb125e2 at: https://6432f4b55f3163426e5b856a--layer5.netlify.app

2023-04-10 19:52 UTC, leecalcote commented on src/collections/resources/articles/kubernetes/multi-cluster/k8s-multi-cluster.mdx
> +Learn more about how to wrangle <Link to= "https://layer5.io/blog/meshery/multi-cluster-kubernetes-management-with-meshery">Multiple Kubernetes clusters with Meshery.</Link>
```suggestion
Learn more about how to wrangle <Link to= "/blog/meshery/multi-cluster-kubernetes-management-with-meshery">Multiple Kubernetes clusters with Meshery.</Link>
```

2023-04-10 19:52 UTC, leecalcote approved these changes
Given that they are all intra-site, the `https://layer5.io` portion is assumed, so we're safe to leave it out. 👍

2023-04-10 19:53 UTC, merged

2023-04-10 19:53 UTC, leecalcote commented
Thank you, @ShivangShandilya 👍

2023-04-11 09:15 UTC, ShivangShandilya commented
> Given that they are all intra-site, the `https://layer5.io` portion is assumed, so we're safe to leave it out. 👍

Noted 😁