Issue-4059 changed color of Open Scenario in Hover mode
layer5io/layer5 pull request #4068
Opened 2023-04-06 13:36 UTC by hirentimbadiya

**Description**

This PR fixes #4059 

**Notes for Reviewers**

https://user-images.githubusercontent.com/86219935/230394345-75be4055-45e5-4f2c-8f05-ccc33c9e4743.mp4

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-04-06 13:37 UTC, hirentimbadiya commented
Please Review this PR , @leecalcote , @Chadha93 , @Nikhil-Ladha  , @Shivam-AfA

2023-04-06 13:51 UTC, leecalcote commented
@hirentimbadiya review the lighthouse checks for this change and confirm that no issues are reported (that is, assuming that lighthouse checks are covering this page, @ayushthe1 )

2023-04-06 13:56 UTC, l5io commented
🚀 Preview for commit 7c03ba79c010f8f9084c10b707dbf62036ceedd0 at: https://642ecf0f4dc2124586f1b931--layer5.netlify.app

2023-04-06 14:03 UTC, ayushthe1 requested changes
Just undo the changes you have done in package-lock.json. Else it's good.

2023-04-06 14:17 UTC, hirentimbadiya commented on package-lock.json
> +        "gatsby-plugin-sitemap": "^5.19.0",
when i ran make site command it automatically changed to this. should i revert it back ? @ayushthe1

2023-04-06 15:25 UTC, hirentimbadiya commented
> Just undo the changes you have done in package-lock.json. Else it's good.

Okay!

2023-04-06 15:52 UTC, l5io commented
🚀 Preview for commit a44d449f4c23eec2cafe53336a1728ab85902613 at: https://642eea0c346c8600bf0004d5--layer5.netlify.app

2023-04-07 05:03 UTC, l5io commented
🚀 Preview for commit 3ff31325e56a7f9a93326c6ca53bfee9fef44051 at: https://642fa3a45b894a626a8be1b4--layer5.netlify.app

2023-04-07 06:04 UTC, ayushthe1 approved these changes
good to go now :+1:

2023-04-07 10:25 UTC, hirentimbadiya commented
@leecalcote can you review this now ?

2023-04-07 12:43 UTC, thisiskaransgit approved these changes
Looks good to merge, thank you for your contribution :tada:

2023-04-07 19:44 UTC, leecalcote approved these changes
Thank you, gents.

2023-04-08 03:55 UTC, l5io commented
🚀 Preview for commit 00454c76e471678c1a406cb1a7d1eebe3dd71148 at: https://6430e505f7271a46b0cfd099--layer5.netlify.app

2023-04-09 04:49 UTC, l5io commented
🚀 Preview for commit 05b7ef6c9468edaddda1cdb468215372b117defd at: https://643243bea308c14498b303a6--layer5.netlify.app

2023-04-09 16:21 UTC, merged