Added image feature to Inline-Quotes
layer5io/layer5 pull request #4100
Opened 2023-04-15 13:04 UTC by Saksham294

**Description**

This PR fixes #4097 
This PR adds user images to inline testimonials

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-04-15 13:06 UTC, Saksham294 commented
I have added the feature of user images to in-line testimonials. I couldn't find photos of two people so would need help in that regard, apart from that we can surely discuss about the design changes expected and I would do the needful.
Thanks

2023-04-15 13:23 UTC, l5io commented
🚀 Preview for commit a6f4f840a0b1d73da523f08bcbde8c8b85881b18 at: https://643aa4cadbdcc42205059e09--layer5.netlify.app

2023-04-15 17:31 UTC, leecalcote requested changes

2023-04-15 17:31 UTC, leecalcote commented on src/components/Inline-quotes/index.js
> +        height: 90px;
@Saksham294 let's make this responsive with use of max-height, %s, or some other dynamic CSS approach.

2023-04-15 17:32 UTC, leecalcote commented
Thanks, @Saksham294! 👏

2023-04-15 19:56 UTC, Shivam-AfA reviewed
Thanks @Saksham294 for this! I wonder if it would look better if we place the image on the left hand side of the person's name, rather than on top of it.

2023-04-17 14:52 UTC, Saksham294 commented
Hey @leecalcote , I made the requested changes for the image tag and made it responsive.

2023-04-17 15:34 UTC, l5io commented
🚀 Preview for commit 55d28507e6660af850a762ce9a2c2e796c32ced5 at: https://643d662b3c846f30a1a60e82--layer5.netlify.app

2023-04-17 21:51 UTC, Shivam-AfA reviewed
@Saksham294 It looks good to me. 

To aid the correct positioning of longer names and titles, you can try increasing padding around the name and title box.

2023-04-18 04:22 UTC, Saksham294 commented
@Shivam-AfA if you think the changes are fine, then I think we can merge this PR

2023-04-18 17:28 UTC, Saksham294 commented
Forgot to mention, we still need photographs of a few people in the testimonials

2023-04-18 17:31 UTC, Shivam-AfA commented
Please correct the padding as well @Saksham294

2023-04-18 17:34 UTC, Saksham294 commented
<img width="1189" alt="Screenshot 2023-04-18 at 11 03 39 PM" src="https://user-images.githubusercontent.com/86240862/232858209-4ae18a6f-6c22-4d89-8f4b-483ccb1caaba.png">
Does this look fine?

2023-04-18 17:37 UTC, Saksham294 commented
<img width="1193" alt="Screenshot 2023-04-18 at 11 06 04 PM" src="https://user-images.githubusercontent.com/86240862/232858654-5f80774f-b288-4a78-90a1-858724bf2466.png">
Or this one?

2023-04-19 08:17 UTC, Saksham294 commented
@Shivam-AfA I have made the changes, kindly check. Thanks

2023-04-19 08:42 UTC, l5io commented
🚀 Preview for commit 8cd5cf8c00b03e63e4a45ac34cea12752876bd52 at: https://643fa8d71f987c7c8ca0ea4f--layer5.netlify.app

2023-04-19 19:28 UTC, leecalcote commented
@Shivam-AfA good to go?

2023-04-20 06:41 UTC, Shivam-AfA commented on src/components/Inline-quotes/index.js
> +    @media screen and (max-width: 600px) {
@Saksham294 Please remove this media query if it's not being used.

2023-04-20 07:04 UTC, Shivam-AfA commented
@leecalcote Looks good to me. However, we don't have images of the users for all the quotes on the meshmap page. Is it fine? 

@Saksham294 While you're in there, could you add the user images to the quotes on the meshery page as well?  https://layer5.io/cloud-native-management/meshery

2023-04-20 07:47 UTC, Saksham294 commented
@Shivam-AfA Do we have images for these users? Also as mentioned earlier I can't find images of some users for the meshmap page too

2023-04-20 07:48 UTC, Shivam-AfA commented
Yes we have the images for them @Saksham294

2023-04-20 08:02 UTC, Saksham294 commented
@Shivam-AfA I can't the remaining images for the meshmap page but meshery page is done

2023-04-20 08:13 UTC, Saksham294 commented
Some merge conflict happened, I don't know why

2023-04-21 13:27 UTC, l5io commented
🚀 Preview for commit f93d00e57ba1997abedb2176c1d75f7ade582204 at: https://64428ed6092a1974410d30ca--layer5.netlify.app

2023-04-23 12:13 UTC, Shivam-AfA commented
@Saksham294 Please correct the responsiveness as well.

![image](https://user-images.githubusercontent.com/88040318/233839119-d5150872-d0e3-460f-ade6-de2a6a42c1aa.png)

Also using `width: 5rem` for the image isn't dynamic, please use something in terms of % or vw.

2023-04-24 21:32 UTC, leecalcote commented
Still spilling over. 
<img width="275" alt="Screenshot 2023-04-24 at 4 31 58 PM" src="https://user-images.githubusercontent.com/7570704/234121521-4d927621-c384-490a-a056-292d6ed824ad.png">

2023-04-24 22:17 UTC, l5io commented
🚀 Preview for commit a430484855f71641a36a5fa6837c36af89e255b0 at: https://6446ff69e5b1502751cba7b0--layer5.netlify.app

2023-04-24 22:31 UTC, merged