navbar floating on the logo bug fixed
layer5io/layer5 pull request #4121
Opened 2023-04-23 04:43 UTC by shibu-g

**Description**

This PR fixes #4117

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
-[]Yes, I signed my commits.
  Yes, I signed my commits.

2023-04-23 05:02 UTC, l5io commented
🚀 Preview for commit b9c5285cf47db17c165f68f9900a8f04a9b24a82 at: https://6444bb502b67275bce1e90c5--layer5.netlify.app

2023-04-23 11:01 UTC, Shivam-AfA commented
Thanks @shibu-g for the fix.

2023-04-23 11:18 UTC, Shivam-AfA commented
You can correct the DCO error by going to the details link beside the failed DCO check.

2023-04-23 11:20 UTC, l5io commented
🚀 Preview for commit 1ad78c363564c7c93dc1f687784585512c3c98bf at: https://6445142ef368c51741284b7e--layer5.netlify.app

2023-04-23 15:03 UTC, thisiskaransgit requested changes
There's already a media query at line 410, to avoid redundancy move the CSS, to it  
```javascript
    @media screen and (max-width: 992px) and (min-width: 912px) {
      width: 125px;
    }
``` 

And the toggle theme is still being cut-off, look into that too

2023-04-23 15:05 UTC, shibu-g commented
> There's already a media query at line 410, to avoid redundancy move the CSS, to it  
> ```javascript
>     @media screen and (max-width: 992px) and (min-width: 912px) {
>       width: 125px;
>     }
> ``` 
> 
> And the toggle theme is still being cut-off, look into that too
> 
> 
> 

Yes thanks for pointing this out i will definitely  do it 👍

2023-04-24 04:52 UTC, l5io commented
🚀 Preview for commit 84efe0fca44145624a235ae2494c9a7bb468b357 at: https://64460a8b788e667241de8e10--layer5.netlify.app

2023-04-24 05:54 UTC, Shivam-AfA commented
Thanx @shibu-g for this.

2023-04-24 06:10 UTC, l5io commented
🚀 Preview for commit 272014e29f80a2d00836a61a39e53d2cdea775e1 at: https://64461cc103dc5f7ae12df15b--layer5.netlify.app

2023-04-24 06:29 UTC, shibu-g commented
> Thanx @shibu-g for this. Can you sign off your commits please?

Actually this time I did signoff on my commit.

2023-04-24 08:36 UTC, Shivam-AfA commented
You need to sign off the previous commits as well

2023-04-24 11:02 UTC, shibu-g commented
> You need to sign off the previous commits as well

i have tryed soo many method but not work 
i have try these method
  git rebase HEAD~4 --signoff
  git rebase -i HEAD~4
  git commit --amend --no-edit -s
nothing works
   how can i do this?

2023-04-24 11:11 UTC, Shivam-AfA commented
@shibu-g 
Head over to this link and follow the steps: https://github.com/layer5io/layer5/pull/4121/checks?check_run_id=12964987112

2023-04-24 11:44 UTC, Chadha93 commented
@shibu-g Let's discuss this on the Websites call starting in 15 minutes. Please add this as an agenda, if you would. https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#

2023-04-24 13:03 UTC, leecalcote commented
DCO manually cleared, @shibu-g 👍

2023-04-24 13:05 UTC, leecalcote commented on src/sections/General/Navigation/navigation.style.js
> +      margin-left: 22px;
```suggestion
      margin-left: 1.375rem;
```

Prefer `rem`.

2023-04-24 13:50 UTC, l5io commented
🚀 Preview for commit 488e5474a4fc6b2fe721c8d0c516b6332a91da38 at: https://644688acb39df43367cd57cf--layer5.netlify.app

2023-04-24 17:31 UTC, merged