Adding Playground popup to home page
layer5io/layer5 pull request #4291
Opened 2023-05-25 08:39 UTC by Shivam-AfA

**Description**

This PR fixes #4276 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-05-25 08:43 UTC, Shivam-AfA commented
@leecalcote This PR adds the playground popup on the home page. The popup is displayed after 2 seconds when the page loads. Users will be able to see the popup only once. Currently I have used an SVG created by @ritiksaxena124 for the content of the popup.

Here's how the popup looks like:

![image](https://github.com/layer5io/layer5/assets/88040318/2c3654e0-ad24-4131-9423-0603e63bf36b)

2023-05-25 08:50 UTC, ritiksaxena124 commented
just a suggestion, we can increase the opacity of the black overlay so that the pop is in more focus, something like [this](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=14019%3A37063&t=3J4FtMWggxoj7Ckv-1)

2023-05-25 08:52 UTC, Shivam-AfA commented
Sure. I'll also add the drop shadow around the popup.

2023-05-25 09:00 UTC, l5io commented
🚀 Preview for commit 9117540c20491345587029d5e3df666743d32daf at: https://646f230e30dd6c20da5cc767--layer5.netlify.app

2023-05-25 16:37 UTC, l5io commented
🚀 Preview for commit 95ca403339b9063ceb057dcb7cd8f726a7e57d26 at: https://646f8e805186751f6f9cd2ac--layer5.netlify.app

2023-05-25 20:17 UTC, leecalcote commented
@Shivam-AfA @ritiksaxena124 Great work. Suggestions:

1) allow users to dismiss by clicking anywhere other than the modal.
2) make the entire modal / popup clickable in addition to the button.
3) keep this implementation, but also create a second implementation that we might use instead:
 --  change this to a popup in the lower, right hand corner that can be ignored if so desired and not a full-screen modal the forces the visitor to interact with it.

2023-05-25 21:01 UTC, Chadha93 commented on src/components/Playground-popup/index.js
> +
Let's wrap this in clickaway - https://www.npmjs.com/package/react-click-away-listener.

2023-05-25 23:14 UTC, leecalcote commented
Do we really need another package for listening to a click away event? If so, that's fine.

2023-05-28 12:16 UTC, Shivam-AfA commented
>Do we really need another package for listening to a click away event? If so, that's fine.
@Chadha93 @leecalcote I tried doing it without the package and was succesful. So there's no need for this now. I have added the suggested functionality.

2023-05-28 12:39 UTC, l5io commented
🚀 Preview for commit 488bf296e8adb50437dcc00c8984aed4089b3e0a at: https://64734b367d4ce0316d31a295--layer5.netlify.app

2023-05-28 12:42 UTC, leecalcote commented
@Shivam-AfA, let’s delay this popup until after 8 seconds. 

I mobile view, this popup still displays as a full-screen modal. The lower, right hand corner EOS what we’re looking for, though.

2023-05-28 13:14 UTC, Shivam-AfA commented
@leecalcote I'll make another PR for a popup at the lower right hand corner of the screen. 

However, I have doubts if we should use that implementation for smaller screens, since it will be difficult to see such a small sized image.

2023-05-28 13:35 UTC, leecalcote requested changes
Thanks much. We don't want a full-screen modal, though. They are off-putting to our audience. 

In terms of mobile, yes, the lower right-hand corner is very much feasible. Use a different graphic / design for mobile.

2023-05-28 14:14 UTC, Shivam-AfA commented
> Thanks much. We don't want a full-screen modal, though. They are off-putting to our audience. 
> 
> In terms of mobile, yes, the lower right-hand corner is very much feasible. Use a different graphic / design for mobile. 

Noted.

2023-05-29 20:39 UTC, leecalcote commented
@Shivam-AfA yes, we'll need a different graphic for the small-sized mobile popup. // @ritiksaxena124

2023-06-01 00:28 UTC, closed without merging