Edit page
layer5io/layer5 pull request #4310
Opened 2023-05-29 16:50 UTC by 8rxn

**Description**

This PR fixes #4297 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-05-29 17:21 UTC, l5io commented
🚀 Preview for commit e3b0495749373ef1986cfe73e75a01a7b158816f at: https://6474de915889952dcf239c1f--layer5.netlify.app

2023-06-01 00:31 UTC, leecalcote commented
@8rxn _hint_: you should only need to be concerned linking to the respective page here: https://github.com/layer5io/layer5/tree/master/src/pages. Beyond this, we won't be able to navigate contributors to the specific component. In some cases, they'll have to navigate to more deeply beyond the page source link. // @Shivam-AfA

2023-06-01 04:56 UTC, 8rxn commented
> @8rxn _hint_: you should only need to be concerned linking to the respective page here: https://github.com/layer5io/layer5/tree/master/src/pages. Beyond this, we won't be able to navigate contributors to the specific component. In some cases, they'll have to navigate to more deeply beyond the page source link. // @Shivam-AfA 

Thanks @leecalcote for the insight

Indeed that's what I am implementing. 
Created a template string than resulted in the file url on github depending upon the `location` prop.

2023-06-01 16:37 UTC, 8rxn commented
Done with the implementation. Open to Reviews.
![image](https://github.com/layer5io/layer5/assets/75237697/17e25406-cc17-44fa-bae1-8f21ed4b77df)

2023-06-01 17:06 UTC, 8rxn commented
Made a few more commits:

Deleted files accidentally pushed. Fixed the pathname, should not be failing anymore, missed footer-landscape-page for footer, added that.

2023-06-01 21:48 UTC, l5io commented
🚀 Preview for commit d16d1d670b7d637334e9230db4f116830c6fa52e at: https://647911dd932d58184e48d0f4--layer5.netlify.app

2023-06-01 21:54 UTC, 8rxn commented
Implemented fixes pointed by @randychilau on slack. 
Link works 🚀

2023-06-02 20:09 UTC, Shivam-AfA commented
@8rxn Thanks for this!

2023-06-02 20:13 UTC, 8rxn commented
> @8rxn Thanks for this! Let's showcase your efforts and ask for feedback on Monday's websites call before getting it live.

Sure @Shivam-AfA 
I do believe that there could maybe be some polish needed. 
I changed a large number of files so it was kind of hard to track whether or not everything works flawlessly or not. 
However I did test a few different type of pages and this seemed perfectly but I could have missed something or the other.

2023-06-03 04:16 UTC, Nikhil-Ladha requested changes
Few issues needed to be taken care of:
The hover effect on the link is incorrect. The cursor changes to pointer on the `Get Involved` heading as well, which should not be the case. Also, restrict the width to `fit-content` such that the whole row (upto the column width) is not hoerable and only the text is.

Since, you have removed the `Footer` component from the `Layout` component all the collection pages like blogs, resources etc doesn't have the `Footer` now (eg: https://647911dd932d58184e48d0f4--layer5.netlify.app/blog/community/building-amazing-open-source-tools-one-contributor-at-a-time). That has to be fixed. You could handle these cases by pointing them to individual pages. Also, keep in mind that the content for `learning-paths` is stored in a separate directory named `content-learn` so a special case for that needs to be handled as well.
Secondly, what if we pass the location property to the `Footer` component directly from the `Layout` compoonent, does it not get the actual page location in its porps?

2023-06-03 04:35 UTC, 8rxn commented
Thanks for the insights  @Nikhil-Ladha 
I'll be taking care of these issues.
Regarding the `Layout`, the `location` prop is only accessible from inside the pages, hence it does not work that way. I did try that beforehand just to avoid changing a large number of files.

2023-06-04 13:22 UTC, 8rxn commented
With great help from @randychilau , I have worked on the issue in another branch with a better implementation and created a new PR for the same.
The changes requested in this PR have been implemented on that branch. Link to new PR : #4334 
Requesting reviews from @Nikhil-Ladha

2023-06-04 13:23 UTC, closed without merging