[UX] Graphic Design: Create a Layer5-branded 3D book to represent the Community Handbook
layer5io/layer5 pull request #4392
Opened 2023-06-17 07:56 UTC by Savio629

**Description**
[UX] Graphic Design: Created a Layer5-branded 3D book to represent the Community Handbook

This PR fixes #4075 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-06-17 08:10 UTC, l5io commented
🚀 Preview for commit d29b4b1006409f7c5be886ba7e6faec7a92b9211 at: https://648d69ff73a33f6183c9dff1--layer5.netlify.app

2023-06-17 08:52 UTC, Savio629 commented
![chlayer](https://github.com/layer5io/layer5/assets/91362589/b661c782-6bfa-486c-8d22-e3b2a340030e)

@thisiskaransgit @vishalvivekm 
Do we need light design for dark mode?
Because the mentioned light design for dark mode doesn't fit well with the theme - #4075

2023-06-17 12:20 UTC, thisiskaransgit commented
@Savio629,  The current change looks good to me. Better if we discuss it at the website meeting.

2023-06-17 20:46 UTC, leecalcote requested changes
@randychilau how does this PR fit / not fit with our approach to light vs dark mode flicker prevention?

2023-06-17 20:46 UTC, leecalcote commented on src/sections/Community/Handbook/BookComponent/BookComponent.js
> +    <a
Are we able to use a `<Link>` here? Use Link for site internal links like this one where possible.

2023-06-17 20:46 UTC, leecalcote commented on src/sections/Community/Handbook/BookComponent/BookComponent.js
> +          src="https://user-images.githubusercontent.com/91362589/245493993-1780f4f9-b332-4b91-95ac-841013624b86.png"
Do not use an external reference like this. Use a site-local image.

2023-06-17 20:46 UTC, leecalcote commented on src/sections/Community/Handbook/BookComponent/BookComponent.js
> +          src="https://user-images.githubusercontent.com/91362589/245493993-1780f4f9-b332-4b91-95ac-841013624b86.png"
Use SVGs, not PNGs, please.

2023-06-18 19:29 UTC, randychilau commented
> @randychilau how does this PR fit / not fit with our approach to light vs dark mode flicker prevention?

Hi @leecalcote,

I reviewed this PR and didn't notice any flicker issues with regards to light vs. dark mode  (even when refreshing):

[3dbook2.webm](https://github.com/layer5io/layer5/assets/90356410/ab010e8a-4860-4ac5-8bf9-d52427bbc66e)

However I did notice that the book image can take a moment to load when doing a "hard refresh", momentarily presenting a blank book while the image loaded:

[3dbook3.webm](https://github.com/layer5io/layer5/assets/90356410/956b1070-0e2f-404d-a558-4efe66ad1192)

This can be due to a couple of factors:
- size of the image file 
  ![image](https://github.com/layer5io/layer5/assets/90356410/34bd4499-5cfa-4146-b340-21efe1dd7d9a)
  - due to image dimensions
  - file format
- image being stored outside of the site and remotely accessed (as Lee mentioned)

Potential changes to resolve the issue:
- resize the file to be smaller dimensions (keeping aspect ratio)
- change the file format from png to either SVG or webp
- change the file location to be stored in the site

Hope that helps.

Cheers,
Randy

2023-06-18 20:32 UTC, Savio629 commented
Was going to convert the png into webp and then use it as a site-local image but forgot to mentioned it her...

2023-06-18 20:55 UTC, l5io commented
🚀 Preview for commit d2cc5610638214af48b99666fa09ea57b026fe09 at: https://648f6eed2348aa6d36ce6335--layer5.netlify.app

2023-06-19 04:03 UTC, vishalvivekm commented
@Savio629 Let's discuss this on websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would :)

2023-06-25 20:57 UTC, Savio629 commented
@Chadha93 
Added rotation on reload and decreased a little bit of shadow...
https://github.com/layer5io/layer5/assets/91362589/31cac91b-c395-48f2-bfb1-4f5d84390e03

2023-06-25 20:59 UTC, leecalcote commented
@Savio629 it seems that we should get this book on the /community page and/or the /handbook page, too.

2023-06-25 21:00 UTC, leecalcote approved these changes

2023-06-25 21:00 UTC, merged

2023-06-25 21:00 UTC, leecalcote commented
Looks great!

2023-06-25 21:09 UTC, Savio629 commented
> @Savio629 it seems that we should get this book on the /community page and/or the /handbook page, too.

As it is redirecting to handbook page itself we can maybe add it to community page...
I'll add it in website's meeting agenda.

2023-06-25 21:16 UTC, leecalcote commented
Sounds real good.