Added member profile for Vaibhav bisht
layer5io/layer5 pull request #4443
Opened 2023-06-27 13:14 UTC by DarrenDsouza7273

**Description**
Added the member profile for Vaibhav 
This PR fixes #4438 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-06-27 13:31 UTC, l5io commented
🚀 Preview for commit eaf696afe7a46aeff85f19f1642326dcb40a027b at: https://649ae46ca0fd760a573e99a4--layer5.netlify.app

2023-06-27 14:04 UTC, DarrenDsouza7273 commented
@vaibhav135

2023-06-28 07:10 UTC, DarrenDsouza7273 commented
@Chadha93

2023-06-28 07:29 UTC, l5io commented
🚀 Preview for commit 1856d93cf63c5b34a222e791a9460a284ada2e65 at: https://649be0d4617c61443031df89--layer5.netlify.app

2023-06-28 13:27 UTC, hirentimbadiya requested changes
Change the twitter username with the correct one.

2023-06-28 13:27 UTC, hirentimbadiya commented on src/collections/members/vaibhav-bisht/index.mdx
> +twitter: Vaibhav_bisht
Vaibhav_Bisht

2023-06-28 13:29 UTC, vaibhav135 commented
@DarrenDsouza7273 Yes LGTM 🚀

2023-06-28 13:41 UTC, DarrenDsouza7273 commented
@hirentimbadiya done

2023-06-28 13:56 UTC, l5io commented
🚀 Preview for commit 63ee533c9234f668ee5ed6960c546298e87d3d80 at: https://649c3b772402b80d2362fa4d--layer5.netlify.app

2023-06-29 02:46 UTC, hirentimbadiya approved these changes
LGTM ✅

2023-06-29 06:54 UTC, l5io commented
🚀 Preview for commit 6a59e38a974d9eb9f04ea3232632a8d3c05d3d0c at: https://649d2a603b49663d39127c86--layer5.netlify.app

2023-06-29 07:05 UTC, goldfishdolphin commented
Looking good 👍🏽

2023-06-29 09:22 UTC, Chadha93 approved these changes
LGTM

2023-06-29 09:22 UTC, merged

2023-06-29 09:22 UTC, Chadha93 commented
Yay @vaibhav135 :balloon: