fix: Enhance and place graphic onto about page
layer5io/layer5 pull request #4471
Opened 2023-07-02 06:10 UTC by anikdhabal

**Description**

This PR fixes #4404 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-07-02 06:26 UTC, l5io commented
🚀 Preview for commit 8592d9fdc14827cb4a737cf6c61a39215ee2f7fb at: https://64a117f10e35132b944027e5--layer5.netlify.app

2023-07-02 11:52 UTC, l5io commented
🚀 Preview for commit e2b29e38bf3fc977e35416448176fedf51fb7f04 at: https://64a16494bad6fb43ba41281f--layer5.netlify.app

2023-07-03 06:45 UTC, vishalvivekm commented
@anikdhabal Please sign off your commits. 
Follow the instructions: https://github.com/layer5io/layer5/pull/4471/checks?check_run_id=14717816428

2023-07-03 07:36 UTC, anikdhabal commented
> @anikdhabal Please sign off your commits. Follow the instructions: https://github.com/layer5io/layer5/pull/4471/checks?check_run_id=14717816428
> 
> Also, let's discuss this on websites meeting today at 5:30 PM IST. Add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit).

Yes, I've already sign of in my latest commit.

2023-07-09 07:18 UTC, samyakshah3008 commented
@anikdhabal  Let's discuss this on Websites Meeting call on Monday. Please add this as an agenda item in the [meeting mintes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would. :)

2023-07-10 06:46 UTC, anikdhabal commented
@leecalcote can you review this PR?

2023-07-12 18:01 UTC, l5io commented
🚀 Preview for commit f4934d55628fa2bafe429262a3a8f2125ee78bfa at: https://64aeea51b7f58010877fad13--layer5.netlify.app

2023-07-12 18:24 UTC, leecalcote requested changes

2023-07-12 18:24 UTC, leecalcote commented on src/sections/Company/About/images/layer5-community-stat.svg
Thanks for this effort.

We can't have an outline around the our mascot (the stick figure).

2023-07-12 19:33 UTC, anikdhabal commented on src/sections/Company/About/images/layer5-community-stat.svg
ok, thank you

2023-07-15 04:42 UTC, l5io commented
🚀 Preview for commit 2cf04f17af2c5b5a8eaf72b060530558df15eb7d at: https://64b22379c648544b91359742--layer5.netlify.app

2023-07-19 18:09 UTC, l5io commented
🚀 Preview for commit dd17b8a7dcaa1d1e6f356e24b6b7e2e265206054 at: https://64b826a608cd9e0c2bb953f7--layer5.netlify.app

2023-07-19 18:31 UTC, l5io commented
🚀 Preview for commit 5079fdb906760d48a426ddecdc6c6fb87b99762a at: https://64b82bc57d7c3312f9c631b2--layer5.netlify.app

2023-07-19 20:42 UTC, leecalcote approved these changes
Excellent, @anikdhabal

2023-07-19 20:43 UTC, leecalcote commented
@anikdhabal, let's do this: replace the CNCF logo with this new infographic. The infographic should be displayed smaller than it currently is.

2023-07-20 14:34 UTC, anikdhabal commented
> @anikdhabal, let's do this: replace the CNCF logo with this new infographic. The infographic should be displayed smaller than it currently is.

Done

2023-07-20 14:47 UTC, samyakshah3008 approved these changes

2023-07-26 21:45 UTC, merged

2023-07-26 21:46 UTC, Chadha93 commented
Thank you gents.