feat:added blog for meshmap
layer5io/layer5 pull request #4537
Opened 2023-07-13 11:23 UTC by Ghat0tkach

**Description**

This PR fixes #4520 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-07-13 11:49 UTC, l5io commented
🚀 Preview for commit f10913fe323aade4a8bd4340b42da2bf23cfe443 at: https://64afe46fa7039811efbfd09c--layer5.netlify.app

2023-07-13 11:54 UTC, theBeginner86 commented on src/collections/blog/2023/2023-7-13-meshmap-guide-for-newcomers/index.mdx
> +<h2>Why Meshmap??</h2>
```suggestion
<h2>Why Meshmap?</h2> 
```

2023-07-13 11:57 UTC, leecalcote commented on src/collections/blog/2023/2023-7-13-meshmap-guide-for-newcomers/index.mdx
> +<h2>Why Meshmap??</h2>
Capitalize both “m”s

2023-07-13 11:57 UTC, Ghat0tkach commented on src/collections/blog/2023/2023-7-13-meshmap-guide-for-newcomers/index.mdx
> +<h2>Why Meshmap??</h2>
Thank you @theBeginner86

2023-07-13 12:36 UTC, l5io commented
🚀 Preview for commit ae237b1f3fb873d9559f6de694082a3c6cea2316 at: https://64afef83d035c316d7606ef3--layer5.netlify.app

2023-07-15 04:43 UTC, hirentimbadiya reviewed
We can also specify an 'alt' tag in the 'img' attribute to provide alternative text for the images. Other than that, everything looks good to merge.

2023-07-15 11:00 UTC, Ghat0tkach commented
> We can also specify an 'alt' tag in the 'img' attribute to provide alternative text for the images. Other than that, everything looks good to merge.

Thank you for the feedback  , added the alt tags as well!

2023-07-15 11:14 UTC, l5io commented
🚀 Preview for commit fca2a8ff5239ef68cd920ce072ebfc2029fe4290 at: https://64b27f049a72cb7a84efdf80--layer5.netlify.app

2023-07-16 09:42 UTC, vishalvivekm commented
@Ghat0tkach 

Let's discuss it on the websites call.
Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima), if you would :)

2023-07-17 11:07 UTC, l5io commented
🚀 Preview for commit e4d0a27d42db08424a4a32304a2fcba53abeab22 at: https://64b520cd8d78930f097ffe5b--layer5.netlify.app

2023-07-25 14:50 UTC, l5io commented
🚀 Preview for commit f2f7924559e9a441534327f8d1264813ec75c54f at: https://64bfe0e4679db90b0e277ca3--layer5.netlify.app

2023-07-28 20:13 UTC, Chadha93 requested changes
@Ghat0tkach, You can add links to meshery docs for publishing designs, and replace the video with "how to publish design".  
1. Docs - https://docs.meshery.io/extensions/publishing-a-design.
2. Video - https://www.youtube.com/watch?v=UCKS4eSB7AY

2023-07-28 20:50 UTC, Ghat0tkach commented
@Chadha93 Thanks again , I will also need to add the design and community member profile

2023-07-29 18:24 UTC, l5io commented
🚀 Preview for commit 996852bc2afb9e81b493d697c759c8c1564e7863 at: https://64c558bece1ad713497f7df4--layer5.netlify.app

2023-07-29 18:52 UTC, l5io commented
🚀 Preview for commit be908721b1d82ddc3b841f0e3ea3741c56b523af at: https://64c55fbc61f7c9126830c8d8--layer5.netlify.app

2023-07-29 19:13 UTC, l5io commented
🚀 Preview for commit 5e4a5968b27f567a29942c96847a35e1f9363345 at: https://64c5642a4de7b11617518e9e--layer5.netlify.app

2023-07-29 20:06 UTC, Ghat0tkach commented
Update : There is some issue in responsiveness since my member profile get added automatically .
Will fix this soon

2023-08-01 10:55 UTC, l5io commented
🚀 Preview for commit 5416962d6c12fb64b473cf5d07e09f6f522ba693 at: https://64c8e46752a8f46f13b2ee95--layer5.netlify.app

2023-08-11 16:12 UTC, l5io commented
🚀 Preview for commit fa45edb6580c6bec8eef8d60cde8ae83bb1d00db at: https://64d65dc554f3687d19ce58b9--layer5.netlify.app

2023-08-12 13:38 UTC, abhijeetgauravm commented
> 🚀 Preview for commit [fa45edb](https://github.com/layer5io/layer5/commit/fa45edb6580c6bec8eef8d60cde8ae83bb1d00db) at: https://64d65dc554f3687d19ce58b9--layer5.netlify.app

![image](https://github.com/layer5io/layer5/assets/65087356/04754f12-2f45-4097-917a-2f7635cbced5)
last linking sentence @Ghat0tkach ok?

2023-08-12 22:09 UTC, Ghat0tkach commented
> > 🚀 Preview for commit [fa45edb](https://github.com/layer5io/layer5/commit/fa45edb6580c6bec8eef8d60cde8ae83bb1d00db) at: https://64d65dc554f3687d19ce58b9--layer5.netlify.app
> 
> ![image](https://user-images.githubusercontent.com/65087356/260232220-04754f12-2f45-4097-917a-2f7635cbced5.png) last linking sentence @Ghat0tkach ok?

Thank you @abhijeetgauravm !🙌

2023-08-12 22:24 UTC, l5io commented
🚀 Preview for commit 31f614e854d15ab2b0bc0d27a8630e082a1966fb at: https://64d806560c870d3e79251df3--layer5.netlify.app

2023-08-13 12:01 UTC, abhijeetgauravm commented
> 🚀 Preview for commit [31f614e](https://github.com/layer5io/layer5/commit/31f614e854d15ab2b0bc0d27a8630e082a1966fb) at: https://64d806560c870d3e79251df3--layer5.netlify.app

![image](https://github.com/layer5io/layer5/assets/65087356/e8dafb17-6e97-47ac-877b-17b7bbdcc61d)
hey @Ghat0tkach won't it look much appealing when  sentences between both images would be at top of the second image or somewhere else?

2023-08-23 20:42 UTC, Chadha93 commented
> > 🚀 Preview for commit [31f614e](https://github.com/layer5io/layer5/commit/31f614e854d15ab2b0bc0d27a8630e082a1966fb) at: [64d806560c870d3e79251df3--layer5.netlify.app](https://64d806560c870d3e79251df3--layer5.netlify.app)
> 
> ![image](https://user-images.githubusercontent.com/65087356/260301198-e8dafb17-6e97-47ac-877b-17b7bbdcc61d.png) hey @Ghat0tkach won't it look much appealing when sentences between both images would be at top of the second image or somewhere else?

@Ghat0tkach, thoughts?

2023-08-24 10:56 UTC, Ghat0tkach commented
> Member



> > > 🚀 Preview for commit [31f614e](https://github.com/layer5io/layer5/commit/31f614e854d15ab2b0bc0d27a8630e082a1966fb) at: [64d806560c870d3e79251df3--layer5.netlify.app](https://64d806560c870d3e79251df3--layer5.netlify.app)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/65087356/260301198-e8dafb17-6e97-47ac-877b-17b7bbdcc61d.png) hey @Ghat0tkach won't it look much appealing when sentences between both images would be at top of the second image or somewhere else?
> 
> @Ghat0tkach, thoughts?

Yup , seems good !

2023-09-24 19:39 UTC, l5io commented
🚀 Preview for commit 03cd8388504360b4760d7e4392eb4e3c35afb1af at: https://6510900d6686c813419ab732--layer5.netlify.app

2023-10-01 06:34 UTC, Ghat0tkach commented
please have a review , gents

2023-10-01 17:54 UTC, leecalcote commented
@Ghat0tkach, let's hold off on this until we officially launch MeshMap.

2024-03-18 11:03 UTC, iArchitSharma commented
@vishalvivekm is it ready to merge

2024-04-18 15:54 UTC, closed without merging