closes #3797 fixed toolkit
layer5io/layer5 pull request #4543
Opened 2023-07-14 13:45 UTC by ranjanmangla1

**Description**

This PR fixes #3797

**Notes for Reviewers**
I have fixed toolkit issues that were coming in @DarrenDsouza7273 's pr #4436

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-07-14 13:51 UTC, DarrenDsouza7273 commented
will get back to you once the review is available

2023-07-14 13:59 UTC, l5io commented
🚀 Preview for commit 068b5b4e54e65ad9f36c7c1ee4d1909d007e0ec3 at: https://64b1548a5c42291dda6879b8--layer5.netlify.app

2023-07-14 14:15 UTC, DarrenDsouza7273 commented
Looks better but still would want @Chadha93 @leecalcote to have a look at it

2023-07-14 18:12 UTC, Ghat0tkach commented
@ranjanmangla1  , actually the service mesh performance are missing in profiles. Please have a look again , also there is some tiny minute misalignment of arrow for meshery logo

2023-07-14 18:13 UTC, Ghat0tkach commented
@ranjanmangla1  , actually the service mesh performance are missing in profiles. Please have a look again , also there is some tiny minute misalignment of arrow for meshery logo

2023-07-14 18:18 UTC, Ghat0tkach requested changes
Add smp badge as well

2023-07-14 18:18 UTC, Ghat0tkach commented on src/sections/Community/Member-single/index.js
> +                      <Badge name="Meshery" to="/cloud-native-management/meshery" className="profile-social-links" src={mesheryLogo} alt="Meshery logo" firstChild={true}/>
add smp badge as well , below this one😅

2023-07-17 09:53 UTC, vishalvivekm commented
@ranjanmangla1 Let's discuss it on the websites call. Add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima), if you would :)

2023-07-29 13:55 UTC, DarrenDsouza7273 commented
@ranjanmangla1 hi ranjan  can u please update on this fix

2023-08-23 17:51 UTC, closed without merging

2023-08-23 17:51 UTC, Chadha93 commented
@ranjanmangla1 Given no response from you here, I'm closing this PR, let's open this for another contributor.