updates for figma links
layer5io/layer5 pull request #4553
Opened 2023-07-15 17:37 UTC by depleur

**Description**

This PR fixes #4534

**Notes for Reviewers**
This PR fixes issue template updates for Figma links in certain files.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-07-15 17:45 UTC, Ghat0tkach commented
@depleur Good work!!
Please sign your commits as well 
Refer [here](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits)

2023-07-15 17:49 UTC, l5io commented
🚀 Preview for commit 3de00c54357d957eff3eac9c2a8145523946459d at: https://64b2dc0f29229931320679a3--layer5.netlify.app

2023-07-16 02:56 UTC, leecalcote requested changes

2023-07-16 02:56 UTC, leecalcote commented on .github/ISSUE_TEMPLATE/bug_report.md
Retain "Layer5 site". This is the https://layer5.io site repo, not the Meshery UI repo.

2023-07-16 09:39 UTC, vishalvivekm commented
@depleur 
Please sign off your commits.

Let's discuss it on the websites call.
Add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima), if you would :)

2023-07-18 05:15 UTC, depleur commented on .github/ISSUE_TEMPLATE/bug_report.md
So I'm assuming even the hyperlink needs to be changed to an appropriate Layer5 Figma page?

2023-07-18 16:20 UTC, thisiskaransgit requested changes
@depleur, incorporate these changes and we're good to go

2023-07-19 05:16 UTC, l5io commented
🚀 Preview for commit 2a18fadac153674ff74056ddada3fe991ba7826a at: https://64b7713aad95e249132cb019--layer5.netlify.app

2023-07-22 17:44 UTC, HarshDobariya79 commented
@depleur your commits are failing DCO checks. Please refer to https://discuss.layer5.io/t/dco-test-in-pr-failed/2836/2 to resolve that.

2023-07-23 06:39 UTC, abhijeetgauravm commented
I want to work on it. Can u assign?

2023-07-24 19:12 UTC, Chadha93 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
@thisiskaransgit Why Mehsery Figma here? Maybe I'm overlooking...

2023-07-24 19:22 UTC, abhijeetgauravm commented
Can I work on this issue?

2023-07-25 16:45 UTC, depleur commented
Hey, I've signed this off now so you can look into merging it. Sorry for the delay.

2023-07-25 20:31 UTC, thisiskaransgit commented on .github/ISSUE_TEMPLATE/feature_request.md
> + 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
```suggestion
 - 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
```

2023-07-25 20:35 UTC, thisiskaransgit reviewed
@depleur incorporate these, rest all looks good

2023-07-25 20:35 UTC, thisiskaransgit commented on .github/ISSUE_TEMPLATE/feature_request.md
> + 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
```suggestion
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
```

2023-07-25 20:35 UTC, thisiskaransgit commented on .github/ISSUE_TEMPLATE/chore_task.md
> +- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
```suggestion
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

```

2023-07-25 20:55 UTC, leecalcote commented
@thisiskaransgit thank you for taking care of this PR.

2023-07-25 20:55 UTC, merged