Added Member profile for meyazhagan
layer5io/layer5 pull request #4557
Opened 2023-07-16 18:31 UTC by shubhsingh5901

**Description**

This PR fixes #4517 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-07-16 18:45 UTC, l5io commented
🚀 Preview for commit ebe64f2e96829a341db1f23aa211c6f3c5f877f5 at: https://64b43a848ca8dd646732a844--layer5.netlify.app

2023-07-17 10:31 UTC, Shivam-AfA commented
@shubhsingh5901 Please sign-off on your commits.

2023-07-22 13:37 UTC, Ghat0tkach commented
The @Meyazhagan bio looks plain empty . Please toss your bio @Meyazhagan , so @shubhsingh5901 can add it in your member profile

2023-07-23 11:31 UTC, vishalvivekm commented
> @Meyazhagan's bio looks plain empty . Please toss your bio @Meyazhagan , so @shubhsingh5901 can add it in your member profile

// @Meyazhagan

2023-07-23 11:33 UTC, vishalvivekm commented
@shubhsingh5901 Please sign off your commit. Use the steps mentioned here: https://github.com/layer5io/layer5/pull/4557/checks?check_run_id=15080563213

2023-07-23 11:45 UTC, Meyazhagan commented
@vishalvivekm @Ghat0tkach 

Here is the update bio

> Hi! I’m Meyazhagan, an Experienced Full Stack Developer with expertise in React, TypeScript, and Golang. Passionate about creating responsive web apps with a focus on design, security, and performance. Interested in Cloud Native projects, open-source tech, and improving software practices. Contributing to the Layer5 organization aligns with my values, allowing me to build impactful work for the community.

2023-07-23 11:48 UTC, vishalvivekm requested changes
@shubhsingh5901

2023-07-23 11:48 UTC, vishalvivekm commented on src/collections/members/meyazhagan/index.mdx
> +bio: I am a software developer.
```suggestion
bio: "Hi! I’m Meyazhagan, an Experienced Full Stack Developer with expertise in React, TypeScript, and Golang. Passionate about creating responsive web apps with a focus on design, security, and performance. Interested in Cloud Native projects, open-source tech, and improving software practices. Contributing to the Layer5 organization aligns with my values, allowing me to build impactful work for the community."
```

2023-07-24 16:03 UTC, shubhsingh5901 commented on src/collections/members/meyazhagan/index.mdx
> +bio: I am a software developer.
sure will do that.

2023-07-24 18:55 UTC, Chadha93 approved these changes

2023-07-24 18:55 UTC, Chadha93 commented
Thank you gents.

2023-07-24 18:55 UTC, merged