Add og image for five adventure page and update lfx term 03 dates
layer5io/layer5 pull request #4633
Opened 2023-07-26 18:02 UTC by vishalvivekm

**Description**

This PR 
- adds og image for [adventures-of-five-and-friends](https://layer5.io/community/adventures-of-five-and-friends)
- udpates lfx term 03 dates

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-07-26 18:24 UTC, l5io commented
🚀 Preview for commit a534603f2a85b2091fee0afb8ac484c0ea4d951a at: https://64c164945a7e6631f107da61--layer5.netlify.app

2023-07-26 18:32 UTC, leecalcote requested changes

2023-07-26 18:32 UTC, leecalcote commented on static/images/meet-five.svg
REMINDER: Please use a PNG for all OpenGraph images.

2023-07-26 18:33 UTC, leecalcote commented on static/images/meet-five.svg
Also, please keep the OpenGraph image in the same component / section.

2023-07-27 08:45 UTC, vishalvivekm commented on static/images/meet-five.svg
Yes @leecalcote . Actually my build is failing locally after I pulled latest from upstream.
I'll get it fixed and then SVG -> PNG , upload the png in the same location

2023-07-27 20:07 UTC, leecalcote approved these changes

2023-07-27 20:07 UTC, leecalcote commented on static/images/meet-five.svg
Ok, a follow up PR...

2023-07-27 20:10 UTC, merged