fixing hover effect on cards on News page
layer5io/layer5 pull request #4691
Opened 2023-08-04 07:29 UTC by VamshiReddy02

**Description**

This PR fixes #4470

I'm sorry for closing my Last PR because of some technical issues. As you all suggested I added Margin to the images and reduced their size also, please let me know of any changes.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-08-04 07:47 UTC, l5io commented
🚀 Preview for commit 34515fa159adebe19c960407cc2e4ced757fd6ae at: https://64ccac8c0ad7296318b84040--layer5.netlify.app

2023-08-04 18:20 UTC, Ghat0tkach commented
Hey @VamshiReddy02 

 Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

2023-08-05 10:15 UTC, hirentimbadiya approved these changes
LGTM 👍🏻

2023-08-10 14:36 UTC, abhijeetgauravm approved these changes
LGTM !

2023-08-10 16:12 UTC, HetviSoni requested changes
+1 to @abhijeetgauravm 's point and also one more. The bottom of this image is getting cut even before we hover 
<img width="299" alt="image" src="https://github.com/layer5io/layer5/assets/76479104/38f9f3c2-c769-488d-bbfc-e46aa9f2244b">

2023-08-10 16:57 UTC, l5io commented
🚀 Preview for commit ecbd9f7b7d06e0f0afb0df196ea766eedc275b2b at: https://64d516ba8eac69031382dbd6--layer5.netlify.app

2023-08-10 17:05 UTC, VamshiReddy02 commented
Hey @abhijeetgauravm and @HetviSoni, I made some changes. Please Review my changes again and please let me know of any changes.

2023-08-10 17:46 UTC, HetviSoni commented on src/components/Card/Card.style.js
> +            margin-left: 3rem;
Here you have explicitly added margin-left as 3rem which is causing alignment issues on some screen size between desktop and mobile(image is not in center of the card).

Maybe you can try 
`margin:auto;
margin-top:0.5rem; `
<img width="418" alt="image" src="https://github.com/layer5io/layer5/assets/76479104/37578d27-0eb1-4ceb-abcb-1a4c1c24c1af">

2023-08-10 17:47 UTC, HetviSoni commented on src/components/Card/Card.style.js
> +            margin-left: 3rem;
Well good work @VamshiReddy02 it is working for the desktop screen.

2023-08-10 18:18 UTC, l5io commented
🚀 Preview for commit 2bd692f94264bdcfd0edaee68582c2c07224de38 at: https://64d529b3903428009dc8d570--layer5.netlify.app

2023-08-10 18:39 UTC, HetviSoni approved these changes
Good work @VamshiReddy02 😄

2023-08-10 19:07 UTC, abhijeetgauravm approved these changes
Looks Good @VamshiReddy02

2023-08-11 15:33 UTC, thisiskaransgit requested changes
@VamshiReddy02 Not quite,
- too much padding in directions where it was not needed
- updating classes' styles that are assigned to multiple elements will have effects, go to /resources, and /blog sections to review the changes.

We needed to specifically update the particular section's elements. Since the images are of different dimensions, we cannot ensure to prevent image overflow for each of them.  

@VamshiReddy02 @HetviSoni, please conclude this task by this week

2023-08-11 19:47 UTC, l5io commented
🚀 Preview for commit 99ddeb81b1618839c4ae10ae3c9133ead7d38775 at: https://64d68fbcfaf31907e05eeff1--layer5.netlify.app

2023-08-13 03:37 UTC, HetviSoni commented
LGTM now

2023-08-13 16:15 UTC, vishalvivekm commented
@VamshiReddy02 Let's discuss it on the websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima), if you would :)

2023-08-15 09:59 UTC, VamshiReddy02 commented
hello everyone, please let me know of any changes.

2023-08-15 10:23 UTC, HetviSoni approved these changes

2023-08-23 17:31 UTC, Chadha93 approved these changes
Thanks @VamshiReddy02

2023-08-23 17:31 UTC, merged