4ddx:Fix/text-color-hover-handbook
layer5io/layer5 pull request #4707
Opened 2023-08-07 19:10 UTC by 4ddx

Signed-off-by: Ishan Kumar <ishanakshar@gmail.com>
**Description**

This PR fixes #4706 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.
 

fix text-color on hover at [page](https://layer5.io/community/handbook)

2023-08-07 19:24 UTC, l5io commented
🚀 Preview for commit a99a355115694753fbed9659183a79fbbeadbb84 at: https://64d1449325e28c1ed2e6e3c3--layer5.netlify.app

2023-08-08 05:31 UTC, 4ddx commented
@Ghat0tkach @leecalcote any updates on this pr?

2023-08-08 10:55 UTC, 4ddx reviewed
Self Reviewed. LGTM.

2023-08-09 11:08 UTC, thisiskaransgit requested changes
@4ddx, please refer to [contributing.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md), to understand how we reference color schemes.

2023-08-09 11:18 UTC, 4ddx commented
@thisiskaransgit white is a defined color in the color scheme ->lighttheme

 #4702  was merged and i had used "white".
Attaching image for your reference:

Thanks,
Best

![image](https://github.com/layer5io/layer5/assets/130624861/a14975de-cb56-49b0-ada2-58f4bc89dec3)

2023-08-10 02:26 UTC, leecalcote requested changes
> @4ddx, please refer to [contributing.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md), to understand how we reference color schemes.

@4ddx thanks for this PR. Please heed @thisiskaransgit's counsel. This site's approach to color theming is slightly different.

2023-08-10 03:36 UTC, 4ddx commented
@leecalcote I'm not quite sure I understand, I read through the contributing.md, went to themeStyles.js, and white is indeed a defined color

Sorry for the confusion

2023-08-10 05:41 UTC, leecalcote commented
Read more closely. https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#adding-dark-mode-for-components

2023-08-10 18:03 UTC, 4ddx commented
Hey @leecalcote I think we have a misunderstanding here.

It does not matter whether it's light mode, or dark mode, when hovered over, the text should be white.
This is exactly what issue #4615 was about.

What is it exactly that I'm missing? 

Thanks,
Best

2023-08-10 21:04 UTC, leecalcote commented
The difference is sustainability. It's better to have theme-based references; better to use the framework than to make absolute reference.

Example: In a couple of months from now, when the community decides that #FFFFFF (white) for text presented in dark mode, stings the eyes and it should be softened to #ECECECE (off-white). The difference is a one-line change versus crawling through hundreds of code files.

Does this help?

2023-08-11 11:07 UTC, l5io commented
🚀 Preview for commit 79eb9992fed8dd653cb605b3f4e6f2ede82fce53 at: https://64d6161ba3736a52863551dc--layer5.netlify.app

2023-08-13 05:03 UTC, Ghat0tkach commented
Hii @4ddx 

Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

2023-08-13 05:17 UTC, 4ddx commented
Hey @Ghat0tkach 

I'm denied access to the google link you sent, I just requested. Please check?

2023-08-13 05:21 UTC, Ghat0tkach commented
> Hey @Ghat0tkach 
> 
> I'm denied access to the google link you sent, I just requested. Please check?

Haven't you filled newcomers form which gives you access to a list of valuable resources? Or joined us on Slack yet?

2023-08-13 05:35 UTC, 4ddx commented
> > Hey @Ghat0tkach
> > I'm denied access to the google link you sent, I just requested. Please check?
> 
> Haven't you filled newcomers form which gives you access to a list of valuable resources? Or joined us on Slack yet?

I'm on slack, but haven't filled any newcomers form

2023-08-13 05:46 UTC, 4ddx commented
Okay, I just filled out the form as well

2023-08-19 20:52 UTC, thisiskaransgit requested changes

2023-08-19 20:52 UTC, thisiskaransgit commented on src/components/HandbookCard/HandbookCard.style.js
> +	  color: ${props => props.theme.navigatorColor};
```suggestion
	  color: ${props => props.theme.white};
```

2023-08-19 20:53 UTC, thisiskaransgit commented on src/components/HandbookCard/HandbookCard.style.js
> +	  color: ${props => props.theme.navigatorColor};
@4ddx, do this and we're good to go

2023-08-20 05:19 UTC, 4ddx commented
Hey, my bad i forgot to sign-off

2023-08-20 05:42 UTC, 4ddx commented
Hi @thisiskaransgit  I'm having some troubles with the sign-off

I also opened another pull request, and closed it, sorry for that.

2023-08-20 05:49 UTC, l5io commented
🚀 Preview for commit 6ee18b52ab1e5077d823ee21635d3a5b0a733a01 at: https://64e1a901efff1a385b41a831--layer5.netlify.app

2023-08-20 06:17 UTC, 4ddx commented
@thisiskaransgit I'm having problems with rebasing.

I'll be closing this pull request and opening a new one. Sorry for the delay.

2023-08-20 06:17 UTC, closed without merging