Added New Event: IstioCon Virtual 2023
layer5io/layer5 pull request #4762
Opened 2023-08-18 17:20 UTC by malaviya-parth

**Description**

This PR fixes #4756

**Notes for Reviewers**
- Have added a link tag register here below the text
- Image resolution is the default provided

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-08-18 17:26 UTC, Chadha93 commented
Thanks for the PR @malaviya-parth. 

Will be merged after the 21st.

2023-08-18 17:34 UTC, l5io commented
🚀 Preview for commit b6f140e09142b1f24918c6fd50b56b0566f4a0ba at: https://64dfab776d07a002ea7bce85--layer5.netlify.app

2023-08-19 05:16 UTC, hirentimbadiya requested changes
@malaviya-parth, please undo the changes you made in package-lock.json file.

2023-08-19 05:59 UTC, l5io commented
🚀 Preview for commit 336d5b14c81007ff8059cac9fca0ff36882fba3f at: https://64e059acc07fa023080ce179--layer5.netlify.app

2023-08-19 07:06 UTC, Ghat0tkach commented
@malaviya-parth @Chadha93 

The PR looks good however a few enhancement needs to be done on the thumbnail image
![image](https://github.com/layer5io/layer5/assets/59855919/2beb757e-d584-4c0a-a424-2904ceb04923)

//
If we can alter-image , otherwise everything is Good⭐
It would be nice if the thumbnail image is 
![image](https://github.com/layer5io/layer5/assets/59855919/e7ab7960-f4e6-434a-b255-4f52a7405cee)

2023-08-19 07:43 UTC, malaviya-parth commented
@Ghat0tkach 
So should I change it with the image you provided? or wait for @Chadha93 's confirmation?

2023-08-19 07:46 UTC, Ghat0tkach commented
@malviya-parth lets wait for his confirmation😅

2023-08-20 13:12 UTC, Ghat0tkach commented
hey @malaviya-parth 

Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

2023-08-21 15:39 UTC, malaviya-parth commented
> hey @malaviya-parth
> 
> Let's discuss it on the websites call. Please add this as an agenda item in the meeting minutes, if you would :)
> 
> https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

Sorry I was not able to make it to the meeting due to some work, If any changes are required can you tell me. Once Again sorry for not attending.

2023-08-22 19:58 UTC, Chadha93 commented
> > hey @malaviya-parth
> > Let's discuss it on the websites call. Please add this as an agenda item in the meeting minutes, if you would :)
> > [docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima)
> 
> Sorry I was not able to make it to the meeting due to some work, If any changes are required can you tell me. Once Again sorry for not attending.

@malaviya-parth, Will you please update the thumbnail with the image @Ghat0tkach, provided?

2023-08-23 18:14 UTC, l5io commented
🚀 Preview for commit 637e02fdba75b4fc67d8bd48e33349ffe976b6e4 at: https://64e64c3ef7d9ad04784e5bae--layer5.netlify.app

2023-08-23 18:43 UTC, Chadha93 commented on src/collections/events/IstioCon 2023/index.mdx
> +published: true
```suggestion
published: true
resource: true
```

2023-08-23 19:04 UTC, l5io commented
🚀 Preview for commit b9ae0de2479dad8e01b87d8cb01b193d32569d1f at: https://64e657b0551e6411acc0d812--layer5.netlify.app

2023-08-23 19:07 UTC, Chadha93 approved these changes

2023-08-23 19:07 UTC, merged