adding-issue-valid-functionality
layer5io/layer5 pull request #4957
Opened 2023-09-23 15:26 UTC by PRANJALRANA11

**Description**

This PR fixes #4933 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-09-23 15:44 UTC, l5io commented
🚀 Preview for commit 7f44154f02d11902afa7dfc421ace4091ea627af at: https://650f074e5abffc3ce7699e79--layer5.netlify.app

2023-09-24 03:16 UTC, PRANJALRANA11 commented
@leecalcote please review the changes

2023-09-25 07:18 UTC, saurabh100ni commented
let's discuss this item on today's website meeting,
please add this agenda in the docs: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk

2023-09-27 14:50 UTC, l5io commented
🚀 Preview for commit f83368c049d598d65b297042a916d91132d202d8 at: https://651440cbd4ade4008fefbb9d--layer5.netlify.app

2023-09-27 16:59 UTC, sandramsc commented
Looks good @PRANJALRANA11, workflow includes support for support for _issue/valid_ and _help wanted_.I also used [YAMLlint](https://www.yamllint.com/) to validate the .yml file 👍🏽

2023-09-27 18:40 UTC, leecalcote commented
@sandramsc any grammatical corrections that you might suggest or rephrasing is most welcomed.

2023-09-27 19:26 UTC, sandramsc commented on .github/workflows/label-triggered.yml
> +              Thanks for opening this issue.It is a verified and valid issue you can take action in accordance
To increase readability I suggest restructuring this sentence to read as follows:
```suggestion
              Thank you for opening this issue. It has been verified and is considered a valid issue. You can now take action based on the provided issue description. 
```

2023-09-27 19:28 UTC, sandramsc commented on .github/workflows/label-triggered.yml
> +              Thanks for opening this issue.It is a verified and valid issue you can take action in accordance
To increase readability I suggest restructuring this sentence to read as follows:
```suggestion
              Thank you for opening this issue. It has been verified and is considered a valid issue. You can now take action based on the provided issue description. 
```

2023-09-27 19:29 UTC, sandramsc commented on .github/workflows/label-triggered.yml
> +              Thank you for opening this issue extra attention is needed for this issue.
To increase readability I suggest restructuring this sentence to read as follows:
```suggestion
             Thank you for opening this issue. It requires special attention, and we appreciate your contribution.
```

2023-09-27 19:32 UTC, sandramsc commented
> @sandramsc any grammatical corrections that you might suggest or rephrasing is most welcomed.

Hi Lee, yes, I've added some inline comments with suggestions. 👍🏽

2023-09-28 06:53 UTC, PRANJALRANA11 commented
@sandramsc commited that

2023-10-01 02:48 UTC, PRANJALRANA11 commented
@leecalcote will this be good to merge

2023-10-01 03:20 UTC, leecalcote commented
> @leecalcote will this be good to merge

Almost. The suggestion verbiage needs refinement.

2023-10-01 03:57 UTC, l5io commented
🚀 Preview for commit 4c5c307643e3a1d1fabe0a14272378d7f8cc9b76 at: https://6518edd058a2270c7fa4725f--layer5.netlify.app

2023-10-12 05:02 UTC, PRANJALRANA11 commented
is this refinement good or do i have to add some more

2023-10-12 11:38 UTC, leecalcote requested changes
@PRANJALRANA11, I'll offer a final round of feedback. If the next review requires more changes, let's closeout this PR and allow you to move onto another issue.

1. "You may now proceed with appropriate actions based on the provided issue description"

No, this is inaccurate.

2. The issue doesn't ask for a comment to be added on application of a "help wanted" label. Thanks for making consideration for one, however, this enhancement isn't desired.

2023-10-12 12:27 UTC, closed without merging