Fix[Added tooltip hover effect on the badges]
layer5io/layer5 pull request #5003
Opened 2023-10-04 16:47 UTC by ankushbhardwaj408

**Description**

This PR fixes #3797 
Added tooltip hover effect on the badges in individual member profile page.

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-10-04 17:07 UTC, l5io commented
🚀 Preview for commit 3f150a5f8636e7f42180398988746f5207b4cc74 at: https://651d9b7c0c65db236791fcd6--layer5.netlify.app

2023-10-05 18:59 UTC, DarrenDsouza7273 requested changes
Hello @ankushbhardwaj408 

Could you please bring up this topic during our upcoming weekly meeting?
I've noticed that the tooltips are still off-centered, and it might be helpful to increase the distance between the tooltips and the badges slightly. This would prevent them from overlapping with some of the badges.

Thank you

2023-10-06 03:18 UTC, ankushbhardwaj408 commented
Hi @DarrenDsouza7273 i will add this issue to the meeting agenda.

2023-10-07 11:30 UTC, l5io commented
🚀 Preview for commit ae2027cd5114999c86e6b4946356ed9607f1570e at: https://652141144195596901240d73--layer5.netlify.app

2023-10-07 11:58 UTC, l5io commented
🚀 Preview for commit d28c22750e398da94531f931f9670c081e5ccd3a at: https://652147a47dda7a6ff8ba7406--layer5.netlify.app

2023-10-07 12:25 UTC, l5io commented
🚀 Preview for commit 64fe283a84df28fc08e7256d94839d91292f6dea at: https://65214dc05f88896d9c583fc8--layer5.netlify.app

2023-10-07 14:05 UTC, ritiksaxena124 commented
Hey @ankushbhardwaj408 thanks for taking this up, could you please increase the size of text inside the tooltip to maybe 14px so that the name of the badge is visible more clearly?

2023-10-07 14:35 UTC, ankushbhardwaj408 commented
Sure @ritiksaxena124 on it.

2023-10-07 17:53 UTC, l5io commented
🚀 Preview for commit 3abd982419da8c58fb859b2b6a40b920ac589083 at: https://65219acf477a95215aa3700b--layer5.netlify.app

2023-10-07 18:15 UTC, l5io commented
🚀 Preview for commit fb62435072696f280882476d9bc2530947bd730b at: https://65219fac5f88891f05583fec--layer5.netlify.app

2023-10-09 04:51 UTC, abhijeetgauravm commented
Hey @ankushbhardwaj408 Let's discuss this on website call today at 5:30 PM IST / 7 AM Central time. Pleasde add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima)

2023-10-09 11:24 UTC, l5io commented
🚀 Preview for commit 63f485ea4b1d141650844909a609c3d2ed6a51f7 at: https://6523e27b54782b00873b5505--layer5.netlify.app

2023-10-10 06:47 UTC, ankushbhardwaj408 commented
https://github.com/layer5io/layer5/assets/93874580/89c263cd-b16b-487c-84a1-16f092b40251

@abhijeetgauravm @vishalvivekm @ritiksaxena124 @DarrenDsouza7273

2023-10-10 06:53 UTC, l5io commented
🚀 Preview for commit b6e93fd30a282acd1062e5fb938bc3e43039bca8 at: https://6524f49430106b17e6ac73a2--layer5.netlify.app

2023-10-12 06:52 UTC, abhijeetgauravm commented
> Recording.2023-10-10.120552.mp4 
> @abhijeetgauravm @vishalvivekm @ritiksaxena124 @DarrenDsouza7273

Looks good!

2023-10-12 14:04 UTC, l5io commented
🚀 Preview for commit 8ef701aa9dcb0f7d71d525e34d9f99c36594ce61 at: https://6527fca0b12eff1fe3dbbdbf--layer5.netlify.app

2023-10-15 14:12 UTC, ritiksaxena124 commented
Merge conflicts @ankushbhardwaj408

2023-10-15 14:17 UTC, ankushbhardwaj408 commented
@ritiksaxena124 i'll look into it

2023-10-18 05:23 UTC, l5io commented
🚀 Preview for commit 043a652aa5ff6028d5880f53f93600ad6f005711 at: https://652f6b817008be57444e8fb5--layer5.netlify.app

2023-10-18 05:25 UTC, ankushbhardwaj408 commented
@ritiksaxena124 all issues resolved.

2023-10-18 07:00 UTC, ritiksaxena124 commented
Great Looks good to me @ankushbhardwaj408 👏

2023-10-18 07:01 UTC, ritiksaxena124 approved these changes

2023-10-18 07:01 UTC, merged