Fixed all Grammatical typo's in README.md
layer5io/layer5 pull request #5004
Opened 2023-10-06 05:03 UTC by prakashAditya639

1 - In the sentence, "We empower developers to change how they write applications, support operators in rethinking how they run modern infrastructure," "rethinking" should be spelled as "re-think."

2 - In the "MeshMap" section, "deploy designs" should be "deploys designs" for proper verb agreement.

3 - In the "Meshery Operator" section, "Meshery operatorMeshery Operator deploys and manages MeshSync" lacks a space between "Meshery operator" and "Meshery Operator." It should be "Meshery operator - Meshery Operator deploys and manages MeshSync."

4 - In the "Community and Contributions" section, "whether your opening an issue or a pull requests" should be "whether you're opening an issue or a pull request" for proper grammar. Also, "pull requests" should be "pull request" if referring to a single action.

5 - In the "Community and Contributions" section, "Join us in the discussion forum and on Slack" should be "Join us in the discussion forum and on Slack" without an extra space before "Slack."

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-10-06 05:22 UTC, l5io commented
🚀 Preview for commit 23a3d4d9fe392cda6bff9af2dc9eed088d9ee6cb at: https://651f993d52eb965ffccbe31d--layer5.netlify.app

2023-10-07 18:06 UTC, leecalcote requested changes

2023-10-07 18:06 UTC, leecalcote commented on README.md
> +[Layer5](https://layer5.io)'s cloud native application and infrastructure management software enables organizations to expect more from their infrastructure. We embrace _developer_-defined infrastruc
Thanks for these corrections, @prakashAditya639. 👍 In this case, "rethinking" is grammatically correct. We'll want to leave this one as-is.

2023-10-07 18:06 UTC, leecalcote commented on README.md
> +<a href="https://layer5.io/meshmap">MeshMap</a> is an end-to-end management platform, here to help teams understand problems, deploys designs, apply patterns, manage and operate your deployments and
Incorrect. Please revert.

2023-10-07 18:06 UTC, leecalcote commented on README.md
> + <h2><a href="https://github.com/meshery/meshery-operator">Meshery Operator: </a></h2>
No thanks. Let's stay sans colon.

2023-10-07 18:06 UTC, leecalcote commented on README.md
> + <a href="https://github.com/layer5io/meshery-operator"> Meshery Operator</a> deploys and manages MeshSync.
Good.

2023-10-07 18:06 UTC, leecalcote commented on README.md
> +<p> We warmly welcome all contributors! Our projects are community-built and each welcomes open collaboration. As you get started, please review this project's <a href="https://github.com/layer5io/la
Good eye.

2023-10-07 18:06 UTC, leecalcote commented on README.md
> +  Join us in the <a href="https://discuss.layer5.io">discussion forum</a> and on <a href="https://slack.layer5.io"><img src=".github/assets/images/slack.webp" height="16px" align="bottom" />Slack</a>
Please revert given that this whitespace is for purposes of maintaining distance between the image and the word.

<img width="110" alt="Screenshot 2023-10-07 at 1 05 48 PM" src="https://github.com/layer5io/layer5/assets/7570704/3920db98-ff6f-42cd-b4f8-75072de3a26d">

2023-10-07 18:53 UTC, prakashAditya639 commented
Reverted Back all the changes you requested for.....

2023-10-08 00:03 UTC, leecalcote approved these changes
Thanks!

2023-10-08 00:03 UTC, merged