Added screenshots for epam integration
layer5io/layer5 pull request #5018
Opened 2023-10-09 18:00 UTC by ankushbhardwaj408

**Description**

This PR fixes #4829 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-10-09 18:18 UTC, l5io commented
🚀 Preview for commit fac9a58fd4a3639a2603780f94d44fa7c1e9c8a4 at: https://65244380f2a8d71ccddd98c8--layer5.netlify.app

2023-10-12 12:20 UTC, sandramsc requested changes
Hi, thank you for your contribution, please create new screenshot for visualizer as icons are missing from the canvas. View the comment on this [PR](https://github.com/layer5io/layer5/pull/4914#issuecomment-1734386234) for more context.

2023-10-12 12:34 UTC, ankushbhardwaj408 commented
Sure @sandramsc i'll work on it.

2023-10-12 14:02 UTC, l5io commented
🚀 Preview for commit 5759ab88e25b16ad035795b603f8418f86b2b46f at: https://6527fbd6dbaa8e1b51cd2e72--layer5.netlify.app

2023-10-15 16:56 UTC, l5io commented
🚀 Preview for commit 7da025b7c2b6098cb67e856e2fb06cb4678d667e at: https://652c196f0ec6f612db66d736--layer5.netlify.app

2023-10-16 06:49 UTC, saurabh100ni commented
Thanks for raising PR, Let's discuss this in the Website call today at 5:30 PM IST.
Please add this as your agenda in [Docs](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk)

2023-10-18 07:27 UTC, l5io commented
🚀 Preview for commit 68269f6e6cb28c97c4991bd0a08c19c16bc684fa at: https://652f887ea49f01639882b5ac--layer5.netlify.app

2023-10-20 04:44 UTC, l5io commented
🚀 Preview for commit 4a1489a98b5f6f1d271725493fa78fe4ed842320 at: https://6532050afd8e6c55bca590d4--layer5.netlify.app

2023-10-28 14:54 UTC, ankushbhardwaj408 commented
@sandramsc please review this pr.

2023-10-28 14:55 UTC, ankushbhardwaj408 commented
> Hi @ankushbhardwaj408 , thank you for your contribution, please create new screenshot for visualizer as icons are missing from the canvas. View the comment on this [PR](https://github.com/layer5io/layer5/pull/4914#issuecomment-1734386234) for more context.

@sandramsc please review this pr now.

2023-10-28 15:09 UTC, l5io commented
🚀 Preview for commit 4f74bc99690dc41263d86630542e626768d191bc at: https://653d23bd8abfc044241b810f--layer5.netlify.app

2023-10-30 06:06 UTC, Mohith234 commented
@ankushbhardwaj408 Let's discuss this on website call today at 5:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit).

2023-11-04 09:57 UTC, l5io commented
🚀 Preview for commit 178862a13ee1caf474d2649136a7c60a4c47cd5e at: https://65461539b9207a663c40abe1--layer5.netlify.app

2023-11-08 15:35 UTC, sudhanshutech commented
@ankushbhardwaj408 merge conflict

2023-11-13 16:30 UTC, ankushbhardwaj408 commented
@sudhanshutech merge conflicts resolved.

2023-11-13 16:42 UTC, l5io commented
🚀 Preview for commit 8f0a5845063c1659410df82896840cbf432d6a51 at: https://655251c3f309090077bfba1a--layer5.netlify.app

2023-11-14 14:17 UTC, l5io commented
🚀 Preview for commit 8c75a4dbc89818561401337d670f5bb59b1d8e2c at: https://6553812b9d19d20c028ef8b9--layer5.netlify.app

2023-11-16 04:13 UTC, l5io commented
🚀 Preview for commit 3d99681d910b949b0756503f35849282a796ee43 at: https://6555968b6c27593263ec5b9d--layer5.netlify.app

2023-11-22 10:51 UTC, l5io commented
🚀 Preview for commit c4d367ba5cb75f12fc031b2c4e4fd56b4bacf9a1 at: https://655ddcc5036f1f0e39c2ee7d--layer5.netlify.app

2023-11-27 12:38 UTC, ankushbhardwaj408 commented
https://655ddcc5036f1f0e39c2ee7d--layer5.netlify.app/cloud-native-management/meshery/integrations/epam-delivery-platform-edp-admin-console

2023-11-27 13:23 UTC, ankushbhardwaj408 commented
https://655ddcc5036f1f0e39c2ee7d--layer5.netlify.app/cloud-native-management/meshery/integrations/epam-delivery-platform-edp-admin-console

2023-12-03 15:40 UTC, leecalcote commented
@ankushbhardwaj408 I believe that @vishalvivekm is asking for changes.

2023-12-03 15:48 UTC, ankushbhardwaj408 commented
@leecalcote i was out of town. I'll get it done asap.

2023-12-03 17:32 UTC, l5io commented
🚀 Preview for commit ee1f9a45b2068bff78fa2f6dc07c92affa2be7bf at: https://656cbb35cb669e290e5bc1a2--layer5.netlify.app

2023-12-04 05:02 UTC, ankushbhardwaj408 commented
@leecalcote i am not able to commit new changes 
![Screenshot 2023-12-04 083449](https://github.com/layer5io/layer5/assets/93874580/ca3eb89f-b48c-46a9-be41-2443b7814c0c)
![Screenshot 2023-12-04 083420](https://github.com/layer5io/layer5/assets/93874580/e6656224-6ca1-4dd5-8788-a3a3c4347ef0)
I think this is due to embed tests in static folder. I have deleted the entire repo and restarted the local server but still this error is appearing while commiting

2023-12-04 09:36 UTC, vishalvivekm commented
> @leecalcote @vishalvivekm i am not able to commit new changes ![Screenshot 2023-12-04 083420](https://private-user-images.githubusercontent.com/93874580/287594939-e6656224-6ca1-4dd5-8788-a3a3c4347ef0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2ODIyNzAsIm5iZiI6MTcwMTY4MTk3MCwicGF0aCI6Ii85Mzg3NDU4MC8yODc1OTQ5MzktZTY2NTYyMjQtNmNhMS00ZGQ1LTg3ODgtYTNhM2M0MzQ3ZWYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDA5MjYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwOGE4ZjM0YmQ4MGFhZDlkZjZlOGU1ZjVjNjg0ZjUyMGZjNWM0NmZjNWYzN2ExZTQzN2M0Mjc5MmMxZmNjN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gxbcoO3CjNll3e6MsCeOkR-aazBXssJarTmgDRmlq3g) ![Screenshot 2023-12-04 083449](https://private-user-images.githubusercontent.com/93874580/287594934-ca3eb89f-b48c-46a9-be41-2443b7814c0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2ODIyNzAsIm5iZiI6MTcwMTY4MTk3MCwicGF0aCI6Ii85Mzg3NDU4MC8yODc1OTQ5MzQtY2EzZWI4OWYtYjQ4Yy00NmE5LWJlNDEtMjQ0M2I3ODE0YzBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDA5MjYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmODgyMjk4MzA2MzU2YTZjODEzMjNhYWFiYWJkMzliZGI4Y2EwYWNmNjRkMjcxMWJhYTNhMGMzZTE3ZTRiNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1umjVQegfzILnZ9T7OLi-2uExcBDlLmgShhyCiS-8lk)

Thanks for reporting this @ankushbhardwaj408.

2023-12-04 09:45 UTC, ankushbhardwaj408 commented
@vishalvivekm ??

2023-12-04 10:31 UTC, vishalvivekm commented on src/collections/integrations/_images/admin-console-operator/meshmap-epam-designer-dark.png
@ankushbhardwaj408 the folder in _images/ has to be named `epam-delivery-platform-edp-admin-console`

Here the title is : Epam Delivery Platform (EDP) Admin Console
its sluggified versoin: `epam-delivery-platform-edp-admin-console`

: https://github.com/layer5io/layer5/pull/5129#issue-1995493031

2023-12-04 10:33 UTC, ankushbhardwaj408 commented on src/collections/integrations/_images/admin-console-operator/meshmap-epam-designer-dark.png
Will change it🫡

2023-12-04 14:46 UTC, l5io commented
🚀 Preview for commit e8c9a12da81efe070cd3ab16b5a4db8448d72f38 at: https://656de5f3eb29fa00871c3719--layer5.netlify.app

2023-12-04 15:19 UTC, l5io commented
🚀 Preview for commit 214838a5ce0fa81b3f529e64e38ef865ff96fd31 at: https://656ded6f65c6b305ac017999--layer5.netlify.app

2023-12-04 18:04 UTC, l5io commented
🚀 Preview for commit a0506648b622c02c6f6117b0b18ed3332c25bcd6 at: https://656e1427fa1051009a473201--layer5.netlify.app

2023-12-04 18:35 UTC, l5io commented
🚀 Preview for commit 9083133da30d9596a827b3a16daeb6603dd62989 at: https://656e1bba569df9008c20047a--layer5.netlify.app

2023-12-04 18:38 UTC, vishalvivekm approved these changes
LGTM.
Thank you @ankushbhardwaj408

2023-12-04 18:38 UTC, merged