#5045: Made learning path cards mobile responsive
layer5io/layer5 pull request #5050
Opened 2023-10-17 13:03 UTC by arianxq

**Description**

This PR fixes #5045
This PR fixes the mobile responsiveness issue for the learning cards as mentioned in issue #5045.

**Notes for Reviewers**

Adjusted the CSS for better mobile responsiveness.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-10-17 13:25 UTC, l5io commented
🚀 Preview for commit 5db6e1000767573967e6591ec71232fa05fa5551 at: https://652e8ad59936d9009429aa89--layer5.netlify.app

2023-10-17 14:52 UTC, abhijeetgauravm requested changes
After the changes, now there are many inconsistencies visible at different screen sizes.

- cutting logo of layer5 and theme toggler at the both top left and right respectively .
- Similarly cards and description.

![image](https://github.com/layer5io/layer5/assets/65087356/bb56b638-28c6-44e8-98e7-aa876a854b2b)
![image](https://github.com/layer5io/layer5/assets/65087356/a40d2ad7-9e5b-4bf4-98c5-e72e0a12a7d5)
![image](https://github.com/layer5io/layer5/assets/65087356/d68bffe5-b50b-4390-8752-3a5f118132e4)
![image](https://github.com/layer5io/layer5/assets/65087356/840f8847-94be-48bb-adfb-38b0b9cd65b5)

Please make it consistent at every screen size.

2023-10-17 16:01 UTC, arianxq commented
> After the changes, now there are many inconsistencies visible at different screen sizes.
> 
> * cutting logo of layer5 and theme toggler at the both top left and right respectively .
> * Similarly cards and description.
> 
> ![image](https://user-images.githubusercontent.com/65087356/275871946-bb56b638-28c6-44e8-98e7-aa876a854b2b.png) ![image](https://user-images.githubusercontent.com/65087356/275872335-a40d2ad7-9e5b-4bf4-98c5-e72e0a12a7d5.png) ![image](https://user-images.githubusercontent.com/65087356/275872671-d68bffe5-b50b-4390-8752-3a5f118132e4.png) ![image](https://user-images.githubusercontent.com/65087356/275873460-840f8847-94be-48bb-adfb-38b0b9cd65b5.png)
> 
> Please make it consistent at every screen size.

Hi @abhijeetgauravm ,

Thank you for feedback.

I've tested the changes on my local setup using the screen sizes you mentioned, and I wasn't able to reproduce the issues you've pointed out. Here's what I've done:
Used developer tools to simulate the exact screen sizes you mentioned.
Ensured my browser zoom level was set to 100%.
Tested on Chrome.

<img width="772" alt="1" src="https://github.com/layer5io/layer5/assets/122199576/d8690f40-b75f-4b8c-aad9-11c860b2450d">
<img width="773" alt="2" src="https://github.com/layer5io/layer5/assets/122199576/1d91d751-1559-4e93-a706-399f5db0c318">
<img width="772" alt="3" src="https://github.com/layer5io/layer5/assets/122199576/9c88833f-b970-4928-90cb-964a42400f80">
<img width="774" alt="4" src="https://github.com/layer5io/layer5/assets/122199576/48d01dc3-a1bf-4d61-99ef-20d054ea2d25">
<img width="770" alt="5" src="https://github.com/layer5io/layer5/assets/122199576/28a33828-98d9-4a91-955a-243a7bb810c5">

2023-10-17 19:04 UTC, abhijeetgauravm commented
> > After the changes, now there are many inconsistencies visible at different screen sizes.
> > 
> > * cutting logo of layer5 and theme toggler at the both top left and right respectively .
> > * Similarly cards and description.
> > 
> > ![image](https://user-images.githubusercontent.com/65087356/275871946-bb56b638-28c6-44e8-98e7-aa876a854b2b.png) ![image](https://user-images.githubusercontent.com/65087356/275872335-a40d2ad7-9e5b-4bf4-98c5-e72e0a12a7d5.png) ![image](https://user-images.githubusercontent.com/65087356/275872671-d68bffe5-b50b-4390-8752-3a5f118132e4.png) ![image](https://user-images.githubusercontent.com/65087356/275873460-840f8847-94be-48bb-adfb-38b0b9cd65b5.png)
> > Please make it consistent at every screen size.
> 
> Hi @abhijeetgauravm ,
> 
> Thank you for feedback.
> 
> I've tested the changes on my local setup using the screen sizes you mentioned, and I wasn't able to reproduce the issues you've pointed out. Here's what I've done: Used developer tools to simulate the exact screen sizes you mentioned. Ensured my browser zoom level was set to 100%. Tested on Chrome.
> 
> <img alt="1" width="772" src="https://user-images.githubusercontent.com/122199576/275900958-d8690f40-b75f-4b8c-aad9-11c860b2450d.png"> <img alt="2" width="773" src="https://user-images.githubusercontent.com/122199576/275901014-1d91d751-1559-4e93-a706-399f5db0c318.png"> <img alt="3" width="772" src="https://user-images.githubusercontent.com/122199576/275901056-9c88833f-b970-4928-90cb-964a42400f80.png"> <img alt="4" width="774" src="https://user-images.githubusercontent.com/122199576/275901105-48d01dc3-a1bf-4d61-99ef-20d054ea2d25.png"> <img alt="5" width="770" src="https://user-images.githubusercontent.com/122199576/275901113-28a33828-98d9-4a91-955a-243a7bb810c5.png">

Yeah @arianxq looks like i was having some issue in edge browser. It looks good now thanks for the contribution!

2023-10-18 02:47 UTC, arianxq commented
before
![275329466-1a2738b1-e030-4608-bfc6-5aa4bb3c1257](https://github.com/layer5io/layer5/assets/122199576/f096cb99-b701-4bbe-a787-ffe89461d361)
now
<img width="770" alt="5" src="https://github.com/layer5io/layer5/assets/122199576/ae63bb89-e7f7-4921-bce1-b79308009ef6">

2023-10-18 02:51 UTC, arianxq commented
<img width="326" alt="5" src="https://github.com/layer5io/layer5/assets/122199576/c23adea2-d14b-4e39-a017-f2b77cdbffaf">

2023-10-19 05:45 UTC, l5io commented
🚀 Preview for commit 3097004e8678cb76000649f3fd4102e8504f02ea at: https://6530c23943164a72e0e33715--layer5.netlify.app

2023-10-19 06:30 UTC, arianxq commented
Sure @Mohith234, updated!

<img width="289" alt="1" src="https://github.com/layer5io/layer5/assets/122199576/6042a28c-e488-488d-8a48-94e5e432b0b3">

2023-10-19 21:57 UTC, leecalcote commented
Thanks for this, @arianxq 👍

2023-10-23 06:07 UTC, saurabh100ni commented
Hey @arianxq  Let's discuss this on website call tomorrow at 5:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

2023-10-25 04:35 UTC, sudhanshutech approved these changes
LGTM

2023-10-25 04:35 UTC, merged