Added new member - Hauwa Ismail Ahmad
layer5io/layer5 pull request #5073
Opened 2023-10-22 16:40 UTC by IrfanSalim

**Description**

This PR fixes #5071 

**Notes for Reviewers**
Added the folder using the profile template, however on the member's page, was not able to see the newly added member.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-10-22 16:59 UTC, l5io commented
🚀 Preview for commit d8201a2c70fbfc15246bb14395103bd3e41de6ed at: https://6535546fd9bdce08bd8c934d--layer5.netlify.app

2023-10-22 17:15 UTC, abhijeetgauravm commented on src/collections/members/hauwa-ismail-ahmad/index.mdx
> +layer5:
Here empty github user handle, cloud user id and location is causing the error, you are facing in preview!

2023-10-22 18:09 UTC, vishalvivekm commented on src/collections/members/hauwa-ismail-ahmad/index.mdx
> +github:
```suggestion
```

2023-10-22 18:14 UTC, vishalvivekm commented on src/collections/members/hauwa-ismail-ahmad/index.mdx
> +location:
```suggestion
location: Sokoto, Nigeria
```

2023-10-22 18:15 UTC, vishalvivekm commented on src/collections/members/hauwa-ismail-ahmad/index.mdx
> +status: Active
```suggestion
status: Active
published: true
```

2023-10-22 18:16 UTC, vishalvivekm requested changes
@IrfanSalim

2023-10-22 18:17 UTC, vishalvivekm commented on src/collections/members/hauwa-ismail-ahmad/index.mdx
> +layer5:
```suggestion
```

2023-10-22 18:21 UTC, vishalvivekm commented on src/collections/members/hauwa-ismail-ahmad/index.mdx
> +linkedin: hauwa-ismail-75224a255
```suggestion
linkedin: hauwa-ismail-ahmad-75224a255
```

2023-10-22 18:37 UTC, l5io commented
🚀 Preview for commit 890c659a7e5e0d32b63fd4879ccb07de3406aa94 at: https://65356ba057ebb91a8d9f6eb2--layer5.netlify.app

2023-10-22 18:42 UTC, vishalvivekm approved these changes

2023-10-23 06:05 UTC, saurabh100ni commented
Hey @IrfanSalim  Let's discuss this on website call tomorrow at 5:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

2023-10-23 08:09 UTC, vishalvivekm commented
Thank you! @IrfanSalim

2023-10-23 08:09 UTC, merged

2023-10-23 08:12 UTC, IrfanSalim commented
> Thank you! @IrfanSalim

Glad I could help, I added the agenda for the connect today as suggested by @saurabh100ni, should I remove that since this is merged?

2023-10-23 10:22 UTC, abhijeetgauravm commented
> > Thank you! @IrfanSalim
> 
> Glad I could help, I added the agenda for the connect today as suggested by @saurabh100ni, should I remove that since this is merged?

Yeah you can @IrfanSalim !