Community Profile Daniel Kiptoon
layer5io/layer5 pull request #5078
Opened 2023-10-23 18:40 UTC by KiptoonKipkurui

**Description**
This is a community profile for Daniel Kiptoon
This PR fixes #5026 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-10-23 18:51 UTC, vishalvivekm approved these changes
## Yay!🎈@KiptoonKipkurui 😎

2023-10-23 18:55 UTC, l5io commented
🚀 Preview for commit 8f379e1e85470054b3815e3ed926a6449dae3347 at: https://6536c17563684c744e904256--layer5.netlify.app

2023-10-23 19:28 UTC, vishalvivekm commented on src/collections/members/daniel-kiptoon/index.mdx
> +maintainer: no
```suggestion
```

2023-10-23 19:29 UTC, vishalvivekm requested changes

2023-10-23 19:29 UTC, vishalvivekm commented on src/collections/members/daniel-kiptoon/index.mdx
> +maintainer: no
> @vishalvivekm I wonder though why its made me a MeshMate even though I haven't explicitly configured it in the template

@KiptoonKipkurui removing this line fixes it. Seems to me a potential bug though.

2023-10-23 19:30 UTC, vishalvivekm commented on src/collections/members/daniel-kiptoon/index.mdx
> +maintainer: no
> @vishalvivekm I wonder though why its made me a MeshMate even though I haven't explicitly configured it in the template

@KiptoonKipkurui removing this line fixes it. Seems to me a potential bug though.

2023-10-23 20:31 UTC, l5io commented
🚀 Preview for commit fede9e42c98804a761600b5b77162aca561e69d8 at: https://6536d7cec948211f5953e1b3--layer5.netlify.app

2023-10-24 21:24 UTC, leecalcote approved these changes
Awesome. 🙂

2023-10-24 21:39 UTC, vishalvivekm commented on src/collections/members/daniel-kiptoon/index.mdx
> +meshmate: no
```suggestion
```

2023-10-24 21:41 UTC, vishalvivekm commented on src/collections/members/daniel-kiptoon/index.mdx
> +maintainer: no
My bad. I meant `meshmate: no` line @KiptoonKipkurui

2023-10-24 22:38 UTC, merged