made the Honeycombs adapt to small viewport
layer5io/layer5 pull request #5085
Opened 2023-10-27 17:18 UTC by harshit-senpai

**Description**

This PR fixes #5021

Previous State:
The Previous view of the Integrations section for 320px devices looks like this.
![image](https://github.com/layer5io/layer5/assets/93075068/c1569c37-66e6-4b7d-818b-e94effdec765)

Final State: 
the final view of the integration section after this PR
![image](https://github.com/layer5io/layer5/assets/93075068/e893790b-023b-4803-9771-4a5a65e22367)

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-10-27 17:33 UTC, l5io commented
🚀 Preview for commit 8cc5f5c3b21890afa1831c26b0928f11aec32d32 at: https://653bf411ebd8d85cd34508cf--layer5.netlify.app

2023-10-28 09:40 UTC, abhijeetgauravm requested changes
@harshit-senpai, as I can see, the issue is fixed only at 320px, but the desired state should be to make these honeycombs look consistent at approximately 333px and below that dimension as well.

![image](https://github.com/layer5io/layer5/assets/65087356/14996a1e-fdc6-4d94-9f31-2c35f2acb937)

![image](https://github.com/layer5io/layer5/assets/65087356/81678e74-f160-47b6-b033-4f2ee05f294c)

![image](https://github.com/layer5io/layer5/assets/65087356/d398ca3f-6220-44a8-ab95-9b2fb99bc14c)

![image](https://github.com/layer5io/layer5/assets/65087356/a1918dc7-2ece-41ab-8d5b-0b557700e8e0)

2023-10-30 05:55 UTC, Mohith234 commented
@harshit-senpai Let's discuss this today at the website meeting. Please add this to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) if you would.

2023-10-30 14:51 UTC, Shiva953 reviewed
I think the max-width should be a little more than 320px

2023-11-05 14:58 UTC, abhijeetgauravm commented
Hey @harshit-senpai  Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

2023-11-06 11:56 UTC, saurabh100ni commented
@harshit-senpai Please add this as your agenda in [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) to present it in the Website Meet today at 6:30 pm IST/7:00 am CT

2023-11-08 16:13 UTC, sudhanshutech commented
On no response from contributor considering closing this pr for now, thanks for contributing @harshit-senpai , if you want you can create a new pr as you come active until lets open this for new assignees

2023-11-08 16:13 UTC, closed without merging