Fix Aws api Gateway "How it works See it in Action" Component
layer5io/layer5 pull request #5092
Opened 2023-10-31 17:42 UTC by Cvr421

**Description**
Adding the New Meshmap Designer and visualizer screenshot in [Aws api gateway operator](https://layer5.io/cloud-native-management/meshery/integrations/aws-api-gateway-operator)
This PR fixes ##4851

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- 

- Yes, I signed my commits.

2023-10-31 17:44 UTC, Cvr421 commented
Hii @saurabh100ni Please review this PR . And let me know your thoughts if anything need to change.

2023-10-31 18:16 UTC, l5io commented
🚀 Preview for commit e0ad9ec04ef12ba976b3ab47cf21a3ad4d7f6308 at: https://654143df3e1e553c746d9458--layer5.netlify.app

2023-11-02 05:30 UTC, saurabh100ni commented
@sudhanshutech //

2023-11-03 21:49 UTC, leecalcote commented
@vishalvivekm how are you ensuring that these are not being overwritten?

2023-11-06 11:41 UTC, saurabh100ni commented
Please add this as your agenda in [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) to present it in the Website Meet today at 6:30 pm IST/7:00 am CT

2023-11-22 13:24 UTC, l5io commented
🚀 Preview for commit d5f94e418dcc6e7196d634f87b2d7bba067af6e7 at: https://655e00e4fd1a4128ed3e6e15--layer5.netlify.app

2023-11-22 13:44 UTC, vishalvivekm requested changes
@Cvr421 
Please create a `aws-api-gateway-operator` directory in integrations/_images/ and move all your screenshots in that. I mean doing this: 
```
        renamed:    aws-api-Design-dark.png -> aws-api-gateway-operator/aws-api-Design-dark.png
        renamed:    aws-api-Design.png -> aws-api-gateway-operator/aws-api-Design.png
        renamed:    aws-api-visualizer-dark.png -> aws-api-gateway-operator/aws-api-visualizer-dark.png
        renamed:    aws-api-visualizer.png -> aws-api-gateway-operator/aws-api-visualizer.png
 ```

2023-11-22 13:47 UTC, vishalvivekm commented on src/collections/integrations/aws-api-gateway-operator/index.mdx
> +    ]
please revert this change after moving screenshots you've uploaded to its specific directory.
@Cvr421

2023-11-22 13:49 UTC, vishalvivekm commented on src/collections/integrations/aws-api-gateway-operator/index.mdx
> +    ]
Refer to this: https://github.com/layer5io/layer5/pull/5129#issue-1995493031

2023-11-24 15:51 UTC, Cvr421 commented
@vishalvivekm I have made the changes requested by you . Please review

2023-11-24 15:59 UTC, l5io commented
🚀 Preview for commit bb4d5af4e9935c0c638631889a31327a899b2630 at: https://6560c828cc5ae73d037d8df3--layer5.netlify.app

2023-11-24 17:39 UTC, l5io commented
🚀 Preview for commit 77640239c18135061cdbe4015c20bb7bb6d22a8f at: https://6560df741fd7770b2f12abcd--layer5.netlify.app

2023-11-25 14:04 UTC, vishalvivekm commented
> @vishalvivekm I have made the changes requested by you . Please review And there are other commits is also merged with this branch i think. Should i need to do something for this OR it is ok

@Cvr421 signoff is missing. The changes are ready except the missing DCO. Please fix it.

2023-11-25 16:58 UTC, l5io commented
🚀 Preview for commit 59b49fdfa5d70c3f0f129829c5d82dc27e2c871c at: https://65622732faa0394a9346eccc--layer5.netlify.app

2023-11-25 17:32 UTC, Cvr421 commented
@vishalvivekm i have added signoff and also fix the merge conflict please review .

2023-11-27 10:57 UTC, sandramsc reviewed
LGTM!

2023-11-29 23:10 UTC, merged

2023-11-29 23:10 UTC, leecalcote commented
Good work!