Final Products page.
layer5io/layer5 pull request #5097
Opened 2023-11-02 03:47 UTC by Modern-artist

**Description**
Final Products page.

This PR fixes #
Implemented Final Product page.

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-11-02 04:08 UTC, l5io commented
🚀 Preview for commit 112e4b19cfa89144e72283d461fb984bf8f846c0 at: https://6543202a8fec0a04d411d398--layer5.netlify.app

2023-11-05 14:53 UTC, abhijeetgauravm commented
Hey @Modern-artist  Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

2023-11-06 10:50 UTC, l5io commented
🚀 Preview for commit 18c6c418132400f96a8d801b3411d5eba859786a at: https://6548c4b886d5720cb35882e8--layer5.netlify.app

2023-11-06 11:40 UTC, saurabh100ni commented
Please add this as your agenda in [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) to present it in the Website Meet today at 6:30 pm IST/7:00 am CT

2023-11-07 10:04 UTC, ankushbhardwaj408 reviewed
When we hover over product link in navbar the whole screen turns white

2023-11-07 12:05 UTC, abhijeetgauravm commented
> When we hover over product link in navbar the whole screen turns white

Yeah @ankushbhardwaj408  // @Modern-artist

2023-11-08 15:47 UTC, l5io commented
🚀 Preview for commit a1173fe68e132e00d9f4379ef909253f11755d4c at: https://654bacd913188767397f3dbc--layer5.netlify.app

2023-11-10 19:20 UTC, abhijeetgauravm commented
> When we hover over product link in navbar the whole screen turns white

@Modern-artist

2023-11-10 20:33 UTC, leecalcote commented
@Modern-artist, it means that you have a bug.

2023-11-10 20:37 UTC, leecalcote requested changes

2023-11-10 20:37 UTC, leecalcote commented on src/assets/images/products/MesheryRange.svg
These images should be colocated in the same components in which they are used.

2023-11-10 20:40 UTC, leecalcote requested changes

2023-11-10 20:40 UTC, leecalcote commented on src/assets/images/products/MesheryRangeDark.svg
This SVG contains a number of PNGs and is not usable. Ensure only vector contents is used.

2023-11-10 20:48 UTC, leecalcote requested changes

2023-11-10 20:48 UTC, leecalcote commented on src/assets/images/products/Nightawk.svg
This image and other images here are really just PNGs and cannot be used.

2023-11-10 20:48 UTC, leecalcote commented on src/assets/images/products/circle_dark.svg
Relocate this image.

2023-11-10 20:48 UTC, leecalcote commented on src/assets/images/products/patterns.svg
We already have this logo in this site's general assets. Reuse.

2023-11-10 20:48 UTC, leecalcote commented on src/assets/images/products/meshmap.svg
This is a PNG.

2023-11-10 20:48 UTC, leecalcote commented on src/assets/images/products/meshmap.svg
We already have this logo in this site's general assets. Reuse.

2023-11-10 20:48 UTC, leecalcote commented on src/pages/products/index.js
Like other pages, this page should be in sections and contain both sections and components.

2023-11-10 20:48 UTC, leecalcote commented on src/pages/products/icons/support.svg
Use the existing Support icon from Cloud, which is Meshery Operator.

2023-11-10 20:48 UTC, leecalcote commented on src/pages/products/icons/meshmap-icon.svg
Don't duplicate.

2023-11-10 20:48 UTC, leecalcote commented on src/pages/products/icons/coming-soon.webp
Don't duplicate.

2023-11-10 20:48 UTC, leecalcote commented on src/pages/products/collapsible-details.js
Follow the established paradigm like other pages. Use sections and components.

2023-11-10 20:48 UTC, leecalcote commented on src/assets/images/products/circle_light.svg
Relocate this image.

2023-11-10 20:48 UTC, leecalcote commented on src/assets/images/products/MesheryRange.svg
This SVG contains a number of PNGs and is not usable. Ensure only vector contents is used.

2023-11-10 20:48 UTC, leecalcote commented on src/assets/images/products/Rectangle.svg
This SVG contains a number of PNGs and is not usable. Ensure only vector contents is used.

Don't duplicate the logo.

2023-11-10 20:48 UTC, leecalcote commented on src/assets/images/products/meshery-logo-light.svg
This SVG contains a number of PNGs and is not usable. Ensure only vector contents is used.

Don't duplicate.

2023-11-10 20:48 UTC, leecalcote commented on src/pages/products/pricing.style.js
> +import styled from "styled-components";
A complete copy/paste? We're increasing our sustaining costs.

2023-11-10 20:48 UTC, leecalcote commented on src/sections/General/Navigation/index.js
No change, so don't include this file.

2023-11-11 02:17 UTC, leecalcote commented
Most of the buttons included here don't work, @Modern-artist. 

This PR is not ready for review.

2023-11-11 02:22 UTC, leecalcote commented on src/pages/products/icons/collaboration.svg
Where is this used?

2023-11-11 03:38 UTC, leecalcote commented
The length of the CSS file needs cut down (by ~1/2)

2023-11-11 03:49 UTC, l5io commented
🚀 Preview for commit 449a447c555edb9f62ff1de5bc669a0911cf0738 at: https://654ef96c7dbdf35abc87e3ef--layer5.netlify.app

2023-11-12 07:45 UTC, abhijeetgauravm commented
Hey @Modern-artist  Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

2023-11-14 13:26 UTC, leecalcote commented
@Modern-artist are we pressing forward here or closing out and starting over?

2023-11-14 13:30 UTC, Modern-artist commented
> @Modern-artist are we pressing forward here or closing out and starting over?

I would prefer to start again as I haven't written any code for the first two sections.

2023-11-19 15:57 UTC, closed without merging