removed repeated word
layer5io/layer5 pull request #5132
Opened 2023-11-16 10:44 UTC by Harsha-10

**Description**

This PR fixes #5128

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-11-16 10:55 UTC, l5io commented
🚀 Preview for commit 389d2f4deb48f993a67fa6aec9807853f5ea5556 at: https://6555f4eeac7e79708c85a388--layer5.netlify.app

2023-11-16 14:26 UTC, ankushbhardwaj408 requested changes

2023-11-17 05:51 UTC, Harsha-10 commented on src/sections/Community/Handbook/faq.js
> +            <p>A: Yes, outside of the regularly scheduled meetings on the community calendar (meet.layer5.io), there are any number of other meetings that occur to facilitate deeper levels or more co
@ankushbhardwaj408  Done

2023-11-17 06:03 UTC, l5io commented
🚀 Preview for commit ec1fac7edc96f2a2f4f2beba5beae904af8e848d at: https://655701a27abbc6596b054e10--layer5.netlify.app

2023-11-17 06:23 UTC, ankushbhardwaj408 approved these changes
LGTM!

2023-11-17 10:24 UTC, Mohith234 approved these changes
LGTM, Thanks for the quick fix @Harsha-10 🚀

2023-11-17 10:25 UTC, merged