[Blog][Ready to review] Meshery Playground: Features you don't want to miss
layer5io/layer5 pull request #5146
Opened 2023-11-21 14:45 UTC by saurabh100ni

**Description**

I wrote blog on Meshery Playground which is ready for reviews.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-11-21 14:57 UTC, l5io commented
🚀 Preview for commit f2e0633096b976efd1800d2f73a5111ed5a164e9 at: https://655cc4fe18276d035af13ffa--layer5.netlify.app

2023-11-21 22:03 UTC, leecalcote commented on src/collections/blog/2023/11-15-Features-of-meshery/index.mdx
> +description: "Features of Meshery Playground which takes your user experience to the next level."
```suggestion
description: "Key features of Meshery Playground for Kubernetes, Prometheus, Argo and other CNCF projects. Use Meshery Playground to explore a new way of DevOps - visual and collaborative configuration management for your infrastructure. "  
```

2023-11-21 22:03 UTC, leecalcote commented on src/collections/blog/2023/11-15-Features-of-meshery/index.mdx
> +Before we dive into the features, Let’s take a recap, What is [Meshery Playground](https://playground.meshery.io/)?
```suggestion
Before we dive into features, let’s understand what the Meshery Playground is.
```

2023-11-21 22:05 UTC, leecalcote commented
There are a number of inconsistencies to cleanup. Please do so.

2023-11-22 07:25 UTC, l5io commented
🚀 Preview for commit b9ddb949ff00805cecdd1340491061d3324272f4 at: https://655dac4601df1a624d2f24c7--layer5.netlify.app

2023-11-22 07:55 UTC, l5io commented
🚀 Preview for commit e8f49355b3fc8e6c30d9001f2055b151da8071c5 at: https://655db36f9cde316d62a65bef--layer5.netlify.app

2023-11-22 14:01 UTC, saurabh100ni commented
@leecalcote Done fixing the inconsistency with the formatting and links and also added your suggestions.

2023-11-22 14:04 UTC, leecalcote commented on src/collections/blog/2023/11-15-Features-of-meshery/index.mdx
> +[Meshery UI](https://meshery.io/) is a web-based user interface for Meshery, offering a convenient way to interact with Meshery Server. Meshery UI is a valuable tool for DevOps engineers, enhancing t
Too many links.

2023-11-22 14:04 UTC, leecalcote commented on src/collections/blog/2023/11-15-Features-of-meshery/index.mdx
> +# [Meshery catalog](https://docs.meshery.io/concepts/catalog):
Why is catalog not capitalized?

2023-11-22 14:06 UTC, leecalcote requested changes

2023-11-22 14:06 UTC, leecalcote commented on src/collections/blog/2023/11-15-Features-of-meshery/index.mdx
>  Meshery Catalog, with its user-friendly approach and collaborative features, stands as a valuable resource for cloud-native practitioners, facilitating seamless deployment, knowledge-sharing, and the
This is a poor description of the Catalog. This is a description of Meshery.

2023-11-22 14:06 UTC, leecalcote commented on src/collections/blog/2023/11-15-Features-of-meshery/index.mdx
>  In summary, Meshery empowers teams through its Workspaces feature, providing a virtual space for seamless collaboration, resource sharing, and efficient management of diverse environments. With logic
In summary, Meshery boils down to its Workspace feature? Meshery doesn't even have this feature, yet. Cloud does.

2023-11-22 14:11 UTC, l5io commented
🚀 Preview for commit b96b7023ac2aea8915312cf5162bae5cd956d599 at: https://655e0bb9e48e773042716763--layer5.netlify.app

2024-07-19 17:02 UTC, closed without merging