Much spaces between contribution and General contribution flow
layer5io/layer5 pull request #5150
Opened 2023-11-22 15:23 UTC by AbiodunVlad

**Description**
 Much spaces between contribution and General contribution flow #4636 

This PR fixes #4636 

**Notes for Reviewers**
Kindly find the changes made on all page under the Handbook section.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-11-22 16:14 UTC, l5io commented
🚀 Preview for commit 9c01e48b643231bd77c2bc2e3cadb7923a7b5605 at: https://655e287b036f1f4736c2ee14--layer5.netlify.app

2023-11-22 16:39 UTC, AbiodunVlad commented
There is a failed check here because of the Node version. I don't have permission to edit it.
Please assist.

2023-11-22 16:42 UTC, leecalcote requested changes

2023-11-22 16:42 UTC, leecalcote commented on src/components/handbook-navigation/toc.style.js
Remove all unnecessary changes in order to facilitate review.

2023-11-22 16:44 UTC, AbiodunVlad commented on src/components/handbook-navigation/toc.style.js
I'm sory but I don't know which unnecessary changes ou're referring to.

2023-11-22 18:16 UTC, abhijeetgauravm commented on src/components/handbook-navigation/toc.style.js
@AbiodunVlad Unnecessary changes might be occurring due to a formatting extension of your code editor.

2023-11-22 18:22 UTC, AbiodunVlad commented on src/components/handbook-navigation/toc.style.js
@abhijeetgauravm please what do you suggest I do? Because I'm really lost at this point.

2023-11-23 17:17 UTC, Mohith234 commented
@AbiodunVlad Use Node Version Manager (NVM) to downgrade your node version.

2023-11-24 14:58 UTC, leecalcote commented
PR title needs renamed.

2023-11-24 23:54 UTC, l5io commented
🚀 Preview for commit c0a96fdf3c86adf4ce713e732d3a1bcf8ad1546a at: https://6561374cc9c6ba3f06804115--layer5.netlify.app

2023-11-25 00:14 UTC, AbiodunVlad commented
All checks have finally passed!
PR is good to go.

@abhijeetgauravm @Mohith234 @leecalcote

2023-11-25 13:07 UTC, abhijeetgauravm commented on src/components/handbook-navigation/toc.style.js
@AbiodunVlad you can temporarily disable the formatting extension and see if the issue persists. This will help you identify whether the extension is the root cause of the problem.

2023-11-25 13:17 UTC, abhijeetgauravm reviewed
![image](https://github.com/layer5io/layer5/assets/65087356/c96c2678-f3f6-4127-a627-9008fdd0f72d)
![image](https://github.com/layer5io/layer5/assets/65087356/2e63095f-68ba-4db0-acb0-92091fb54b91)

@AbiodunVlad

2023-11-26 06:37 UTC, abhijeetgauravm commented
Hey @AbiodunVlad Let's discuss this on website call today at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

2023-11-27 16:58 UTC, l5io commented
🚀 Preview for commit 883fb49d44e1f837fdbe04e71f7c5ed7cf5ebb9b at: https://6564ca7e1a6803007a883a5a--layer5.netlify.app

2023-11-27 17:19 UTC, AbiodunVlad commented
I reviewed the code and fixed necessary changes.

2023-11-28 08:26 UTC, abhijeetgauravm reviewed
@AbiodunVlad, it looks good in preview now. However, there seem to be unnecessary changes, possibly due to the formatting extension of your code editor.

2023-11-29 18:33 UTC, AbiodunVlad commented
@abhijeetgauravm Thank you for your feedback.
What unnecessary changes do you observe? Is it good to merge or do I have to fix something?

2023-11-29 23:38 UTC, leecalcote requested changes
Thanks, @AbiodunVlad. There's no meaningful change in the `src/components/handbook-navigation/toc.style.js` page. Please remove those changes from this PR and do the same for any other non-material changes.

2023-11-29 23:38 UTC, leecalcote commented
Merge conflicts....

2024-03-06 16:40 UTC, closed without merging