add-CTA-on-every-observability-integration-page
layer5io/layer5 pull request #5252
Opened 2024-01-01 10:05 UTC by vishalvivekm

**Description**

This PR fixes #5234 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-01-01 10:17 UTC, l5io commented
🚀 Preview for commit a6bd6feac1cbca834bcbc10b7762954e5d58524c at: https://659290d17632d6a874eb6f57--layer5.netlify.app

2024-01-03 08:52 UTC, leecalcote requested changes
No: Know More

Yes: Learn More

Please change the button text.

2024-01-03 13:12 UTC, vishalvivekm commented on src/sections/Meshery/Meshery-integrations/Individual-Integrations/cta-performance.js
> +                            Know more
```suggestion
                            Learn More
```

2024-01-03 13:13 UTC, vishalvivekm commented
> No: Know More
> 
> Yes: Learn More
> 
> Please change the button text.

Done

2024-01-03 13:24 UTC, l5io commented
🚀 Preview for commit 08fdf6f7aef85df7fb15d4954acf9885d4b451d2 at: https://65955faffa5ed705d1f6d288--layer5.netlify.app

2024-03-29 11:14 UTC, l5io commented
🚀 Preview for commit 24772b0546a119081991f069282435e6404b1dde at: https://6606a2551ddf01988fc4b861--layer5.netlify.app

2024-03-29 11:26 UTC, merged