Profile ahmed jamil
layer5io/layer5 pull request #5300
Opened 2024-01-18 17:00 UTC by srujan0404

**Description**
Kindly check and review my PR, I have added Ahmed jamil in the members list under community

This PR fixes #5292

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-01-18 17:12 UTC, l5io commented
🚀 Preview for commit 474195ef968e62bf5f3d6218eb99a3f130d829cb at: https://65a95b9e7dc1680319a287cc--layer5.netlify.app

2024-01-19 09:59 UTC, iArchitSharma commented on src/collections/members/ahmed-jamil/index.mdx
> +- community
@srujan0404 remove the community badge

2024-01-19 10:00 UTC, iArchitSharma requested changes
LGTM if above changes are done!

2024-01-19 13:18 UTC, srujan0404 commented
@iArchitSharma Done with changes

2024-01-19 13:30 UTC, l5io commented
🚀 Preview for commit 78305526d5ce7b5ef246745609c92b18b90d1b21 at: https://65aa790f7cad7b08caa2dac7--layer5.netlify.app

2024-01-23 11:28 UTC, samyakshah3008 approved these changes
Looks good ✅

2024-01-23 11:32 UTC, l5io commented
🚀 Preview for commit 3da67c38ac7273395cc1e514e34b6bc6e4bb6119 at: https://65afa37ae900d00393c3c9db--layer5.netlify.app

2024-01-24 19:50 UTC, sudhanshutech commented
Thanks @srujan0404

2024-01-24 19:51 UTC, merged