Profile: Ripal Handoo
layer5io/layer5 pull request #5302
Opened 2024-01-18 17:44 UTC by Vidip-Ghosh

**Description**

This PR fixes #5293 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-01-18 17:49 UTC, srujan0404 commented
@Vidip-Ghosh LGTM!!

2024-01-18 17:55 UTC, l5io commented
🚀 Preview for commit 0abb49c6a8682cb9cab9260e6fb238d142f17d65 at: https://65a965c832768000a090a87c--layer5.netlify.app

2024-01-24 19:56 UTC, sudhanshutech commented
@Vidip-Ghosh have you confirmed the profile is visible because its not

2024-01-24 19:57 UTC, sudhanshutech requested changes

2024-01-24 19:57 UTC, sudhanshutech commented on src/collections/members/Ripal_Handoo/index.mdx
> +published: #true
remove # from here, then it might
```suggestion
published: true
```

2024-01-25 12:00 UTC, Vidip-Ghosh commented
Its deployment is now failing @sudhanshutech

2024-01-25 12:01 UTC, sudhanshutech commented
yes you can take care of it by making some small commit from your side, try it

2024-01-29 11:41 UTC, Vidip-Ghosh commented
> yes you can take care of it by making some small commit from your side, try it

I did this but still preview failing

2024-01-31 05:42 UTC, iArchitSharma commented
are you following all the steps - https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#set-up-your-local-development-environment

2024-01-31 12:35 UTC, Vidip-Ghosh commented
> are you following all the steps - https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#set-up-your-local-development-environment

Yes I have followed

2024-01-31 12:53 UTC, l5io commented
🚀 Preview for commit 21ea3efbf09bfda7ed4fb3ef2ec446d2bc507d11 at: https://65ba42342cc4cad426ac0030--layer5.netlify.app

2024-01-31 16:49 UTC, iArchitSharma commented
@RipulHandoo all good?

2024-01-31 16:55 UTC, RipulHandoo commented
Yes it looks good. Just a small change, my name is wrong in the image path.

2024-01-31 19:09 UTC, l5io commented
🚀 Preview for commit a58122d21d0756f717af73d14c1579455e33c878 at: https://65ba9a5c34a6760dbce218fd--layer5.netlify.app

2024-01-31 19:34 UTC, merged