cookie implemented for navbar
layer5io/layer5 pull request #5341
Opened 2024-01-24 07:47 UTC by captain-Akshay

**Description**

This PR fixes  #5295 

I added just a simple logic to the button or not.
we will be making it into a profile button if the session cookie address changes to the main domain i.e. layer5.io rather than meshery.layer5.io(which is a subdomain) then we might so logout button and other default options.

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

2024-01-24 07:49 UTC, captain-Akshay commented on src/sections/General/Navigation/index.js
> +import Cookie from "js-cookie";
this was added here.

2024-01-24 07:49 UTC, captain-Akshay commented on src/sections/General/Navigation/index.js
> +          )}
this was added here.

2024-01-24 07:50 UTC, captain-Akshay commented on src/sections/General/Navigation/index.js
> +  const [cookie, setCookie] = useState(null);
this was added here.

2024-01-24 07:58 UTC, l5io commented
🚀 Preview for commit 18790362a56d379fbf4df23c76d6132d7cfd5166 at: https://65b0c2db4d190a55d2951223--layer5.netlify.app

2024-01-25 21:21 UTC, leecalcote reviewed
Here's what I see while having an active session - 

<img width="375" alt="Screenshot 2024-01-25 at 3 19 05 PM" src="https://github.com/layer5io/layer5/assets/7570704/7af27b5f-b154-4a98-8aef-50fc2f02186a">

Two items:
1. The active session has access to the capability "meshmap", however, the URL on the playground button is still play.meshery.io.
2. Should we be expecting to see an avatar of the user at some point?

2024-01-28 15:06 UTC, iArchitSharma requested changes
@captain-Akshay  this doesn't seems to work?

2024-02-07 23:20 UTC, leecalcote commented
@captain-Akshay there's a piling up of your open, incomplete PRs across a couple repos...

2024-02-26 07:25 UTC, l5io commented
🚀 Preview for commit cd31ce73d721b773e0ecbba694c3b652a2f1cb70 at: https://65dc3c934e315f7ff0af1620--layer5.netlify.app

2024-02-26 12:33 UTC, l5io commented
🚀 Preview for commit 950941e175fd29981a8173fcbd05e4eafc83cc12 at: https://65dc84c74e315fba6daf1979--layer5.netlify.app

2024-02-26 15:22 UTC, l5io commented
🚀 Preview for commit 00b3c36ae7cbf05320ff74e85c89a8f2eb9dd2da at: https://65dcac79bdab100ae3813153--layer5.netlify.app

2024-02-26 16:09 UTC, captain-Akshay commented
[Screencast from 2024-02-26 20-34-33.webm](https://github.com/layer5io/layer5/assets/59491379/94ba56a6-2d87-44a7-a294-2b69d3cf0415)

[Screencast from 2024-02-26 20-39-07.webm](https://github.com/layer5io/layer5/assets/59491379/89a8830a-75fc-4bef-bff1-6937aa2b7907)

@ritiksaxena124

2024-03-11 15:09 UTC, l5io commented
🚀 Preview for commit cc9508dfe0c46cb7acbd417710c54fa9c6f4225a at: https://65ef1e5cea89e068425eb83c--layer5.netlify.app

2024-03-13 11:56 UTC, l5io commented
🚀 Preview for commit 4bdddaf56eab4942daeef49ce3d3b4ff3d7c410c at: https://65f1942a3e64390ee4b71e09--layer5.netlify.app

2024-03-13 14:14 UTC, captain-Akshay commented
[Screencast from 2024-03-13 17-02-13.webm](https://github.com/layer5io/layer5/assets/59491379/70be2e7f-1d87-410c-b422-b5318ff98293)

2024-03-13 14:25 UTC, l5io commented
🚀 Preview for commit 74c5d434e50eeae7124a1d96aefc4d6f49ea1653 at: https://65f1b706f269a22b1a288ce2--layer5.netlify.app

2024-03-14 14:21 UTC, merged