[Screenshots] added for integration External Secrets Operator #5328
layer5io/layer5 pull request #5413
Opened 2024-02-18 05:04 UTC by meetjn

**Description**

This PR fixes #5328 

**Notes for Reviewers**

Added both Dark Mode and Light Mode screenshots.

<img width="1440" alt="Screenshot 2024-02-18 at 10 13 19 AM" src="https://github.com/layer5io/layer5/assets/141674944/414d206a-7349-4404-8e1b-9f4b5eedb460">
<img width="1440" alt="Screenshot 2024-02-18 at 10 12 32 AM" src="https://github.com/layer5io/layer5/assets/141674944/31f3a3a3-7c72-43ed-a970-5264fc5d1e99">

<img width="1440" alt="designer dark" src="https://github.com/layer5io/layer5/assets/141674944/07a459c2-934f-4406-b308-88f6a19628ff">
<img width="1440" alt="designer light" src="https://github.com/layer5io/layer5/assets/141674944/191ef70b-db45-4b00-acbd-9ba24c72f21c">
<img width="1440" alt="visualizer dark" src="https://github.com/layer5io/layer5/assets/141674944/6d96323a-3987-4635-a360-7a436eb69129">
<img width="1440" alt="visualizer light" src="https://github.com/layer5io/layer5/assets/141674944/e7de4b6d-84e8-48f7-b53f-e2a86d41075b">

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits. 
- [ ] Signed-off-by: Meet Jain <meetjaiin@gmail.com>

2024-02-20 16:52 UTC, vishalvivekm commented on src/collections/integrations/_images/external secret/visualizer light.png
the folder should be named `external-secrets-operator`and not `external secret` 
will you please update it @meetjn

2024-02-20 16:53 UTC, vishalvivekm commented on src/collections/integrations/external-secrets-operator/index.mdx
> +  /Users/meet/Desktop/layer5/src/collections/integrations/_images/external secret/visualizer light.png
These changes aren't needed @meetjn.
Revert these, if you would, please.

2024-02-20 16:53 UTC, vishalvivekm requested changes
preview is failing.
have suggested some changes, they might fix it.

2024-02-22 06:43 UTC, l5io commented
🚀 Preview for commit 989750bd70252132271ff393d2805ff01cc48567 at: https://65d6ec7d0c8e5866d8c5dbcd--layer5.netlify.app

2024-02-22 09:02 UTC, meetjn commented
> preview is failing. have suggested some changes, they might fix it.

Updated the suggested changes.

2024-02-24 02:59 UTC, meetjn commented
> There're not changes @meetjn
> 
> ![image](https://private-user-images.githubusercontent.com/110674407/307091444-7c862e4a-0469-44da-b883-e35237980d2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NDM0NTAsIm5iZiI6MTcwODc0MzE1MCwicGF0aCI6Ii8xMTA2NzQ0MDcvMzA3MDkxNDQ0LTdjODYyZTRhLTA0NjktNDRkYS1iODgzLWUzNTIzNzk4MGQyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQwMjUyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZGJmMGM4YWM4MTFhMDI5ZDNjZDEzMmU4MGM2NDg0YmJhZmNlYThjYzFhYTVjNjEyYTM1OWMxMjE3ZTgxNjQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xQfwzDHSy-AQDF7Ztvsjti-1eVkXHALs_52QM3vlsDw)
> 
> Where're the screenshots and the directory I previously mentioned under `_images/`
> 
> https://65d6ec7d0c8e5866d8c5dbcd--layer5.netlify.app/cloud-native-management/meshery/integrations/external-secrets-operator

Updated screenshots with the file paths and new directory under _images

2024-02-24 03:03 UTC, l5io commented
🚀 Preview for commit 821e386a72282b8ddb06795a471e1169a2808311 at: https://65d95c34145040971390d67c--layer5.netlify.app

2024-02-24 04:13 UTC, l5io commented
🚀 Preview for commit 9d0c238d902328b4c12e8ff4d343b0640a62748c at: https://65d96cb7fd55299b3dec9be6--layer5.netlify.app

2024-02-25 10:17 UTC, vishalvivekm requested changes

2024-02-25 10:17 UTC, vishalvivekm commented on .gitpod.yml
please revert this change.

2024-02-25 10:17 UTC, vishalvivekm commented on src/collections/integrations/_images/External-secrets-operator/designDark.png
`external-secrets-operator` not `External-secrets-operator`

2024-02-25 14:53 UTC, closed without merging