Update recognition.js
layer5io/layer5 pull request #5538
Opened 2024-05-15 05:11 UTC by bunnyDasari

I have changed the recognitionsstyle  from 0.5 rem to 1 rem as mentioned in the issue

**Description**

This PR fixes #
incresed the space  between the Activity badges points 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-05-15 05:23 UTC, bunnyDasari commented
I am writing to inform you that the issue regarding style has been successfully resolved. Please feel free to reach out if you encounter any other issues.

2024-05-15 05:25 UTC, l5io commented
🚀 Preview for commit cd1de86d04caf26111c25b5b293dc0c1caa9039e at: https://6644470652099b54ced02116--layer5.netlify.app

2024-05-18 14:37 UTC, vishalvivekm commented
> I am writing to inform you that the issue regarding style has been successfully resolved. Please feel free to reach out if you encounter any other issues.

@bunnyDasari Thank you. Will you please link the PR with corresponding open issue ? 
You can do so, by including `fixes #<PR-number>`

2024-05-19 09:59 UTC, bunnyDasari commented
@vishalvivekm fixes #5520
Name of the issue : Add spacing on Recognition page

2024-05-19 14:20 UTC, psankhe28 commented
> @vishalvivekm fixes #5520 Name of the issue : Add spacing on Recognition page

If possible, edit it in the PR description itself
Here: `This PR fixes #`

2024-05-20 09:14 UTC, bunnyDasari commented
@psankhe28  done. I have edited in description itself 

> > @vishalvivekm fixes #5520 Name of the issue : Add spacing on Recognition page
> 
> If possible, edit it in the PR description itself Here: `This PR fixes #`

2024-05-24 05:54 UTC, sudhanshutech requested changes
i still don't see any space between badges: 
![image](https://github.com/layer5io/layer5/assets/90546692/7bd03b68-b4eb-42d7-816d-44faeda7bfd6)

add slight space between these list of badges

2024-05-29 08:09 UTC, sudhanshutech commented
@bunnyDasari are you working on the changes suggested, any help?

2024-06-06 12:34 UTC, bunnyDasari commented
> @bunnyDasari are you working on the changes suggested, any help?

yeah i have changed in github itself but im unable to run project locally can please help me with this

2024-06-10 11:14 UTC, sudhanshutech commented
can you share your issue in website call today:

2024-06-16 02:35 UTC, bunnyDasari commented
@sudhanshutech im busy with my end sem exams from past 15days can i attend upcoimg meetings

2024-07-02 04:55 UTC, closed without merging