[Fix Post Blog] - Meshery 5000 star milestone
layer5io/layer5 pull request #5599
Opened 2024-06-20 21:45 UTC by sandramsc

**Description**

This PR fixes #5598

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-06-21 18:30 UTC, l5io commented
🚀 Preview for commit 439319697f3dcc40bcec1d792cadd7b8cbedf5ee at: https://6675c64e6a08c6ccfbeb4929--layer5.netlify.app

2024-06-21 19:23 UTC, l5io commented
🚀 Preview for commit 5e1590486cd8bb13d1648751b6cd777542c663b3 at: https://6675d2e3543aaedbe5ed753a--layer5.netlify.app

2024-06-21 19:57 UTC, l5io commented
🚀 Preview for commit e86e5d5609a4a99db0eb3f8be664b216ba8dc1a7 at: https://6675dae5af4203009f07c95e--layer5.netlify.app

2024-06-21 20:30 UTC, l5io commented
🚀 Preview for commit a470ad5f9e97da0a3f1149f810d5160c1e197097 at: https://6675e25402ce9306169beee9--layer5.netlify.app

2024-06-21 21:00 UTC, l5io commented
🚀 Preview for commit 76b05b1d50ec6a0852e4eccc3683935a84b0f66c at: https://6675e94c543aaeefa5ed73df--layer5.netlify.app

2024-06-21 21:09 UTC, sandramsc commented
Tried a few times to get the heading "The Journey Has Just Begun" to align on the left, under the headings of the same size above it by using br and p tag to as well as removing the mentioned tags, but it remains aligned on the left. Feedback on how to adjust/fix this is welcome.

![imageedit_4_7999326101](https://github.com/layer5io/layer5/assets/19821445/4b107339-dbff-4152-b9ca-8d73afcea2b6)

2024-06-24 11:40 UTC, vishalvivekm commented
Thank you for your contribution.
Let's discuss this on Websites's call. Add this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit), if you would :)

2024-07-20 22:50 UTC, leecalcote commented
Argh! I should have reviewed this years ago. 🫤 Thank you for this, @sandramsc 👍

2024-07-23 20:15 UTC, l5io commented
🚀 Preview for commit 11fc7575a45a8a094d956371150d360e11c95323 at: https://66a00ef4ad6e3933fe04125f--layer5.netlify.app

2024-07-24 20:20 UTC, hargunkaur286 commented on src/collections/blog/2024/06-21-meshery-5000-star-milestone/index.mdx
1. you can make the

2024-07-24 20:42 UTC, hargunkaur286 requested changes
Overall, the content looks good to me!

2024-07-26 09:34 UTC, sudhanshutech commented
@sandramsc does hargun's feedback looks good?

2024-07-29 20:03 UTC, leecalcote commented
@hargunkaur286 please apply these formatting changes on @sandramsc's behalf. 👍

2024-07-29 20:03 UTC, merged