added spaces between the badges
layer5io/layer5 pull request #5631
Opened 2024-07-02 04:42 UTC by bunnyDasari

fixes #5520

added spaces between the badges

Description

This PR fixes #
increased the space between the Activity badges.

2024-07-02 04:56 UTC, l5io commented
🚀 Preview for commit 90e2b02afbfd82762caad360d86e9ecd762e202a at: https://66838841a39c30e9cd499222--layer5.netlify.app

2024-07-02 04:58 UTC, bunnyDasari commented
before the changes
![Screenshot 2024-07-02 100853](https://github.com/layer5io/layer5/assets/104191071/059a3584-61c4-4444-a8fa-1bc3e7a79a5f)
after the changes 
![Screenshot 2024-07-02 094524](https://github.com/layer5io/layer5/assets/104191071/92c96fce-ab0d-4cde-9e79-657124cefc90)

2024-07-05 10:32 UTC, iArchitSharma requested changes
thanks @bunnyDasari , but can you please make sure that the badges are perfectly aligned with their respective text?

2024-07-06 01:33 UTC, bunnyDasari commented
> thanks @bunnyDasari , but can you please make sure that the badges are perfectly aligned with their respective text?

Okay I'll align it perfectly

2024-07-08 12:26 UTC, closed without merging