Solved Cards not fitting on smaller screens in Community Handbook page
layer5io/layer5 pull request #5644
Opened 2024-07-07 09:17 UTC by krishkumar84

**Description**

This PR fixes #5639

**Notes for Reviewers**
@Ashparshp  kindly review this 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.
 
the community cards have a fixed width of 25rem and a hover scale effect. However, this setup is causing issues on small mobile screens. To address this, I've added a media query that adjusts the card styling for smaller mobile screens, ensuring a better user experience across devices.

2024-07-07 09:27 UTC, Deepak0320Singhal commented
@krishkumar84 Thank you for your contribution.
Let's discuss this on Websites's call. Add this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit), if you would :)

2024-07-07 09:31 UTC, l5io commented
🚀 Preview for commit 560d2f664fb262265a3afe2d8f9035cd65f3f872 at: https://668a60474212c3b468728f86--layer5.netlify.app

2024-07-07 10:01 UTC, krishkumar84 commented
> @krishkumar84 Thank you for your contribution. Let's discuss this on Websites's call. Adding this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit), if you would :)
sure add this in agenda of meeting minutes

2024-07-07 10:47 UTC, Ashparshp reviewed
LGTM! But why are you having these many numbers of breakpoints?

2024-07-07 11:02 UTC, krishkumar84 commented
> LGTM! But why are you having these many numbers of breakpoints?

because here the card width was predefined which is 25rem so on smaller screen due to that issue arises so by the no of breakpoints it ensures that i look great on even small to small devices

2024-07-07 11:57 UTC, Ashparshp approved these changes

2024-07-07 11:58 UTC, Ashparshp approved these changes
Also, thanks for fixing Adventures of Five and Friends page as well!
LGTM..

2024-07-07 11:59 UTC, Ashparshp commented
@iArchitSharma ^^

2024-07-16 06:35 UTC, Ashparshp commented
@vishalvivekm ^^

2024-07-19 16:57 UTC, sudhanshutech requested changes

2024-07-19 16:57 UTC, sudhanshutech commented on src/components/AdventuresVol/adventures-vol.style.js
> +	  @media (max-width: 450px) {
@krishkumar84 please avoid using so much of these media queries and also at every width points. these are hard to maintain. Try to use max width and width together. Even if its needed to use it should be only one and used in such a way it should effect the whole component.

2024-07-21 09:48 UTC, Ashparshp commented
@krishkumar84 Any luck?

2024-08-26 19:08 UTC, closed without merging