Issue 5640 abjustlayout
layer5io/layer5 pull request #5647
Opened 2024-07-07 12:53 UTC by pukarlamichhane

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-07-07 13:07 UTC, l5io commented
🚀 Preview for commit 5087bb0acb8f84a7aaa6879551a598d158d8c3f3 at: https://668a92c2757d6ae9a040720b--layer5.netlify.app

2024-07-07 16:42 UTC, sudhanshutech commented
@pukarlamichhane make sure you add the issue number in pr message not in title so it will link with appropriate issue.
Also ensure you sign your commits please

2024-07-07 16:44 UTC, sudhanshutech requested changes

2024-07-07 16:44 UTC, sudhanshutech commented on src/sections/Learn/Lab-single/index.js
> -  // React.useEffect(() => {
why this?

2024-07-07 16:44 UTC, sudhanshutech commented on src/sections/Learn/Lab-single/LabSinglePageWrapper.style.js
> -	.backBtn {
avoid doing unnecessary lint changes please

2024-07-07 16:59 UTC, vishalvivekm commented
@pukarlamichhane 
Thank you for your contribution.
Let's discuss this on Websites' call. Adding this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit).

2024-07-07 17:22 UTC, pukarlamichhane commented on src/sections/Learn/Lab-single/LabSinglePageWrapper.style.js
> -	.backBtn {
ok sir

2024-07-16 10:24 UTC, Ashparshp commented
@pukarlamichhane Make sure to sign-off commits..

2024-07-19 16:53 UTC, sudhanshutech commented
@pukarlamichhane any progress further?

2024-07-19 16:55 UTC, pukarlamichhane commented
Already completed

On Fri, 19 Jul 2024, 22:38 Sudhanshu Dasgupta, ***@***.***>
wrote:

> @pukarlamichhane <https://github.com/pukarlamichhane> any progress
> further?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/layer5io/layer5/pull/5647#issuecomment-2239632729>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZ745SUYUJYZ34IJLYTIVSTZNFABTAVCNFSM6AAAAABKPKZ4VKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEMZZGYZTENZSHE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-07-21 10:10 UTC, Ashparshp commented
@pukarlamichhane Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

2024-07-23 22:26 UTC, l5io commented
🚀 Preview for commit da441c06c9984e638aca20a0937fed14a723c5fa at: https://66a02de54c78b354a02dfe8f--layer5.netlify.app

2024-08-22 12:32 UTC, sudhanshutech commented
@pukarlamichhane checking again?

2024-08-23 06:10 UTC, Ashparshp commented
@pukarlamichhane, Final check..

2024-08-27 05:08 UTC, closed without merging