jsx syntax highlighter
layer5io/layer5 pull request #5681
Opened 2024-07-15 06:53 UTC by mannika763

**Description**

This PR fixes #5673

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-07-15 07:08 UTC, l5io commented
🚀 Preview for commit 3ec611d8291015fb519b61c7e9c40b50e50bc298 at: https://6694ca889464c837cab63f02--layer5.netlify.app

2024-07-15 08:52 UTC, sudhanshutech commented
@mannika763 
Let's discuss this on Websites' call. Add this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit), if you would :)

2024-07-15 09:17 UTC, l5io commented
🚀 Preview for commit 4ce2691689126981cf595b75db0590bf574fac8d at: https://6694e8859c1981746e6b3d72--layer5.netlify.app

2024-07-15 12:04 UTC, sudhanshutech commented
have you not joined slack @mannika763 .? Please join here the meeting: https://meet.layer5.io/websites

2024-07-16 02:04 UTC, mannika763 commented
@sudhanshutech Sorry, I didn't see your message earlier. Can I join today?

2024-07-16 05:18 UTC, Ashparshp commented
@mannika763 No sweat!! We don't have meeting for today, let's discuss in tomorrow development call.. add your item into meeting [minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?usp=drivesdk)

2024-07-16 09:53 UTC, l5io commented
🚀 Preview for commit ac9142d358f349c06b6b85dd95a3804c24664888 at: https://669642ada7f8eb72265bad7f--layer5.netlify.app

2024-07-16 11:20 UTC, sudhanshutech requested changes

2024-07-16 11:20 UTC, sudhanshutech commented on src/components/CodeBlock/index.js
> +      theme={isDark ? theme : vsCodeLight}
keep the theme as it was earlier please. Currently light doesn't seems to good so we can keep the existing effect

2024-07-16 15:36 UTC, mannika763 reviewed
I have added a condition for dark and light themes in the code-block.js file. This allows us to maintain the same theme for both light and dark modes according to the CodeBlock.js file.
Please let me know if this approach is correct or should i follow something else.
Thankyou

2024-07-16 15:48 UTC, l5io commented
🚀 Preview for commit ae97610103396c994676c2027bd11c463f53ebbe at: https://669695f1f619af48744dcaeb--layer5.netlify.app

2024-07-19 16:30 UTC, sudhanshutech commented
> I have added a condition for dark and light themes in the code-block.js file. This allows us to maintain the same theme for both light and dark modes according to the CodeBlock.js file. Please let me know if this approach is correct or should i follow something else. Thankyou

@mannika763 keep the same dark theme code block at light theme, we don't need separate logic or different theme for light it can be constant as it is dark right now.

2024-07-19 18:06 UTC, mannika763 reviewed
I have removed the conditional rendering related to isDark. Now, the dark theme will appear in both light and dark modes.

2024-07-19 18:19 UTC, l5io commented
🚀 Preview for commit 612ca9673c3418cbdcfdfbf8b7289b536ed6828e at: https://669aadd4b2a5948e5e9e91b3--layer5.netlify.app

2024-07-20 05:44 UTC, sudhanshutech approved these changes

2024-07-20 05:45 UTC, merged