Deploying meshery designs added to layer5 learning-path
layer5io/layer5 pull request #5715
Opened 2024-07-22 21:25 UTC by Alero-Awani

**Description**

Added **Deploying Meshery Designs** to layer5 Learning path

**Notes for Reviewers**
Got this error when I tried to view the page. 

```
Error in function ChapterCard in ./src/components/Learn-Components/Chapter-Card/index.js:10
Cannot read properties of undefined (reading 'frontmatter')

./src/components/Learn-Components/Chapter-Card/index.js:10
Open in Editor
   8 |       <div className="chapter-desc">
   9 |         <h3>
> 10 |           {chapter.frontmatter.chapterTitle
     |                   ^
  11 |             ? chapter.frontmatter.chapterTitle
  12 |             : chapter.frontmatter.courseTitle}
  13 |         </h3>
```

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

2024-07-26 20:04 UTC, sudhanshutech commented
@captain-Akshay ?

2024-08-31 21:25 UTC, Ashparshp commented
@Alero-Awani, checks are facing and also, anything to update or share?

2024-10-09 10:54 UTC, sudhanshutech commented
@vishalvivekm is this something you are carrying forward?

2025-01-24 04:04 UTC, vladboisa requested changes
Hi, Looks good overall. Thank you for helping Open-Source community.
But i have 1 little attention, in your commit, we have so much PNG files.
And i think we should to compress all of them, for example [This service](tinypng.com)

2025-04-27 03:39 UTC, closed without merging