Fix: responsiveness issue#5693
layer5io/layer5 pull request #5724
Opened 2024-07-24 17:13 UTC by AlfiyaSiddique

**Description**

This PR fixes #5693 

**Notes for Reviewers**
This PR contains minor style fixes for the mobile size of a section on the blog page.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 

**Outcome**

https://github.com/user-attachments/assets/7a54bf61-9a39-476e-8c2d-0953175b801e

2024-07-24 17:29 UTC, l5io commented
🚀 Preview for commit 039d7876a6f12a690b4a42b4b06e0deb5a41f0e9 at: https://66a139ab9b9eab092ebebda6--layer5.netlify.app

2024-07-24 17:41 UTC, AlfiyaSiddique commented
Attached a recording of the outcome, let me know if it looks good or if you have any feedback. Also, let me know about the section `Related Blogs` if it also needs to be responsive as part of this issue.

2024-07-24 19:27 UTC, hargunkaur286 commented
@AlfiyaSiddique This looks good to me! Can you please confirm that when we reach the related blogs section, it does become responsive once we refresh the page(after reaching the desired responsiveness), right?

2024-07-25 09:25 UTC, hargunkaur286 commented
@AlfiyaSiddique There's one issue that you can solve as a part of this PR, make sure that "Layer5" starts from the next section, i.e. from below the image and is centered aligned on this page only. Below is a screenshot of the same. Let me know if it makes sense.
<img width="1151" alt="Screenshot 2024-07-25 at 2 55 08 PM" src="https://github.com/user-attachments/assets/51f7b049-aa52-4b79-a4a3-d0ebcf21368c">

2024-07-25 14:04 UTC, AlfiyaSiddique commented
@hargunkaur286 correct the `Related Blogs` does fit in properly after refreshing the page so no change is needed.
Will make the change for the `Layer5 Badges` Section and ping you.
Thanks for the feedback.

2024-07-27 16:25 UTC, AlfiyaSiddique commented
Hey @hargunkaur286!
The fix for the `Layer5 Badges` section is done. Do let me know if need any other changes.

2024-07-27 19:07 UTC, hargunkaur286 commented
Thank you for the contribution @AlfiyaSiddique This looks good to me!

2024-07-28 17:33 UTC, Ashparshp commented
@AlfiyaSiddique Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

2024-07-28 19:32 UTC, vishalvivekm reviewed
we''ll probably don't want to change site-wide css declarations @AlfiyaSiddique , as it may cause undesired behavior on other pages.

2024-07-28 19:36 UTC, vishalvivekm commented
```css
img.badge-modal{
max-width:95%; // prev 625px;
}
```
It's a bit too big imo.
![image](https://github.com/user-attachments/assets/5a8db80b-dfa2-4b79-9fbc-3312aace25e6)

2024-07-28 19:46 UTC, vishalvivekm requested changes
Another responsiveness issue: 
@AlfiyaSiddique  @Ashparshp @hargunkaur286 
![Screen Shot 2024-07-29 at 01 16 22](https://github.com/user-attachments/assets/18323114-e49b-4627-bd3b-12a9804c7a4d)

2024-07-28 19:48 UTC, hargunkaur286 commented
@vishalvivekm this issue resolves when we refresh the page, that's why didn't request for it. Is it valid?

2024-07-28 19:54 UTC, vishalvivekm commented
> @vishalvivekm this issue resolves when we refresh the page, that's why didn't request for it. Is it valid?

:heavy_check_mark: 
Thank you, just confirmed this on my :iphone:
> Is it valid?

Quite not.

2024-07-28 19:58 UTC, l5io commented
🚀 Preview for commit 26b2898a4db58c86f1cecd2b816e2ec01e0dce43 at: https://66a6a29cc499827ed3ad4dcd--layer5.netlify.app

2024-07-31 14:27 UTC, AlfiyaSiddique commented
> >Is it valid?

>Quite not.

@vishalvivekm What's quite not valid, can you please describe?
Do you want me to change the image width here?
```
img.badge-modal{
max-width:95%; // prev 625px;
}
```
The review comments are quite not clear to me so confirming!

2024-08-01 06:25 UTC, Ashparshp commented
@hargunkaur286 we're good to go with this PR right?

2024-08-03 16:22 UTC, Ashparshp commented
@AlfiyaSiddique Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

2024-08-12 11:35 UTC, l5io commented
🚀 Preview for commit 74d8dfaeaa3909b846b120e2af80a37b2669cc57 at: https://66b9f33ca3dcf17da5b486d0--layer5.netlify.app

2024-08-14 08:45 UTC, Muhammed-Moinuddin commented
LGTM !

2024-08-16 06:13 UTC, Ashparshp commented
@AlfiyaSiddique @hargunkaur286, is there anything more to update, or is this good to go?

2024-08-17 07:47 UTC, AlfiyaSiddique commented
@Ashparshp nothing from my side. @hargunkaur286 let me know if any more changes are needed

2024-08-17 08:04 UTC, Ashparshp commented
Thank you @AlfiyaSiddique.

2024-08-23 13:40 UTC, AlfiyaSiddique commented
@vishalvivekm, just a gentle reminder to review this PR when you get a chance so it can proceed further. Thanks!

2024-09-21 18:09 UTC, Ashparshp commented
@vishalvivekm @sudhanshutech //

2024-10-09 10:52 UTC, sudhanshutech commented
@Ashparshp is this still needed? Have you clarified the fix?

2025-01-15 20:41 UTC, closed without merging

2025-01-15 20:41 UTC, Vidit-Kushwaha commented
Already fixed; closing this pull request.