reword the CTA text
layer5io/layer5 pull request #5751
Opened 2024-07-29 20:51 UTC by siddharthbaleja7

**Description**

This PR fixes #5717 by changing the text "Open Playground" to "Open in Demo System" as requested.

**Desired Situation**

The button text "Open Playground" should be changed to "Open in Demo System".

**Contributor Resources and Handbook**

- The [layer5.io](https://layer5.io) website uses Gatsby, React, and GitHub Pages. Site content is found under the master branch.
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com) (open invite).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Notes for Reviewers**

- Ensure that the text change is correctly applied.
- Verify that the new text "Open in Demo System" is displayed appropriately in the UI.
- Check for any typos or formatting issues.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [x] Yes, I signed my commits.

2024-07-29 21:05 UTC, l5io commented
🚀 Preview for commit 6fc3f64565714104c9f8d6e8853fe98684d5291f at: https://66a803d4bbc01e80152aa9e6--layer5.netlify.app

2024-07-30 14:40 UTC, hargunkaur286 commented
@siddharthbaleja7 Thank you for your contribution! This looks good to me!

2024-07-30 14:45 UTC, hargunkaur286 commented
@siddharthbaleja7 Can you share screenshots of the changes?

2024-07-30 14:48 UTC, hargunkaur286 requested changes
These changes had to be done in the [Home](https://layer5.io/) Page 
<img width="1470" alt="Screenshot 2024-07-30 at 8 17 44 PM" src="https://github.com/user-attachments/assets/b420207f-6770-4ef1-be2f-28395888b6d5">

2024-07-30 14:49 UTC, hargunkaur286 commented
// @vishalvivekm

2024-07-30 16:18 UTC, siddharthbaleja7 commented
@hargunkaur286 should I make the changes in home page ?

2024-07-30 16:30 UTC, siddharthbaleja7 commented
@hargunkaur286, here is the screenshot.
<img width="1463" alt="Screenshot 2024-07-30 at 21 57 51" src="https://github.com/user-attachments/assets/a0bc1f18-0b98-440a-b077-5e3a990ffbe3">

2024-07-30 19:01 UTC, hargunkaur286 commented
> @l5io @hargunkaur286 should I make the changes in home page ?

Yes, please take reference from the issue description and the screenshot shared here.

2024-07-30 19:48 UTC, siddharthbaleja7 commented
@l5io @hargunkaur286 Just for clarification, I need to change "use playground" to "open in demo system," right?

2024-07-30 19:58 UTC, hargunkaur286 commented
> @l5io @hargunkaur286 Just for clarification, I need to change "use playground" to "open in demo system," right?

yes

2024-07-30 21:00 UTC, l5io commented
🚀 Preview for commit accc62039cc3ddb90617c92e48350ad83c95b4be at: https://66a95426ef94da97aa4a64ce--layer5.netlify.app

2024-07-30 21:00 UTC, hargunkaur286 commented
@siddharthbaleja7 please revert the changes from products/index.js file

2024-07-30 21:43 UTC, l5io commented
🚀 Preview for commit d6712e8438edda7181838bfaf240bd9f15d56d7e at: https://66a95e1d9f477d0086d2a4a5--layer5.netlify.app

2024-07-30 22:04 UTC, siddharthbaleja7 commented
@l5io @hargunkaur286 The reverts are done. Please review.

2024-07-31 10:27 UTC, siddharthbaleja7 commented
@l5io @hargunkaur286 The reverts are done. Please review.

2024-07-31 10:51 UTC, hargunkaur286 commented
LGTM! 🚀

2024-07-31 14:27 UTC, siddharthbaleja7 commented
@vishalvivekm Can you please review this PR?

2024-07-31 22:24 UTC, siddharthbaleja7 commented
@vishalvivekm Can you please review this PR?

2024-07-31 22:31 UTC, hargunkaur286 commented
> @vishalvivekm Can you please review this PR?

@siddharthbaleja7 The maintainers usually have a lot of PR's to review in the queue, so it would be nice, if you could be a bit patient, your PR will be reviewed. Meanwhile, please revert these changes:

<img width="1122" alt="Screenshot 2024-08-01 at 4 00 29 AM" src="https://github.com/user-attachments/assets/d9ec6b4c-c852-4816-837e-69ae95e97f2f">

2024-07-31 23:07 UTC, l5io commented
🚀 Preview for commit e6a7840701e5ae782ce12cb0452c826fc64e8d62 at: https://66aac35e4d4fb62495c8a982--layer5.netlify.app

2024-08-01 11:49 UTC, siddharthbaleja7 commented
> > @vishalvivekm Can you please review this PR?
> 
> @siddharthbaleja7 The maintainers usually have a lot of PR's to review in the queue, so it would be nice, if you could be a bit patient, your PR will be reviewed. Meanwhile, please revert these changes:
> 
> <img alt="Screenshot 2024-08-01 at 4 00 29 AM" width="1122" src="https://private-user-images.githubusercontent.com/96698544/354015100-d9ec6b4c-c852-4816-837e-69ae95e97f2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MTMxOTAsIm5iZiI6MTcyMjUxMjg5MCwicGF0aCI6Ii85NjY5ODU0NC8zNTQwMTUxMDAtZDllYzZiNGMtYzg1Mi00ODE2LTgzN2UtNjlhZTk1ZTk3ZjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDExNDgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlNDYxYWM0Mjk3NzRkYmRjOGU0YzljYjEyYzlmMjYwYTJiMTdlZTgzMTA3YzUwYzQzZWRiMDhlYmZhYmU3NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n8B_rBoq7bpqyURUXSMVM24_5Ji8vd6_FkdesAuYqJI">

@hargunkaur286 The export default index; line has no changes from the original and does not need to be reverted. There should be no issue with keeping it as is.

2024-08-02 14:15 UTC, siddharthbaleja7 commented
@vishalvivekm Can you please review this PR?

2024-08-02 18:01 UTC, l5io commented
🚀 Preview for commit 175ce2103f6661b72e1876a25c0411de32a98553 at: https://66ad1e8995b5979132e48c6d--layer5.netlify.app

2024-08-02 18:07 UTC, closed without merging