Update metrics
layer5io/layer5 pull request #5756
Opened 2024-07-31 22:34 UTC by Ashparshp

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-07-31 22:49 UTC, l5io commented
🚀 Preview for commit 65ba0c34386fd39be035cd166da7feb4765828c5 at: https://66aabf32521aed299f9ece00--layer5.netlify.app

2024-08-05 16:49 UTC, sudhanshutech requested changes

2024-08-05 16:49 UTC, sudhanshutech commented on src/collections/programs/lfx-2024/lfx-2024.mdx
> +Layer5 is all about <Link to="/community">its community</Link> of contributors. We have designed an onboarding program customized to <Link to="/community/newcomers">meet newcomers</Link> where they’r
The line `around for a year and half `needs to be updated with more specific. // @vishalvivekm can you?

2024-08-17 03:50 UTC, sudhanshutech commented
@Ashparshp is this done ? Have you confirmed the metric by asking someone and are feedbacks incorporated

2024-08-17 06:19 UTC, Ashparshp commented
@sudhanshutech, still waiting for a number from you..

2024-08-22 12:28 UTC, sudhanshutech commented
> @sudhanshutech, still waiting for a number from you..

// @vishalvivekm

2024-08-22 13:12 UTC, leecalcote commented on src/collections/programs/lfx-2024/lfx-2024.mdx
> +Layer5 is all about <Link to="/community">its community</Link> of contributors. We have designed an onboarding program customized to <Link to="/community/newcomers">meet newcomers</Link> where they’r
```suggestion
Layer5 is all about <Link to="/community">its community</Link> of contributors. We have designed an onboarding program customized to <Link to="/community/newcomers">meet newcomers</Link> where they’re at and developed an onboarding buddy program, <Link to="/community/meshmates">MeshMates</Link> with individuals dedicated to assisting contributors. The Layer5 community and its open source projects are thriving.
```

2024-08-22 13:12 UTC, merged