Fix placeholder text in Text Input component
layer5io/layer5 pull request #5769
Opened 2024-08-02 18:39 UTC by siddharthbaleja7

### Description
This PR addresses an issue with the placeholder text in the Text Input component. The current placeholder text reads "PlaceHolder goes here" when it should be "placeHolder". 

### Expected Behavior
The placeholder text should be updated to display "placeHolder" instead of "PlaceHolder goes here". You can review the component at [Sistent Text Input](https://layer5.io/projects/sistent/components/text-input) for reference.

### Changes Made
- Updated the placeholder text from "PlaceHolder goes here" to "placeHolder" in the Text Input component.

Please review the changes and let me know if further adjustments are needed.

2024-08-02 18:53 UTC, l5io commented
🚀 Preview for commit 27350030afa62cd6c6f54de6813d396a0f94d83f at: https://66ad2ae995b5979fbce46b75--layer5.netlify.app

2024-08-02 19:33 UTC, l5io commented
🚀 Preview for commit fcdf1acf359a4e033ba330ca9d9601577455fcf5 at: https://66ad342943ec4dab4df6f5e9--layer5.netlify.app

2024-08-02 20:50 UTC, siddharthbaleja7 commented
@Ashparshp Can you please review this PR.

2024-08-03 06:38 UTC, siddharthbaleja7 commented
@Ashparshp Can you please review this PR.

2024-08-03 16:15 UTC, Ashparshp commented
@siddharthbaleja7 Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

2024-08-05 17:08 UTC, sudhanshutech requested changes

2024-08-05 17:08 UTC, sudhanshutech commented on src/sections/Projects/Sistent/components/text-input/guidance.js
> +              <Input placeholder="PlaceHolder" />
use 
```suggestion
              <Input placeholder="Placeholder" />
```

2024-08-08 05:23 UTC, sudhanshutech commented
@siddharthbaleja7 there is a small change requested. Will you able to quickly complete that?

2024-08-08 05:27 UTC, siddharthbaleja7 commented
@sudhanshutech Sure

2024-08-08 05:49 UTC, l5io commented
🚀 Preview for commit 975273ac49ddac7b30e44b3a4a92ec9b08b0c977 at: https://66b45c24be40e59a6a01572d--layer5.netlify.app

2024-08-08 05:51 UTC, sudhanshutech approved these changes

2024-08-08 05:51 UTC, merged