Improved the UI of ebpf and other svg's for better visibility in dark mode
layer5io/layer5 pull request #5819
Opened 2024-08-15 06:46 UTC by Suswetha6

**Description**

This PR fixes #5070 

**Notes for Reviewers**
I've added a new property in the theme objects in themeStyles.js and updated the css of svg in meshmap section.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-08-15 07:01 UTC, l5io commented
🚀 Preview for commit a486635f3ef731735081191dc4c0b1d05a03ddfe at: https://66bda7570d0bf57b1954d8ab--layer5.netlify.app

2024-08-15 19:51 UTC, narasimha-1511 commented
Hey @Suswetha6 please sign the commits using -s , now you need to rebase and squash them

2024-08-15 20:57 UTC, narasimha-1511 commented
<img width="526" alt="Screenshot 2024-08-16 at 2 26 54 AM" src="https://github.com/user-attachments/assets/4a2561ea-9c5b-4738-a95d-834f267d7657">
You should not add the boder box or something kindly change the svg itself which appears better in the dark mode

2024-08-15 20:59 UTC, narasimha-1511 requested changes
kindly remove these borders and update the svg

2024-08-15 20:59 UTC, narasimha-1511 commented on src/sections/Meshmap/meshmap-catalog.js
> +    border: 2px solid ${props => props.theme.borderColorWhiteToTransparent};
remove these borders

2024-08-16 05:58 UTC, Ashparshp commented on CNAME
@Suswetha6, why did you remove this file?

2024-08-16 05:59 UTC, Ashparshp commented
@narasimha-1511, do we have a svg for this? and @Suswetha6, please fix the DCO sign-off. If you're unaware, read more about it in the contributing guide.

2024-08-19 06:14 UTC, Ashparshp commented
@Suswetha6, Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

2024-08-19 12:17 UTC, Ashparshp commented
@Suswetha6, please join. The meeting has started.

2024-08-21 05:35 UTC, Ashparshp commented
@Suswetha6, any luck?

2024-08-22 03:58 UTC, Ashparshp commented
@Suswetha6, checking again?

2024-08-22 06:56 UTC, Suswetha6 commented
Hey @narasimha-1511  , sorry i was not available. I am not sure how to do the DCO sign-off, i will read about it and do it by eod

2024-08-22 07:17 UTC, l5io commented
🚀 Preview for commit 0aada74a41115d3bad8b8e09a0738bdb4ea6ed14 at: https://66c6e5c9cde1b814330e07c2--layer5.netlify.app

2024-08-31 19:00 UTC, Ashparshp commented
@Suswetha6, any update?

2024-08-31 22:35 UTC, vishalvivekm commented on CNAME
@Suswetha6 Why is this file deleted ? will you revert this change please ?

2024-08-31 22:39 UTC, vishalvivekm requested changes
I don't see any difference this PR makes to the svgs what we have right now: 
![image](https://github.com/user-attachments/assets/baa369fe-a6fe-41c2-a0fa-dad75d1aaf04)

2024-08-31 22:40 UTC, vishalvivekm commented on src/theme/app/themeStyles.js
will you please sound off why are these theme changes are being introduced ? @Suswetha6

2024-09-02 06:40 UTC, closed without merging