Add layer5 learning paths blog
layer5io/layer5 pull request #5841
Opened 2024-08-25 10:43 UTC by Shubhf

**Description**

This PR fixes #5796 and #2323 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-08-25 11:00 UTC, l5io commented
🚀 Preview for commit 66c05dd09174a5ab3e10874ab66a4ce05a8eff9c at: https://66cb0e26b3f6bcf1f22f6e41--layer5.netlify.app

2024-08-26 19:00 UTC, sudhanshutech requested changes

2024-08-26 19:00 UTC, sudhanshutech commented on .github/ISSUE_TEMPLATE/2024-08-06-introducing-layer5-learning-paths.md
> +title: "Introducing Layer5 Learning Paths"
@Shubhf you still adding a blog under .github folder . why? This is a workflow directory not a blog

2024-08-26 19:01 UTC, sudhanshutech commented
All checks failing. @Ashparshp review carefully

2024-08-31 07:16 UTC, Ashparshp commented
@Shubhf, will u fix?

2024-09-07 13:33 UTC, sudhanshutech commented
@Shubhf understand the codebase then you can pick the issue again. Thanks

2024-09-07 13:33 UTC, closed without merging