Member Profile of Jerens Lensun
layer5io/layer5 pull request #5844
Opened 2024-08-26 10:35 UTC by Spoorthy1423

**Description**
#5835 [Community] Created member profile of Jerens Lensun

This PR fixes #5835 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ Yes] Yes, I signed my commits.

2024-08-26 13:38 UTC, hargunkaur286 commented
@Spoorthy1423 Thank you for working on this pr. A few points to note: For the "position" placeholder, we give the position that the member has in the community i.e. of a "contributor", and the layer5 profile's link is given in the issue description, please refer other files to see how will it be incorporated.

2024-08-26 19:02 UTC, sudhanshutech requested changes

2024-08-26 19:02 UTC, sudhanshutech commented on src/collections/members/jeres-lensun/index.mdx
> +  - ui-ux
remove these two badge and meshery badge please

2024-08-27 17:18 UTC, vishalvivekm commented on src/collections/members/jeres-lensun/index.mdx
> +image_path: ./jerens-lensun.jpeg
```suggestion
image_path: ./JerensProfilePic.jpg
```

2024-08-27 17:19 UTC, vishalvivekm commented on src/collections/members/jeres-lensun/index.mdx
> +community_manager: no
```suggestion
```

2024-08-27 21:39 UTC, l5io commented
🚀 Preview for commit 629f5ee86b1fbc699403eeab555f37fff7260273 at: https://66ce4757d1e9df8b9080359e--layer5.netlify.app

2024-08-27 22:16 UTC, Spoorthy1423 commented
@vishalvivekm  i passed all the checks and if anything more needed let me know.

2024-08-28 04:46 UTC, sudhanshutech approved these changes

2024-08-28 04:46 UTC, merged