Add contributor
layer5io/layer5 pull request #5852
Opened 2024-08-29 16:40 UTC by AlfiyaSiddique

**Description**

This PR fixes #5837 

**Notes for Reviewers**
* Two files added to complete this task namely, `index.mdx` and profile image

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-08-29 16:47 UTC, sudhanshutech requested changes

2024-08-29 16:47 UTC, sudhanshutech commented on src/collections/members/senthil-athiban/index.mdx
> +  - meshery
@AlfiyaSiddique add only meshery and meshmap badge

2024-08-29 16:54 UTC, vishalvivekm commented on src/collections/members/senthil-athiban/index.mdx
> +image_path: './senthil-athiban/profile.png'
```suggestion
image_path: './senthil-athiban/senthil-athiban.png'
```

2024-08-29 16:55 UTC, vishalvivekm commented on src/collections/members/senthil-athiban/index.mdx
> +  - meshery
```suggestion
  - meshery
```

2024-08-29 16:55 UTC, vishalvivekm commented on src/collections/members/senthil-athiban/index.mdx
> +bio: Senthil Athiban is passionate about software development, with a keen interest in building products that solve real-world problems. His journey began with crafting the UI/UX of modern websites,
```suggestion
bio: "Senthil Athiban is passionate about software development, with a keen interest in building products that solve real-world problems. His journey began with crafting the UI/UX of modern websites, where he developed a deep appreciation for intuitive design and user experience. He is continuously exploring the tech world, driven by an insatiable thirst for knowledge that won't be quenched until he reaches the last drop. When he's not coding or contributing to open-source projects on GitHub, you can find him on the football field, channeling his energy into his love for the game."
```

2024-08-29 17:53 UTC, l5io commented
🚀 Preview for commit bb1e61ec0b625ec3a1dd8a07552ca69f056d96b6 at: https://66d0b53dad88236125de7747--layer5.netlify.app

2024-08-30 12:05 UTC, AlfiyaSiddique commented
The requested changes are done by @vishalvivekm. Please review again @sudhanshutech!

2024-08-31 07:15 UTC, Ashparshp requested changes
@AlfiyaSiddique, please compress the profile image and change it to the `.webp` format.

2024-08-31 14:53 UTC, Mandeep56Singh commented
@AlfiyaSiddique you need to apply the changes requested by @sudhanshutech. Only then your PR can be merged.

2024-08-31 16:08 UTC, l5io commented
🚀 Preview for commit 166c39d2509d91aaffcc3cf87d88073cceda3f72 at: https://66d33f6fa10a303d97d87dfd--layer5.netlify.app

2024-08-31 17:48 UTC, AlfiyaSiddique commented
@Ashparshp changed the image type to `webp` and the size of image is 27 kb, let me know if it needs to be compressed more!

2024-08-31 18:59 UTC, Ashparshp approved these changes
LGTM! Thank you @AlfiyaSiddique.

2024-08-31 22:05 UTC, vishalvivekm approved these changes

2024-08-31 22:06 UTC, merged

2024-08-31 22:07 UTC, vishalvivekm commented
### Yay! :balloon: :tada: :rocket:
@senthil-athiban