Mdx2 upgrade v3
layer5io/layer5 pull request #5925
Opened 2024-09-24 19:31 UTC by Aviral0702

**Description**

This PR fixes #
Aims to migrate to MDX V2 and gatsby-plugin-mdx v4

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-09-25 15:42 UTC, sudhanshutech commented
where are the other build checks here?

2024-09-25 15:46 UTC, sudhanshutech requested changes
why there is changes in md and yml files , i don't understand?

2024-09-25 15:47 UTC, sudhanshutech commented
@Aviral0702 will you explain the breaking changes here while migarte.

2024-09-26 15:00 UTC, sudhanshutech commented
please reply on all of the questions asked above .

2024-09-26 15:01 UTC, sudhanshutech commented
> > why there is changes in md and yml files , i don't understand?
> 
> The older configurations of mdx files are not compatible with new rules of parsing mdx files in MDX V2. That is why we need to change the configuration here and if it works we will permanently change the configuration of these files.

is it? i still don't understand why yml files are been changed here

2024-09-26 17:26 UTC, Aviral0702 commented
> @Aviral0702 merge conflicts

resolved.

2024-09-30 04:30 UTC, vishalvivekm commented
@Aviral0702 @sudhanshutech 
Let's discuss this during the website call on Monday at 5:30 PM IST (7:00 AM CT).

Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

2024-09-30 04:30 UTC, vishalvivekm commented
I've added this to the agenda items @sudhanshutech @Aviral0702

2024-10-09 22:46 UTC, leecalcote commented on .github/workflows/lighthouseci.yml
I'm missing it. What changed in these files?

2024-10-14 07:36 UTC, vishalvivekm commented
@Aviral0702 
Are we discussing updates on this PR today on websites' call ?

2024-10-21 00:33 UTC, closed without merging