added interview of Aisuko Li
layer5io/layer5 pull request #6003
Opened 2024-10-17 08:24 UTC by hargunkaur286

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-10-17 08:37 UTC, l5io commented
🚀 Preview for commit be7857f49b76fb229eb23be42387c75046d44d0b at: https://6710cc8006ee75bc43db7465--layer5.netlify.app

2024-10-17 08:47 UTC, Touriist commented
@hargunkaur286 clicking on Anita's picture takes to community/members/undefined
![image](https://github.com/user-attachments/assets/5d6c13f6-9d2f-4933-aa27-dd4eba297be1)

2024-10-21 01:23 UTC, vishalvivekm commented
@hargunkaur286 
Thank you for your contribution!
Let's discuss this during the website call on Monday at 5:30 PM IST (7:00 AM CT).

Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

2024-10-23 03:53 UTC, Aisuko commented
What should I do for this PR? I think maybe this link can be as a reference https://layer5.io/blog/announcements/announcing-meshery-v050

2024-10-24 18:05 UTC, l5io commented
🚀 Preview for commit e62009b87fa10481f620135cdcd06a2fde611e2e at: https://671a8c12c6e19e1d5fbe7f33--layer5.netlify.app

2024-10-25 04:12 UTC, leecalcote commented on src/collections/blog/2024/09-27-meet-the-maintainer-aisuko-li/aisuko-li-layer5-maintainer.png
We have a newer, cooler member card style (in Figma) that can be used, if you like.

2024-10-25 04:14 UTC, leecalcote requested changes

2024-10-25 04:14 UTC, leecalcote commented on src/collections/blog/2024/09-27-meet-the-maintainer-aisuko-li/post.mdx
> +  <p>What is so fascinating about service meshes?</p>
@hargunkaur286 terrible question. I've repeatedly asked that we distance the project from service meshes as much as possible. Will you please see that this question is either removed or replaced with another?

2024-10-25 04:14 UTC, leecalcote commented
@hargunkaur286 you are most welcome to insert your name as the interviewer, if you like.

2024-11-02 05:24 UTC, l5io commented
🚀 Preview for commit 897b1c349324f8e528f8e9e5466f105391df9ede at: https://6725b749667d6a1cfc6b39a8--layer5.netlify.app

2024-11-23 14:32 UTC, merged