Add TextField component to the sistent components page #5948
layer5io/layer5 pull request #6008
Opened 2024-10-19 15:24 UTC by nooras

**Description**
Add TextField component to the sistent components page

This PR fixes #
#5948 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 
Screenshot:
![screencapture-localhost-8000-projects-sistent-components-2024-10-19-20_19_31](https://github.com/user-attachments/assets/64bb788e-4562-42dd-a42f-84c2201d27ac)

2024-10-19 15:37 UTC, l5io commented
🚀 Preview for commit bfd7e4ca470fae778d1c2a8aaa75b0d52361625e at: https://6713d1eb18a026d785930e4c--layer5.netlify.app

2024-10-19 16:05 UTC, l5io commented
🚀 Preview for commit 76aae3371601356825f07b8c693d1fe1c30d30ae at: https://6713d883ee5caad9b39ed31e--layer5.netlify.app

2024-10-21 01:22 UTC, vishalvivekm commented
@nooras 
Thank you for your contribution!
Let's discuss this during the website call on Monday at 5:30 PM IST (7:00 AM CT).

Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

2024-10-21 11:28 UTC, vishalvivekm commented
> @nooras Thank you for your contribution! Let's discuss this during the website call on Monday at 5:30 PM IST (7:00 AM CT).
> 
> Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

adding

2024-10-22 05:24 UTC, sudhanshutech requested changes

2024-10-22 05:24 UTC, sudhanshutech commented on src/sections/Projects/Sistent/components/text-field/index.js
> +          <h2>TextField</h2>
Text Field

2024-10-22 05:24 UTC, sudhanshutech commented on src/sections/Projects/Sistent/components/text-field/code-block.js
> +export const CodeBlock = ({ name, code }) => {
@nooras isn't code block component already there then why creating new?

2024-10-22 05:25 UTC, sudhanshutech requested changes
add some space
![image](https://github.com/user-attachments/assets/299d4847-b1a3-40a2-af15-c1d6e84687b6)

2024-10-22 05:25 UTC, sudhanshutech commented
merge conflicts...

2024-10-23 17:59 UTC, l5io commented
🚀 Preview for commit d2c1f526724894b413b00ed2842f7e42a7df71aa at: https://671939227bdcdc52dccce67e--layer5.netlify.app

2024-10-24 07:31 UTC, l5io commented
🚀 Preview for commit ff800ee5f638fa371fbdddcf5f7d363a0bae9661 at: https://6719f7a3f1138a8875d68370--layer5.netlify.app

2024-10-24 14:13 UTC, sudhanshutech approved these changes

2024-10-24 14:13 UTC, merged