Added the avatar section
layer5io/layer5 pull request #6021
Opened 2024-10-22 12:27 UTC by NishantSinghhhhh

Description

Component Name: Avatar component present in Sistent component folder.

This PR addresses various enhancements and features, including:

- Documentation: I have written documentation for the Avatar Component used in the Sistent repository.
- Avatar Variants: Added different styles for avatars, including square, rounded, and customizable sizes to enhance user experience.
- Security Practices: Documented best practices for using avatars with proper alt text for accessibility.

Notes for Reviewers

Please pay special attention to the documentation and feedback on these changes would be greatly appreciated.

Signed commits

Yes, I signed my commits.

2024-10-22 12:39 UTC, l5io commented
🚀 Preview for commit e8c9fa513927d141b6b85f404546742f7ccf43a3 at: https://67179cd4a8981b0c7b1ae4b8--layer5.netlify.app

2024-10-22 19:44 UTC, l5io commented
🚀 Preview for commit 20d6f1cb84cee3455dae84991e7806df2340e3c5 at: https://67180066d051d5b1630ff7d3--layer5.netlify.app

2024-10-23 07:04 UTC, NishantSinghhhhh commented
@sudhanshutech sir can you review it and merge this PR if possible

2024-10-23 13:55 UTC, l5io commented
🚀 Preview for commit f006e1383e5e7ab2b45c171b5b88387626bc6506 at: https://6719002053ba8600eaf9bdac--layer5.netlify.app

2024-10-23 16:33 UTC, l5io commented
🚀 Preview for commit 2352ed6df155156988a07309017b329c57956a2a at: https://671925300d8a2b3794faef38--layer5.netlify.app

2024-10-24 13:45 UTC, NishantSinghhhhh commented
@nebula-aac , I have resolved conflicts from this branch too ! :-)

2024-10-24 13:59 UTC, l5io commented
🚀 Preview for commit bc1f486c5f34edc2c7c2191fa4afb9204ba5aee6 at: https://671a52512aedc81ce200b984--layer5.netlify.app

2024-10-24 14:09 UTC, sudhanshutech requested changes
@NishantSinghhhhh would you please use some other characters for avatar like any cartoon characters instead our people. It would be also good if you can use any existing images already there

2024-10-24 14:15 UTC, NishantSinghhhhh commented
> @NishantSinghhhhh would you please use some other characters for avatar like any cartoon characters instead our people. It would be also good if you can use any existing images already there

Sir Can I find Cartoon images in the layer5 folder ??

2024-10-24 14:16 UTC, sudhanshutech commented
@NishantSinghhhhh you can use the five images. It should be in layer5 repo only or you will get from layer5 brand page

2024-10-24 14:20 UTC, NishantSinghhhhh commented
> @NishantSinghhhhh you can use the five images. It should be in layer5 repo only or you will get from layer5 brand page

sir can you please provide the link of possible

2024-10-24 14:21 UTC, sudhanshutech commented
https://layer5.io/company/brand

2024-10-24 17:06 UTC, l5io commented
🚀 Preview for commit 4c378f5b7b459d4f4c6a351ea2dde85c7923f961 at: https://671a7e0eb4c16313edc28ba9--layer5.netlify.app

2024-10-24 17:42 UTC, l5io commented
🚀 Preview for commit adc7e43879391c393b37a63de3f262dd213b57df at: https://671a8672b4c1632114c28fe2--layer5.netlify.app

2024-10-24 17:51 UTC, leecalcote commented
Cool. Thank you, @NishantSinghhhhh and @nebula-aac 🙌

2024-10-24 18:01 UTC, NishantSinghhhhh commented
> Cool. Thank you, @NishantSinghhhhh and @nebula-aac 🙌

Pleasure Sir

2024-10-25 10:55 UTC, NishantSinghhhhh commented
@sudhanshutech , sir can you have a look at this PR once again

2024-10-27 08:32 UTC, l5io commented
🚀 Preview for commit 1b7c37658fda1f75bfc8182e4ed650fa838b0c83 at: https://671dfa5adecd37137335b6ef--layer5.netlify.app

2024-10-28 07:10 UTC, vishalvivekm commented
@NishantSinghhhhh 
Thank you for your contribution!
Let's discuss this during the website call on Monday at 5:30 PM IST (7:00 AM CT).

Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

2024-10-30 12:24 UTC, l5io commented
🚀 Preview for commit 6beebac3ed70dbe7cb6796845838535adbc25b97 at: https://672225348e16a69496197562--layer5.netlify.app

2024-11-08 21:22 UTC, sudhanshutech commented
@vishalvivekm did you pointed @NishantSinghhhhh to those svgs we talked about in call?

2024-12-09 20:38 UTC, leecalcote commented
> @vishalvivekm did you pointed @NishantSinghhhhh to those svgs we talked about in call?

@NishantSinghhhhh will you be completing this PR?

2025-01-02 11:55 UTC, sudhanshutech commented
I am closing this pr since this pr has been abandoned . @NishantSinghhhhh feel free to open when you are back.

2025-01-02 11:55 UTC, closed without merging