Added new project helm-kanvas-snapshot to backend table
layer5io/layer5 pull request #6024
Opened 2024-10-23 05:57 UTC by balagowda

**Description**

This PR fixes #5928

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-10-23 06:11 UTC, l5io commented
🚀 Preview for commit bf0f8d09f87e1769354c649313522c50eda83fb9 at: https://671893193fdedc3dc893ba19--layer5.netlify.app

2024-10-24 15:41 UTC, sudhanshutech requested changes

2024-10-24 15:41 UTC, sudhanshutech commented on src/sections/Community/Handbook/repo-data.js
> +        "A Helm chart for deploying Kanvas, a Meshery component for enhanced observability and management workflows.",
```suggestion
        "The Kanvas Snapshot Helm Plugin allows users to generate a visual snapshot of their Helm charts directly from the command line.",
```

2024-10-24 16:25 UTC, sudhanshutech approved these changes

2024-10-24 16:25 UTC, merged