Made the kanvas logo responsive
layer5io/layer5 pull request #6072
Opened 2024-11-10 16:28 UTC by NishantSinghhhhh

Description

This PR fixes #6069

Notes for Reviewers:
This PR makes the logo of bigger size 
**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-11-10 16:33 UTC, vishalvivekm commented on src/sections/Kanvas/kanvas_banner.js
> +        margin-top: -7rem;
```suggestion
```

2024-11-10 16:33 UTC, vishalvivekm commented on src/sections/Kanvas/kanvas_banner.js
> +        margin-top: -7rem;
the style is already look 3 lines above

2024-11-10 16:33 UTC, vishalvivekm commented on src/sections/Kanvas/kanvas_banner.js
> +        margin-top: -7rem;
```suggestion
```

2024-11-10 16:34 UTC, vishalvivekm commented on src/sections/Kanvas/kanvas_banner.js
> +        margin-top: -7rem;
```css
margin-top: -7rem;
```

is by default for the `.kanvas-logo`, unless we're modifying the value, writing it again is redundant.

2024-11-10 16:45 UTC, l5io commented
🚀 Preview for commit 7a2003268176ccef6e73a21172517cedd5ea5a9b at: https://6730e2c2a9cb37e30ceca63c--layer5.netlify.app

2024-11-10 16:48 UTC, NishantSinghhhhh commented
@vishalvivekm , I have done the requested changes

2024-11-10 17:03 UTC, l5io commented
🚀 Preview for commit 3e998c372785d096a8e3a8598414d6d0daab43f1 at: https://6730e708e3f337e7b9e4a264--layer5.netlify.app

2024-11-10 19:30 UTC, vishalvivekm commented
@NishantSinghhhhh please take a look at : https://github.com/layer5io/layer5/pull/6070

2024-11-11 09:39 UTC, vishalvivekm commented
@NishantSinghhhhh Thank you for your contribution!
Let's discuss this during the website call on Monday at 5:30 PM IST (7:00 AM CT).

Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

2024-11-15 03:51 UTC, sudhanshutech commented
@NishantSinghhhhh any screenshot?

2024-12-09 20:37 UTC, leecalcote requested changes
This doesn't appear to fix either issue on the home page or the kanvas page. Am I missing something, @NishantSinghhhhh?
<img width="418" alt="Screenshot 2024-12-09 at 2 36 02 PM" src="https://github.com/user-attachments/assets/0d52031d-2d41-464e-b082-083689e027e4">

2024-12-10 00:15 UTC, leecalcote commented
PR abandoned. Fix provided elsewhere.

2024-12-10 00:15 UTC, closed without merging