fix: opportunty card responsiveness
layer5io/layer5 pull request #6082
Opened 2024-11-15 13:14 UTC by upsaurav12

**Description**

This PR fixes #5997

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-11-15 13:21 UTC, upsaurav12 commented
@vishalvivekm, I have used ``RowWrapper`` for this as it was discussed in last meet. Sorry i was not able to finish this due to exams.

2024-11-15 16:53 UTC, upsaurav12 commented
if i want to see if there is no other side effect how can i find that ??

2024-11-18 11:51 UTC, vishalvivekm commented
@upsaurav12 
Thank you for your contribution!
Let's discuss this during the website call on Monday at 6:30 PM IST

adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

2024-12-02 12:19 UTC, l5io commented
🚀 Preview for commit ce8c583f8486c06b90c96ab07acf5fb19145f152 at: https://674da576a6b5e107d922b7ed--layer5.netlify.app

2024-12-04 12:39 UTC, upsaurav12 commented
@vishalvivekm i have made some changes in ``career/career-single/index.js`` file for this page https://layer5.io/careers/software-engineer. It was fixed through ``<Row>`` component by ``flex:wrap`` but it still had some issues like alignment. so i just changed breakpoints from ``767px tp 1200px.``. 
Is approach should be a correct approach?

2024-12-05 04:36 UTC, l5io commented
🚀 Preview for commit 5d791d44d367870681bbbb7191b9d42085367606 at: https://67512d916e19bba79409ca69--layer5.netlify.app

2024-12-13 16:10 UTC, leecalcote commented
@mdkaifansari04 will you give this a review?

2024-12-13 16:39 UTC, leecalcote commented
merge conflicts...

2024-12-13 17:14 UTC, l5io commented
🚀 Preview for commit d006c2b97fb2dc989514cf12f1d8af10f3592f6b at: https://675c6b0f28119a48dc77104a--layer5.netlify.app

2024-12-14 20:46 UTC, mdkaifansari04 requested changes
Else it is fine, just check if it can be done more better way using best practices

2024-12-15 10:16 UTC, upsaurav12 commented
@mdkaifansari04 thank you for suggestions. 
There are many ``<Row>`` components that have responsive issue, but i am not sure whether it is related to``<Row>`` component or they can be solve individually.

2024-12-15 10:38 UTC, mdkaifansari04 commented
You can try debugging it, also if you wanted to know more about `Row` component you should look into Sistent repo. 

If it has some predefined styles, try updating it or try passing styles directly into `Row` component. (If required)

2025-04-27 03:39 UTC, closed without merging