Removed posthog dependency from the site
layer5io/layer5 pull request #6125
Opened 2024-12-18 12:37 UTC by aakankshabhende

**Description**
Removed posthog dependency from the site

This PR fixes #6110 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-12-18 12:53 UTC, l5io commented
🚀 Preview for commit d8e98404abf9a42e54706f768eddc513ea66cdb5 at: https://6762c50bca1f4700b877ed6e--layer5.netlify.app

2024-12-19 01:12 UTC, sudhanshutech requested changes
why you are removing from integrations? they ae different thing so you don't have to remove anything from integrations directory.

2024-12-19 06:35 UTC, l5io commented
🚀 Preview for commit b1574b8d05de351dd22f9b6b17606700c5c44e78 at: https://6763be776e5d9b3154853f51--layer5.netlify.app

2024-12-22 10:53 UTC, sudhanshutech approved these changes

2024-12-22 10:54 UTC, merged