Add toggle-button component
layer5io/layer5 pull request #6127
Opened 2024-12-19 14:49 UTC by eyeaadil

**Description**

This PR fixes #5958 

**Notes for Reviewers**

For complete changes check the given link
https://6764ee9243e3a0d6fe4821ce--layer5.netlify.app/projects/sistent/components/toggle-button/guidance

ScreenShot
![image](https://github.com/user-attachments/assets/173a6c94-8196-4d86-8ec9-a5c37e2612c2)

![image](https://github.com/user-attachments/assets/5ef12a0c-9ae7-4ccd-8c20-e26b692c2a22)

![image](https://github.com/user-attachments/assets/c1487c70-b9dd-433c-8fb8-b6de0d3f363e)

![image](https://github.com/user-attachments/assets/12b99547-a7ef-4058-846d-5771c702ed2b)

![image](https://github.com/user-attachments/assets/213eb7b5-474d-427f-9f0c-1095650b55f5)

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-12-19 15:07 UTC, l5io commented
🚀 Preview for commit fe4e389f3a0d110d3667db6dd84b8189909fe570 at: https://6764364266069e46100ebd59--layer5.netlify.app

2024-12-19 15:49 UTC, eyeaadil commented
@l5io  ,can you please review this PR?

2024-12-19 19:03 UTC, Pratik-050 requested changes
Also make sure to include a screenshot or screen recording of the changes you've made, that'll make the review process easier.
Revert the changes in package-lock.json and gatsby-node.js

2024-12-20 03:24 UTC, l5io commented
🚀 Preview for commit 1f86b767e1f56f638dfb109b52d755411a5977c7 at: https://6764e31e62c055bf7dc6cd61--layer5.netlify.app

2024-12-20 04:13 UTC, l5io commented
🚀 Preview for commit ee92d60856948ccd86330db5fafbf2fa1ae84a92 at: https://6764ee9243e3a0d6fe4821ce--layer5.netlify.app

2024-12-21 07:20 UTC, eyeaadil commented
@Vidit-Kushwaha ,can you please review this?

2024-12-22 19:45 UTC, Pratik-050 commented
@eyeaadil still I can see changes in package.json and gatsby-node.js

2024-12-23 05:02 UTC, sudhanshutech requested changes
@eyeaadil revert changes in package lock file

2024-12-23 05:04 UTC, sudhanshutech commented
@eyeaadil 
Thank you for your contribution!
Let's discuss this during the website call on Monday at 6:30 PM IST (7:00 AM CT).

Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?tab=t.0).

2024-12-23 13:43 UTC, Vidit-Kushwaha commented on gatsby-node.js
Revert changeous in this file

2024-12-23 13:43 UTC, Vidit-Kushwaha commented on package-lock.json
Same

2024-12-23 13:53 UTC, Vidit-Kushwaha commented on src/sections/Projects/Sistent/components/toggle-button/index.js
Button name is not intuitive can we change button name from `Bold, Underline, and italic` to another name like `toogle button 1`

2024-12-23 13:57 UTC, Vidit-Kushwaha requested changes
@eyeaadil I have added a few comments. You can look into it

2024-12-26 04:21 UTC, l5io commented
🚀 Preview for commit 787218b2c2280fe6baeca82cb68a86da7f1d940f at: https://676cd9847770b4210ed2db12--layer5.netlify.app

2024-12-28 03:35 UTC, l5io commented
🚀 Preview for commit 24a1a2d7901d139d70abcff74392d8a363b7aafb at: https://676f71b18b0d230ae93b1da2--layer5.netlify.app

2024-12-28 04:24 UTC, l5io commented
🚀 Preview for commit 22dd684a9444cbd645418246af1e80775c578d3f at: https://676f7d134e307413f8e3317a--layer5.netlify.app

2024-12-30 10:59 UTC, SAHU-01 commented
@eyeaadil looks like you've implemented the recommended changes, please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?tab=t.0).
And maybe we can close merge and close this PR.

2024-12-30 12:19 UTC, Vidit-Kushwaha requested changes
@eyeaadil I have given you some input; otherwise, It look good to me 🙌

2024-12-30 12:19 UTC, Vidit-Kushwaha commented on src/components/handbook-navigation/TocPagination.js
> +        <Button $primary $url={content[currentPage + 1]?.link} onClick={() => console.log("button is clicked")}>
Remove the `onCLick` statment from the button
```suggestion
        <Button $primary $url={content[currentPage + 1]?.link}>
```

2024-12-30 12:19 UTC, Vidit-Kushwaha commented on package-lock.json
Revert changeous in this file

2025-01-01 18:06 UTC, l5io commented
🚀 Preview for commit 4d910165bcfd17bb20fbd08e1674d705d81a118c at: https://6775837cc3164cd54fa04d7c--layer5.netlify.app

2025-01-01 18:21 UTC, eyeaadil commented
@Vidit-Kushwaha @SAHU-01 , now can you please review this? If there are still any issues, please let me know.

2025-01-02 04:02 UTC, sudhanshutech commented
@eyeaadil revert you change form package-lock json please

2025-01-02 19:11 UTC, l5io commented
🚀 Preview for commit 0de525eb960022eb912a72f210abdc38ed8443a3 at: https://6776e4ace1dbb39360c32a4d--layer5.netlify.app

2025-01-03 03:52 UTC, eyeaadil commented
> @eyeaadil revert you change form package-lock json please

i revert the changes in package-lock.json ,now can review this ?

2025-01-03 03:53 UTC, eyeaadil commented
@sudhanshutech @SAHU-01 @Vidit-Kushwaha ,can you please review and merge this PR if there is no changes needed.

2025-01-03 19:34 UTC, Vidit-Kushwaha approved these changes
@eyeaadil, Looks good to me. @sudhanshutech we can merge into master

2025-01-04 18:00 UTC, eyeaadil commented
@sudhanshutech , can you please review this and merge this PR if there is no changes needed.

2025-01-04 20:00 UTC, leecalcote commented on gatsby-node.js
> +
@eyeaadil ?

2025-01-13 06:45 UTC, merged