[UI]: Open source Pricing form
layer5io/layer5 pull request #6129
Opened 2024-12-23 10:15 UTC by SAHU-01

**Description**

This PR fixes adds an open source pricing form in the layer5.io/pricing page

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-12-23 10:29 UTC, l5io commented
🚀 Preview for commit 504bd08249770d8bc8b35f344e8387dd27779cf5 at: https://67693b32d3b3402316bb7e27--layer5.netlify.app

2024-12-27 13:46 UTC, l5io commented
🚀 Preview for commit bc19fc078a9fbdbf11f6986149fbb473171a0ecc at: https://676eaf66dffd102a5c3aa6a0--layer5.netlify.app

2024-12-27 14:03 UTC, l5io commented
🚀 Preview for commit 0bf65b9ac3e76288f191f816fe144bb34da3e868 at: https://676eb35a8b0d2329d43b1e33--layer5.netlify.app

2024-12-28 10:02 UTC, vishalvivekm commented
@SAHU-01 
As I take a look at the form, a theme issue:
![Screenshot_20241228-153053](https://github.com/user-attachments/assets/ffa5b618-f260-4178-9094-bc85c7164014)

2024-12-31 18:44 UTC, leecalcote commented
I wonder if this PR is dependent upon #6132

2025-01-04 19:59 UTC, leecalcote commented
@vishalvivekm review needed.

2025-01-05 10:48 UTC, vishalvivekm requested changes
Updated are needed to be pushed @SAHU-01

2025-02-24 11:17 UTC, closed without merging