Hyperlink to conduct on Community page
layer5io/layer5 pull request #734
Opened 2020-09-08 06:33 UTC by NorbertLuszkiewicz

Signed-off-by: NorbertLuszkiewicz <norbertluszkiewicz00@gmail.com>

**Description**

  I added hyperlink to full-length code of conduct on Community page

This PR fixes #

 

**Notes for Reviewers**

  https://github.com/layer5io/layer5/issues/730

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

2020-09-08 20:08 UTC, Tanuj22 commented
@NorbertLuszkiewicz thanks for jumping in. There is a merge conflict can you look into it?

2020-09-09 01:37 UTC, leecalcote commented
Thank you, @Jashpatel1. I went ahead and resolved the conflict. 👍

2020-09-09 20:21 UTC, Tanuj22 requested changes
Just some minor changes if you would look into them @NorbertLuszkiewicz 

![Screenshot from 2020-09-10 01-49-15](https://user-images.githubusercontent.com/42486853/92648955-eb867680-f307-11ea-8cf0-d840a76ee265.png)
The color should be gray only for hover.

2020-09-09 20:21 UTC, Tanuj22 commented on _includes/community/meshmates-program.html
> +    form.
the text is "this incident form". The "form" part is repeating twice

2020-09-10 03:36 UTC, Nikhil-Ladha commented
Also, the MeshMate page is not responsive. Can you pleasese fix that too?

2020-09-10 16:42 UTC, Tanuj22 commented
> Also, the MeshMate page is not responsive. Can you pleasese fix that too?

Nice work here @NorbertLuszkiewicz :100: .Can you also have a look at this^^

2020-09-11 06:36 UTC, NorbertLuszkiewicz commented
Looking responsive
 ![img](https://i.imgur.com/StEuV2v.png)
 ![img](https://i.imgur.com/xVThUDV.png)

2020-09-11 06:46 UTC, Nikhil-Ladha commented
![Screenshot from 2020-09-11 12-14-39](https://user-images.githubusercontent.com/29438875/92877198-8aa28f80-f428-11ea-9e15-f110c0cb2d05.png)
This is for the tablet view.

2020-09-11 07:13 UTC, NorbertLuszkiewicz commented
ok I'll take care of it

2020-09-13 20:52 UTC, leecalcote approved these changes
Thank you, @NorbertLuszkiewicz. 👍

2020-09-13 20:53 UTC, merged