Jashpatel1/themecolors
layer5io/layer5 pull request #803
Opened 2020-09-23 06:48 UTC by Jashpatel1

**Description**

This PR fixes #672 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2020-09-23 09:41 UTC, Tanuj22 requested changes
Also change the heading colors from blue. Try the color for smp blue

2020-09-23 09:41 UTC, Tanuj22 commented on src/sections/Navigation/navigation.style.js
> +              color: #00b39f; !important;
Don't hardcode the colors.

2020-09-23 09:41 UTC, Tanuj22 commented on src/sections/Navigation/navigation.style.js
> +          background: #00b39f;
same

2020-09-23 09:41 UTC, Tanuj22 commented on src/sections/Navigation/navigation.style.js
> +          color: #00b39f;
same

2020-09-24 14:14 UTC, Tanuj22 commented
@leecalcote @Nikhil-Ladha @chandrashritii thoughts here. I don't think the SMP Blue color for the headings is not quite fitting here

2020-09-24 15:37 UTC, Nikhil-Ladha commented
I think this color will fit good rgb(59 73 79)

2020-09-24 18:11 UTC, leecalcote commented
> I think this color will fit good rgb(59 73 79)

The color of RGB (60, 73, 78), which is Hex #3C494E (that comes from layer5.io/brand) is close to the one that you're suggesting, @Nikhil-Ladha and might be a good one to try.

2020-09-24 18:19 UTC, leecalcote commented
Soon, we will be able to refer to the [Layer5 Style Guide](https://docs.google.com/presentation/d/12XWzUN3MqCm4jchV4RWgkqikPbgkKeTDhipVufNU2BU/edit#slide=id.g984d490928_2_193).

2020-09-24 18:20 UTC, Nikhil-Ladha commented
Oh, I meant that one only, just picked it from the chrome dev 😅

2020-09-24 18:36 UTC, leecalcote commented
I updated the `headingColor` of each of the themes. It's an improvement, but may not be what we keep in the end. Let's give some color some time to settle in and see if it has a lasting fit.

2020-09-24 18:37 UTC, leecalcote approved these changes

2020-09-24 18:37 UTC, merged