iamsurajdc/brandPage
layer5io/layer5 pull request #804
Opened 2020-09-23 11:20 UTC by iamsurajdc

**Description**

This PR fixes [#712](https://github.com/layer5io/layer5/issues/712)

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2020-09-23 12:57 UTC, Tanuj22 requested changes
@iamsurajdc Nice initial work. 
- The gray background is not looking good. Keep it white.
- You have used images for different color pallets. We will want them to be a div filled with the required colors

2020-09-23 15:14 UTC, iamsurajdc commented
@Tanuj22 Thank you for the compliment,
If there would be white `bg`, then It'll lose the differentiating container panes along with the `border-radius` format for respective sections, Are you sure to get rid of grey with white?

2020-09-23 17:45 UTC, Tanuj22 commented
> @Tanuj22 Thank you for the compliment,
> If there would be white `bg`, then It'll lose the differentiating container panes along with the `border-radius` format for respective sections, Are you sure to get rid of grey with white?

I don't think the gray color is looking nice here. @Nikhil-Ladha what you think?

2020-09-23 17:55 UTC, Nikhil-Ladha commented
I agree with @Tanuj22 gray looks a bit odd and doesn't quite goes with the brand colors (which ironically you are working upon 😅).

2020-09-23 18:02 UTC, Nikhil-Ladha commented
> @Tanuj22 Thank you for the compliment,
> If there would be white `bg`, then It'll lose the differentiating container panes along with the `border-radius` format for respective sections, Are you sure to get rid of grey with white?

Well, your point is valid that we won't get the border radius effect just by changing the bg color to white, but adding a box shadow to it will make it look evident. Give that a shot.

2020-09-26 05:09 UTC, leecalcote commented
@iamsurajdc there is a merge conflict that you will want to take a look at.

2020-10-03 09:06 UTC, Tanuj22 requested changes
Great work here @iamsurajdc . A couple of changes needed -

- In the mobile view, the color and the grayscale headings are together. Rather they should be above each of there corresponding parts.
![Screenshot from 2020-10-03 14-21-27](https://user-images.githubusercontent.com/42486853/94987577-ecb46780-0584-11eb-9607-62e25adeddac.png)

- Merge `layer5-ng` branch into your branch. Then use the `Button` component already available. The various classes like `waves` etc. can then be removed safely.

- Create a separate file for each of the sections of `Layer5`, `Mystery`,  `ImageHub` etc. This will make it easier to manage as we add more sections in the future. 

P.S. I know these may seem like many changes but this will make the code more modular and cleaner. If you are stuck somewhere or need more clarification please ask :)

2020-10-05 07:38 UTC, Tanuj22 requested changes
Really awesome work @iamsurajdc. Three small changes and we are good to go. 

- The color pallets should be below there respective headings. Keep the color and grayscale side by side. (This should also be the case in mobile view) Check the current site for reference. 
![Screenshot from 2020-10-05 13-02-18](https://user-images.githubusercontent.com/42486853/95051623-2c0cc080-070b-11eb-8879-04da78c4b122.png)

- Align this to the pallets in meshery and SMP to center in mobile view. 
![Screenshot from 2020-10-05 13-06-09](https://user-images.githubusercontent.com/42486853/95051883-a0476400-070b-11eb-9791-60c66ec0db2a.png)

- Keep the contact us part below the heading in the mobile view. 
![Screenshot from 2020-10-05 13-01-32](https://user-images.githubusercontent.com/42486853/95051913-ab01f900-070b-11eb-9245-567098926f35.png)

2020-10-06 20:44 UTC, leecalcote commented
Looking good, @iamsurajdc. Nearly at the finish line. :)

2020-10-08 18:38 UTC, Nikhil-Ladha commented
A nice improvement here, few more improvements needed:
- The section header should have a bigger font size and should be properly left-aligned similar to other sub-headings.
- The grayscale and the color, colors are getting mixed up as we make the view responsive and move to a mobile view or tablet view. Please fix that.

2020-10-08 18:40 UTC, Nikhil-Ladha commented on src/sections/Brand/index.js
> +import { Link } from "gatsby"
Also, please fix these warnings. This one and 2-3 below it, only on this file.
The warning for unused variables.

2020-10-08 18:41 UTC, Nikhil-Ladha requested changes
@iamsurajdc  ^^

2020-10-08 18:46 UTC, Tanuj22 commented
@Nikhil-Ladha actually @iamsurajdc asked to move forward with this PR as he is unable to make the changes. We can create the issue for the changes needed.

2020-10-08 18:51 UTC, Jashpatel1 commented
> @Nikhil-Ladha actually @iamsurajdc asked to move forward with this PR as he is unable to make the changes. We can create the issue for the changes needed.

Yes, I think we can move with these changes and open up another issue for updates, if it suits well @Nikhil-Ladha

2020-10-08 19:08 UTC, Nikhil-Ladha commented
Ohh, ok ok. No worries.
Good that you spoke and confronted that @iamsurajdc :+1: 
Let's move forward over here...some more updates can be made in future PRs!

2020-10-08 19:09 UTC, Nikhil-Ladha approved these changes
Good work here @iamsurajdc :sunglasses:

2020-10-08 19:14 UTC, Jashpatel1 commented
Great work here @iamsurajdc with sheer patience.

2020-10-08 19:15 UTC, Tanuj22 approved these changes
Thank you @iamsurajdc for this great work :). Can you create an issue for all the changes that are left to be done?

2020-10-08 19:15 UTC, merged

2020-10-08 21:27 UTC, leecalcote commented
@iamsurajdc, I’d say this is worth a GitHub star on the Meshery project. Star your work. :) good of you to deliver this first PR. 👍

2020-10-09 01:20 UTC, iamsurajdc commented
> Thank you @iamsurajdc for this great work :). Can you create an issue for all the changes that are left to be done?

I will