Layer5 ng_#833
layer5io/layer5 pull request #864
Opened 2020-09-30 17:24 UTC by jomefavourite

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2020-09-30 18:48 UTC, Tanuj22 requested changes
@jomefavourite The format of the file should be like the existing news article present not like ones in the current site otherwise it won't show up.

2020-09-30 18:48 UTC, Tanuj22 commented on package.json
> +    "gatsby": "^2.24.65",
revert this please

2020-09-30 18:48 UTC, Tanuj22 commented on src/collections/news/2019-12-27-vendors-make-a-splash-in-2019-service-mesh-implementation-rush/index.mdx
> +---
The format of this file should be like the existing news article present. Please look at them.

2020-09-30 19:00 UTC, jomefavourite commented
Okay, but I'm having a hard time , since im not conversant with React. If you could help out...

2020-09-30 19:18 UTC, Tanuj22 commented
@jomefavourite have a look at this file - https://raw.githubusercontent.com/layer5io/layer5/layer5-ng/src/collections/news/0000-00-00-news-template/index.mdx .  You have to replace the title, erul, etc. accordingly. The the content would be between the opening and closing `<NewsWrapper>` tags.

2020-09-30 20:06 UTC, leecalcote commented
@jomefavourite thanks for plugging away here. It's inspiring to see you breaking into Reactjs. 💪

2020-09-30 20:34 UTC, jomefavourite commented
@leecalcote Thanks

2020-09-30 20:34 UTC, jomefavourite commented
> @jomefavourite have a look at this file - https://raw.githubusercontent.com/layer5io/layer5/layer5-ng/src/collections/news/0000-00-00-news-template/index.mdx .  You have to replace the title, erul, etc. accordingly. The the content would be between the opening and closing `<NewsWrapper>` tags. 

Thanks for making it clear

2020-10-02 14:23 UTC, Tanuj22 commented
done in #887

2020-10-02 14:23 UTC, closed without merging