Added NGINX Service Mesh
layer5io/layer5 pull request #967
Opened 2020-10-14 23:58 UTC by malanmurphy

**Description**

Initial NGINX Service Mesh release info; NSM product icon; updated existing Nginx references to NGINX

**Notes for Reviewers**

I set the following values as unknowns. Please let me know if this is a valuation that I would add. 

 multi-tenant-score: ?
 netdev-persona-score: ?

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2020-10-15 02:57 UTC, Jashpatel1 requested changes

2020-10-15 02:57 UTC, Jashpatel1 commented on _data/landscape/meshes.yml
> +  multi-tenant-score: ?
Enclose the question mark inside double quotes

2020-10-15 02:57 UTC, Jashpatel1 commented on _data/landscape/meshes.yml
> +  netdev-persona-score: ?
Same as above

2020-10-15 22:32 UTC, malanmurphy commented on _data/landscape/meshes.yml
> +  netdev-persona-score: ?
re-pushed updates. Thx!

2020-10-16 02:54 UTC, Jashpatel1 approved these changes
Just a small change. If you could sign your commits, we are ready to go. Thanks @malanmurphy

2020-10-16 03:57 UTC, Nikhil-Ladha commented
@leecalcote if you can please confirm the data.

2020-10-16 03:58 UTC, Nikhil-Ladha commented on _data/landscape/non-functional.yml
> +  timeline-order: 21
It should be 22

2020-10-16 03:59 UTC, Nikhil-Ladha commented on _data/landscape/proxies.yml
> +  desc: "nginMesh - launched in September 2017, the nginMesh project deploys NGINX as a sidecar proxy in Istio."
This is repeated, it needs to be removed.

2020-10-22 17:13 UTC, Nikhil-Ladha approved these changes

2020-10-22 17:14 UTC, merged

2020-10-22 20:49 UTC, leecalcote commented
It's a beautiful thing, @malanmurphy. 😄

2020-10-27 06:18 UTC, PluckyPrecious commented
Fixes #926