added community page
layer5io/layer5 pull request #974
Opened 2020-10-17 10:16 UTC by codetheorem

Signed-off-by: Hrishikesh Agarwal <hrishikeshagarwalv@gmail.com>

**Description**
Added community page.

This PR fixes #793 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2020-10-17 10:25 UTC, codetheorem commented
Screen Shot of the Page-

![screencapture-localhost-8000-community-1602930267713](https://user-images.githubusercontent.com/54779517/96334820-29a65100-1091-11eb-9efb-4400f81252e2.png)

2020-10-18 09:07 UTC, Tanuj22 requested changes

2020-10-18 09:07 UTC, Tanuj22 commented on src/sections/Community/Community.js
> +                        >Join the Community</a>
Use the `Button` component and remove the classes defined for this

2020-10-18 09:07 UTC, Tanuj22 commented on src/sections/Community/Community.js
> +                <h3 className="h3link">
Do not add custom styling for links. Color will be changed later globally for links

2020-10-18 09:07 UTC, Tanuj22 commented on src/sections/Community/community.style.js
> +    h3 {
Don't change the styles of already defined tags.

2020-10-18 09:07 UTC, Tanuj22 commented on src/sections/Community/community.style.js
> +    h6 {
Don't change the styles of already defined tags.

2020-10-18 09:07 UTC, Tanuj22 commented on src/sections/Community/community.style.js
> +    h1, h2, h3, h4, h5, h6 {
Don't change the styles of already defined tags.

2020-10-18 09:07 UTC, Tanuj22 commented on src/sections/Community/community.style.js
> +    a {
Don't change the styles of already defined tags.

2020-10-18 09:07 UTC, Tanuj22 commented on src/sections/Community/community.style.js
> +    .h3link{
Don't change the styles of already defined tags.

2020-10-18 09:07 UTC, Tanuj22 commented on src/sections/Community/community.style.js
> +    .btn{
remove after using `Button` component

2020-10-18 09:07 UTC, Tanuj22 commented on src/sections/Community/community.style.js
> +    .btn:hover{
remove

2020-10-18 09:07 UTC, Tanuj22 commented on src/sections/Community/Community.js
> +import image from "../../assets/images/community/datacenter-crash.svg";
Use a better name than `image`

2020-10-18 09:07 UTC, Tanuj22 commented on src/sections/Community/CommunityMembers.js
> +import image from "../../assets/images/community/Layer5-mentor-program.png";
same

2020-10-18 09:07 UTC, Tanuj22 commented on src/sections/Community/community.style.js
> +    .link{
remove

2020-10-19 09:54 UTC, codetheorem commented
@Tanuj22 please review it.

2020-10-19 10:27 UTC, Tanuj22 requested changes
Also, the table is not responsive in mobile view

2020-10-19 10:27 UTC, Tanuj22 commented on src/sections/Community/Community.js
> +            <h3>Largest collection of
Center this and use h2

2020-10-19 10:27 UTC, Tanuj22 commented on src/sections/Community/Community.js
> +                <h6>Open Source Projects</h6>
use h4

2020-10-19 10:27 UTC, Tanuj22 commented on src/sections/Community/Community.js
> +                    >Repository Overview</a>
Center this like the one in current page

2020-10-19 10:27 UTC, Tanuj22 commented on src/sections/Community/CommunityMembers.js
> +            <h3 className="black-text">Our Community Members</h3>
h2

2020-10-19 10:27 UTC, Tanuj22 commented on src/sections/Community/CommunityMembers.js
> +                <h6>Jump in! The community is warm</h6>
h5

2020-10-19 10:27 UTC, Tanuj22 commented on src/sections/Community/CommunityMembers.js
> +                        <a href="/community/members">See our community members</a>
use `Link`

2020-10-19 10:27 UTC, Tanuj22 commented on src/sections/Community/MeshmatesProgramSummary.js
> +                            href="/community/meshmates"
use `Link`

2020-10-19 10:27 UTC, Tanuj22 commented on src/sections/Community/MeshmatesProgramSummary.js
> +                <h3>Layer5 MeshMates</h3>
h2

2020-10-19 10:27 UTC, Tanuj22 commented on src/sections/Community/MeshmatesProgramSummary.js
> +                <h6>An onboarding and mentoring program</h6>
h5

2020-10-19 12:30 UTC, codetheorem commented
I have added overflow-x auto so that anybody can scroll in horizontal to view table.

2020-10-19 17:06 UTC, Tanuj22 approved these changes
Looks good. Thanks for working on this :)

2020-10-19 17:06 UTC, merged